### ISSUE TITLE
Observatorio Municipal para la Inclusión Social de Málaga

### ISSUE THREAD

**Issue by sbkspain** [JaimeObregon/observatoriospublicos.es#100]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Municipal para la Inclusión Social

### Sitio web

https://observatoriosocial.malaga.eu/

### Correo electrónico

observatorio.social@malaga.eu

### Organismos públicos de los que depende

Área de Derechos Sociales

### Ámbito territorial

local

### Tipo

publico

### Informes publicados

https://observatoriosocial.malaga.eu/publicaciones/

### Descripción

Herramienta operativa del Área de Derechos Sociales diseñada para conocer la realidad social de Málaga en general y de las personas usuarias del Sistema Público de Servicios Sociales en particular.

Consta de un equipo interdisciplinar de profesionales del Trabajo Social y la Informática con especialización en investigación social y comunitaria.
Objetivos

    Proporcionar la información necesaria para la toma de decisiones en la planificación e intervención social.
    Investigación sobre las causas y consecuencias de la pobreza y la exclusión social.

Realiza estudios e investigaciones encaminadas a mantener actualizado el Diagnóstico Social de la ciudad, entendiendo este, como un proceso permanente de análisis social de la ciudad, en el que se enmarcan todas las publicaciones.

### Fecha de inicio

2011

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
