### ISSUE TITLE
[NUEVO OBSERVATORIO] Observatori de la Bretxa Digital

### ISSUE THREAD

**Issue by jovimon** [JaimeObregon/observatoriospublicos.es#101]
### Nombre del observatorio (OBLIGATORIO)

Observatori de la Bretxa Digital

### Sitio web

https://brechadigital.gva.es/

### Correo electrónico

observatorio_dglbd@gva.es

### Organismos públicos de los que depende

Generalitat Valenciana - Conselleria de Innovación, Industria, Comercio y Turismo

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

2023 CUADERNO DIGITAL EN EL SECTOR AGRARIO
2023 GUIA BASICA PARA CREAR CONTENIDO ACCESIBLE EN LAS REDES SOCIALES
2023 GUIA BASICA DE DOCUMENTOS ACCESIBLES
2023 GUIA BASICA DE ACCESIBILIDAD WEB
2023 INVESTIGACION, TRANSFERENCIA Y COMUNICACION. ACCIONES Y RESULTADOS EN TORNO A BRECHA DIGITAL GENERACIONAL
...
https://brechadigital.gva.es/es/publicacions

### Descripción

Nuestra sociedad está cada vez más interconectada y disponer de acceso a la esfera digital representa una necesidad indispensable para nuestra vida diaria.
En este sentido, resulta imprescindible en el actual contexto disponer de un punto de encuentro en el que todos los sectores, tanto el público como el privado, vinculados a la problemática de la brecha digital y del avance de la sociedad digital, puedan exponer sus propuestas, demandas y sugerencias, reforzando así el papel de participación de la sociedad civil organizada y la intercomunicación con la administración autonómica, constituyéndose en plataforma de intercambio y colaboración, compartiendo el conocimiento y la información.
Es un órgano colegiado y consultivo que dependiendo de la Dirección General competente en materia de lucha contra la brecha digital trata de ser un foro de participación que permita el impulso compartido entre las administraciones públicas, los agentes económicos y sociales y la sociedad civil organizada en la lucha contra la brecha digital. Servirá de plataforma para planificar, estudiar y analizar el entorno y la realidad socioeconómica valenciana en materia de brecha digital.

### Fecha de inicio

18 de marzo de 2021, mediante el [DECRETO 43/2021, de 18 de marzo, del Consell, de creación del Observatorio de Brecha Digital.](https://dogv.gva.es/es/resultat-dogv?signatura=2021/3198&L=1)

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
