### ISSUE TITLE
Observatorio Tributario Andaluz

### ISSUE THREAD

**Issue by JuanBreva** [JaimeObregon/observatoriospublicos.es#102]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Tributario Andaluz

### Sitio web

https://ota.malaga.eu/

### Correo electrónico

ota@malaga.eu

### Organismos públicos de los que depende

Ayuntamiento de Málaga.

### Ámbito territorial

local

### Tipo

publico

### Informes publicados

https://ota.malaga.eu/informes/

### Organismos que lo componen

Citando desde su propia página (esto es de locos): El **Organismo Autónomo de Gestión Tributaria** (...) se elabora desde el **Departamento de Estadísticas y Estudios**, adscrito a la **Subdirección de Presupuestos, Control y Estudios del O. A. de Gestión Tributaria del Ayuntamiento de Málaga**, a través de _un grupo de trabajo formado por técnicos_, con titulación universitaria superior, con gran experiencia en el análisis, la investigación y la recopilación de datos relevantes de informes oficiales, publicaciones y paginas web de las principales entidades, instituciones estadísticas y administraciones públicas del país.

### Descripción

«Constituir un instrumento de transparencia orientado a la investigación de la tributación local, la financiación a través de transferencias de otras administraciones, y en general, cualquier información de naturaleza económica con incidencia en el ámbito de la Administración Municipal.»

### En activo

Sí

**Comment by JaimeObregon** [comment]
¡Añadido! :)
