### ISSUE TITLE
Participación ciudadana navarra

### ISSUE THREAD

**Issue by Spurgus** [JaimeObregon/observatoriospublicos.es#103]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la participación ciudadana en Navarra

### Sitio web

https://gobiernoabierto.navarra.es/es/participacion/enviar-aportacion/1587/observatorio-participacion-ciudadana-navarra

### Organismos públicos de los que depende

Gobierno abierto..presidencia

### Ámbito territorial

autonómico

### Tipo

mixto

### Informes publicados

No hay informes publicados solo un plan de impulso a la.actividas 2016/17.
https://gobiernoabierto.navarra.es/es/participacion/1587/impulso-participacion-ciudadana-navarra-2016-2019

### Organismos que lo componen

Presidencia del Gobierno en colaboración con el Departamento de Sociología de la UPNa y del Colegio de Sociología y Politología de Navarra

### Descripción

.
Navarra.Las funciones de este Observatorio de nueva creación serían la de identificar y servir de intercambio de información sobre experiencias participativas consideradas de un especial interés, tanto en Navarra como fuera de ella, para su divulgación y gestión de buenas y malas prácticas en esta materia. Asimismo, se pretende poner en marcha un seminario de personas expertas que coadyuven al desarrollo del Plan de Impulso de la Participación Ciudadana, así como la presentación de un proyecto innovador en esta materia

### Fecha de inicio

2016

### Cese de actividad

No parece tener actividad.

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
