### ISSUE TITLE
Observatorio de la Violencia de Género

### ISSUE THREAD

**Issue by sbkspain** [JaimeObregon/observatoriospublicos.es#104]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Violencia de Género

### Sitio web

https://observatorioviolencia.org

### Correo electrónico

observatorioviolencia@fundacionmujeres.es

### Ámbito territorial

estatal

### Tipo

mixto

### Informes publicados

https://observatorioviolencia.org/informes-e-investigaciones/

### Descripción

Uno de nuestros objetivos fundacionales es la intervención a favor de la prevención y erradicación de la violencia de género, entre nuestras actividades, pretendemos fomentar el conocimiento social de esta realidad y difundir a la opinión pública los datos obtenidos, estudios y actuaciones contra la violencia ejercida sobre las mujeres.

De este modo en el año 2005 surge el Observatorio de la Violencia de Género, donde diariamente recopilamos, a través de los medios de comunicación, y fuentes oficiales e institucionales relacionadas con la violencia de género, noticias, opiniones e informes que puedan ser de interés no sólo para profesionales en la materia, sino para la población en su conjunto.

### Fecha de inicio

2005

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
