### ISSUE TITLE
Observatorio Turístico

### ISSUE THREAD

**Issue by JuanBreva** [JaimeObregon/observatoriospublicos.es#105]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Turístico

### Sitio web

https://visita.malaga.eu/profesional/es/observatorio-turistico

### Correo electrónico

visita@malaga.eu

### Organismos públicos de los que depende

El Ayuntamiento de Málaga, la Universidad de Málaga y el Área de Turismo de Málaga.

### Ámbito territorial

local

### Tipo

publico

### Informes publicados

https://visita.malaga.eu/profesional/es/observatorio-turistico/informes

### Descripción

De su web: El Observatorio Turístico de la Ciudad de Málaga es una iniciativa que el Área de Turismo del Excmo. Ayuntamiento de Málaga y la Universidad de Málaga ponen en marcha en el año 2008.

El objetivo de este informe estadístico, de carácter anual, es conocer de una forma completa e integrada las pautas de la visita y el perfil del visitante, tanto turistas como excursionistas, entre otros aspectos. Es decir, se trata de determinar los perfiles del visitante que llega a la ciudad de Málaga: cuáles son sus motivaciones iniciales, cómo organizan su viaje, qué tipo de actividades realizan durante su estancia, cómo valoran la oferta disponible y el viaje en función de sus expectativas iniciales, entre otros aspectos relevantes.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
