### ISSUE TITLE
Observatorio de la Movilidad Viaria de Málaga (MOVIMA)

### ISSUE THREAD

**Issue by JuanBreva** [JaimeObregon/observatoriospublicos.es#107]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Movilidad Viaria de Málaga (MOVIMA)

### Sitio web

https://movilidad.malaga.eu/es/lineas-de-trabajo/movima/

### Correo electrónico

movilidad@malaga.eu

### Organismos públicos de los que depende

Ayuntamiento de Málaga.

### Ámbito territorial

local

### Tipo

publico

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
