### ISSUE TITLE
[NUEVO OBSERVATORIO] - Observatori d'IA per a l'Administració Pública

### ISSUE THREAD

**Issue by jovimon** [JaimeObregon/observatoriospublicos.es#109]
### Nombre del observatorio (OBLIGATORIO)

Observatori d'IA per a l'Administració Pública

### Sitio web

https://observatorioia.gva.es/

### Organismos públicos de los que depende

Generalitat Valenciana - Conselleria d'Innovació, Indústria, Comerç i Turisme

### Ámbito territorial

autonómico

### Tipo

publico

### Descripción

Sobre la Inteligencia Artificial (IA) no existe una única definición. De hecho, el concepto es bastante difuso, ya que la IA es una ciencia multidisciplinaria que se desarrolla en campos tan diversos como la neurología, la agricultura o las matemáticas y los avances tecnológicos asociados a ella se producen a un ritmo vertiginoso.

La IA nació motivada por la inquietud del hombre de imitar la naturaleza y a sí mismo, de imitar la inteligencia humana. Hoy en día es un campo específico de la ingeniería informática que se centra en la creación de sistemas capaces de recopilar datos, tomar decisiones y resolver problemas considerando como guía el comportamiento humano y las reglas y comportamientos que se encuentran en la naturaleza.

La creación y puesta en marcha del Observatorio de Inteligencia Artificial para la Administración Pública (OIAAP) es uno de los compromisos que el Consell de la Generalitat se fijó en el Seminario de Invierno de 2017, con el fin de contar con información actualizada sobre los avances en Inteligencia Artificial aplicada a la gestión de la Administración Pública y la atención al ciudadano. El observatorio es de carácter público, por lo que tanto investigadores, como empresas y particulares tienen acceso libre a la información que este genera.

Con este observatorio, la Generalitat persigue estar al tanto de las últimas tendencias en este campo con el fin de aplicarlas a la modernización de los servicios públicos. El OIAAP pretende, con el tiempo, servir para identificar los casos de uso y oportunidades de mejora presentes en la Administración valenciana para el desarrollo de proyectos innovadores que permitan aplicar las ventajas que ofrece la IA a la sociedad.

De este modo, se podrían ofrecer servicios modernos mediante, entre otros, la utilización de "bots" conversacionales para la atención a la ciudadanía, nuevos modelos en programas para la prevención de incendios forestales, soluciones innovadoras para la detección de colectivos vulnerables, etc.

El Observatorio de Inteligencia Artificial para la Administración Pública es un ente dependiente de la [Conselleria de Innovación, Universidades, Ciencia y Sociedad Digital](https://innova.gva.es/), a través de la Dirección General para el Avance de la Sociedad Digital.

Para conocer un poco más sobre la historia de la Inteligencia Artificial, identificar a los [agentes implicados](https://observatorioia.gva.es/es/imprescindibles#p_p_id_56_INSTANCE_cRDjJJr6WlEu_) y comenzar a manejarse con los términos más habituales empleados en este campo, existen diversas iniciativas como el [Léxico del Correo de la UNESCO](https://es.unesco.org/courier/2018-3/lexico-inteligencia-artificial), el diccionario tecnológico [Datapedia](http://luca-d3.com/es/diccionario-tecnologico/index.html) de Telefónica o los [Cuadernos de la Fundación General CSIC](http://www.fgcsic.es/lychnos/es_es/articulos/inteligencia_artificial), entre muchas otras.

### Fecha de inicio

9 de junio de 2023, según el [DECRETO 85/2023, de 9 de junio, del Consell, de creación del Observatorio de la Inteligencia Artificial de la Comunitat Valenciana](https://dogv.gva.es/es/resultat-dogv?signatura=2023/6578&L=1).

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
