### ISSUE TITLE
[NUEVO OBSERVATORIO]

### ISSUE THREAD

**Issue by arodrrosa** [JaimeObregon/observatoriospublicos.es#110]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Permanente del Mercado de los Servicios Portuarios

### Sitio web

https://observatorio.puertos.es/Paginas/Observatorio.aspx

### Correo electrónico

observatorio@puertos.es

### Organismos públicos de los que depende

Organismo Público Puertos del Estado

### Ámbito territorial

estatal

### Tipo

publico

### Descripción

El Observatorio Permanente del Mercado de los Servicios Portuarios, se constituyó en diciembre de 2012, según los criterios que contempla el Texto Refundido de la Ley de Puertos del Estado y de la Marina Mercante, como un instrumento para analizar las condiciones de competitividad en relación con los precios y calidad de los servicios portuarios, y acordar las variables de competitividad sobre las que establecer recomendaciones.

### Fecha de inicio

11-12-2012

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido :)
