### ISSUE TITLE
Obsam

### ISSUE THREAD

**Issue by Smaikel10** [JaimeObregon/observatoriospublicos.es#111]
### Nombre del observatorio (OBLIGATORIO)

Observatori Socioambiental de Menorca

### Sitio web

https://www.obsam.cat/

### Correo electrónico

smn.obsam@cime.es

### Organismos públicos de los que depende

Instituto Menorquín de Estudios

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
