### ISSUE TITLE
[NUEVO OBSERVATORIO] - Observatori de preus de la Comunitat Valenciana

### ISSUE THREAD

**Issue by jovimon** [JaimeObregon/observatoriospublicos.es#112]
### Nombre del observatorio (OBLIGATORIO)

Observatori de preus de la Comunitat Valenciana

### Sitio web

https://argos.gva.es/va/web/prospectiva/observatori

### Organismos públicos de los que depende

Generalitat Valenciana - Consellería de Economía Sostenible, Sectores Productivos, Comercio y Trabajo

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
