### ISSUE TITLE
[NUEVO OBSERVATORIO] Medicamentos peligrosos

### ISSUE THREAD

**Issue by tintintino** [JaimeObregon/observatoriospublicos.es#113]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Nacional de Medicamentos Peligrosos

### Sitio web

https://www.consejogeneralenfermeria.org/observatorio-nacional/observatorio-nacional-de-medicamentos-peligrosos

### Ámbito territorial

estatal

### Tipo

publico

### En activo

Sí

**Comment by JaimeObregon** [comment]
:D

**Comment by JaimeObregon** [comment]
Ooops. Le quito, porque es del Consejo general de Enfermeria, una entidad que no es pública, y no consta que sea un observatorio con financiación pública.

**Comment by tintintino** [comment]
Sorry Jaime, no me había dado cuenta. Cierro otros 3 issues que dependen del mismo organismo.
