### ISSUE TITLE
[NUEVO OBSERVATORIO] - OBSERVATORIO DE PRECIOS DE LOS PRODUCTOS AGROALIMETARIOS DE LA COMUNITAT VALENCIANA

### ISSUE THREAD

**Issue by jovimon** [JaimeObregon/observatoriospublicos.es#114]
### Nombre del observatorio (OBLIGATORIO)

OBSERVATORIO DE PRECIOS DE LOS PRODUCTOS AGROALIMETARIOS DE LA COMUNITAT VALENCIANA

### Sitio web

https://www.gva.es/es/inicio/atencion_ciudadano/buscadores/departamentos/detalle_departamentos?id_dept=14851

### Ámbito territorial

autonómico

### Tipo

publico

### Fecha de inicio

6 de octubre de 2006, según el [DECRETO 150/2006, de 6 de octubre, del Consell, por el que se crea el Observatorio de Precios de los Productos Agroalimentarios de la Comunitat Valenciana](https://dogv.gva.es/es/resultat-dogv?signatura=2006/11596).

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
