### ISSUE TITLE
Observatorio de Contratación Pública Responsable de Canarias

### ISSUE THREAD

**Issue by purcell2007** [JaimeObregon/observatoriospublicos.es#116]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Contratación Pública Responsable de Canarias

### Sitio web

https://contratacionresponsablecanarias.org/

### Correo electrónico

info@contratacionresponsablecanarias.org

### Organismos públicos de los que depende

Dirección General de Derechos Sociales e Inmigración del Gobierno de Canarias a través del proyecto Integra Responsable

### Ámbito territorial

autonómico

### Tipo

publico

### Organismos que lo componen

https://redanagos.org/
https://www.gobiernodecanarias.org/
https://www.facebook.com/adeicancanaria/
https://eapncanarias.org/

### Descripción

Observatorio de CPR de Canarias
El Observatorio de CPR de Canarias es un órgano de asesoramiento, control y estudio respecto a la contratación pública para la sociedad civil y agentes involucrados.

### Fecha de inicio

2023

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
