### ISSUE TITLE
[NUEVO OBSERVATORIO]

### ISSUE THREAD

**Issue by arodrrosa** [JaimeObregon/observatoriospublicos.es#117]
### Nombre del observatorio (OBLIGATORIO)

Observatori del Canvi Climàtic

### Sitio web

https://climaienergia.com/observatori/

### Correo electrónico

observatori@climaienergia.com

### Organismos públicos de los que depende

Ayuntamiento de Valencia

### Ámbito territorial

local

### Tipo

publico

### Descripción

El Observatori del Canvi Climàtic es el centro educativo y divulgativo de Valencia para formar, concienciar y sensibilizar frente al cambio climático.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
