### ISSUE TITLE
[NUEVO OBSERVATORIO] el Observatorio de la Muerte Digna y de las Comisiones de Mortalidad de las Áreas de Salud.

### ISSUE THREAD

**Issue by hacknlove** [JaimeObregon/observatoriospublicos.es#118]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Muerte Digna y de las Comisiones de Mortalidad de las Áreas de Salud.

### Sitio web

https://www.astursalud.es/noticias/-/noticias/omd

### Organismos públicos de los que depende

https://sede.asturias.es/bopa-disposiciones?p_p_id=pa_sede_bopa_web_portlet_SedeBopaDispositionWeb&p_p_lifecycle=0&_pa_sede_bopa_web_portlet_SedeBopaDispositionWeb_mvcRenderCommandName=%2Fdisposition%2Fdetail&p_r_p_dispositionText=2020-06176&p_r_p_dispositionReference=2020-06176&p_r_p_dispositionDate=03%2F08%2F2020

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
