### ISSUE TITLE
Observatorios Castilla y León

### ISSUE THREAD

**Issue by Rubenfer** [JaimeObregon/observatoriospublicos.es#12]
[OBSERVATORIO DE LA COMUNIDAD DE CASTILLA Y LEÓN (SECCIÓN DE GÉNERO)](https://familia.jcyl.es/web/es/mujer/observatorio-comunidad-seccion-genero.html)
[Observatorio de la Convivencia Escolar](https://www.educa.jcyl.es/convivenciaescolar/es/observatorio-convivencia-escolar)
[Observatorio TransfomAcción y ParticipAcción](https://www.observatoriotransformacion.com/)
[Observatorio Regional de la Sociedad de la Información de Castilla y León (ORSI)](https://www.aytoburgos.es/-/observatorio-regional-de-la-sociedad-de-la-informacion-de-castilla-y-leon-orsi-)
[Observatorio de Agresiones](https://www.saludcastillayleon.es/profesionales/es/prevencion-riesgos-laborales/plan-integral-frente-agresiones/observatorio-agresiones)

**Comment by JaimeObregon** [comment]
Añadidos :)
