### ISSUE TITLE
Observatorio contra la LGTBIfobia de Castilla - La Mancha

### ISSUE THREAD

**Issue by JaySpazio** [JaimeObregon/observatoriospublicos.es#120]
### Nombre del observatorio (OBLIGATORIO)

Observatorio contra la LGTBIfobia de Castilla - La Mancha

### Sitio web

https://observatoriolgtbiclm.com/

### Organismos públicos de los que depende

Desconocido por el momento.

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

Desconocido por el momento.

### Organismos que lo componen

- WADO (Asociación LGTBI+ de Castilla - La Mancha)
- Junta de Comunidades de Castilla - La Mancha
- Instituto de la Mujer de Castilla - La Mancha
- Ayuntamiento de Ciudad Real
- Ayuntamiento de Guadalajara

### Descripción

El Observatorio contra la LGTBIfobia de Castilla – La Mancha es una herramienta de información, asesoramiento, y detección de situaciones LGTBIfobicas, sensibilización, acompañamiento y de formación  hacia las personas Lesbianas, Gays, Trans, Bisexual e Intersexuales (LGTBI), así como a cualquier entidad LGTBI que lo necesite que tiene lugar en nuestra región.

Nuestra misión como observatorio es poder ofrecer recursos e información a las personas LGTBI que lo necesiten, colaborar con demás entidades que quieran participar. Además poder detectar, informar, asesorar, acompañar a las personas que han sufrido delitos de odio con agravante de LGTBIfobia y registrar por medio de datos y demostrar por medios de estudios e informes que la LGTBIfobia continúa existiendo en nuestra región.

Como Observatorio la visión es poder tener varios objetivos fijados a largo plazo como concienciar la LGTBIfobia en la existente actual y erradicar contra la LGTBIfobia.

### Fecha de inicio

7 de Septiembre de 2021 (07-09-2021)

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
