### ISSUE TITLE
Observatori del Treball i Model Productiu

### ISSUE THREAD

**Issue by tabarnia** [JaimeObregon/observatoriospublicos.es#121]
### Nombre del observatorio (OBLIGATORIO)

Observatori del Treball i Model Productiu

### Sitio web

https://observatoritreball.gencat.cat/ca/inici

### Organismos públicos de los que depende

Departament d'Empresa i Treball (Generalitat)

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

https://www.idescat.cat/pec/2017-2020/?id=020202&paae=2024

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
