### ISSUE TITLE
[NUEVO OBSERVATORIO] Observatorio de Transformación y Participación de Castilla y León

### ISSUE THREAD

**Issue by anasonora** [JaimeObregon/observatoriospublicos.es#122]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Transformación y Participación de Castilla y León

### Sitio web

https://www.observatoriotransformacion.com/

### Correo electrónico

observatoriotransformacion@gmail.com

### Organismos públicos de los que depende

Junta de Castilla y León

### Ámbito territorial

autonómico

### Tipo

publico

### Descripción

El Observatorio Tranformación y Participación es un órgano que se constituye para actuar como soporte a la docencia, a la investigación y la participación social. Asentado a nivel autonómico en Castilla y León pretende crear una Red Estatal que aporte soluciones desde la participación social al ámbito de la investigación e innovación aplicada

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
