### ISSUE TITLE
Observatori del Sistema de Salut de Catalunya

### ISSUE THREAD

**Issue by tabarnia** [JaimeObregon/observatoriospublicos.es#123]
### Nombre del observatorio (OBLIGATORIO)

Observatori del Sistema de Salut de Catalunya

### Sitio web

https://observatorisalut.gencat.cat/ca/inici

### Organismos públicos de los que depende

Agència de Qualitat i Avaluació Sanitàries de Catalunya (Generalitat)

### Ámbito territorial

estatal

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
