### ISSUE TITLE
[EDITAR OBSERVATORIO]

### ISSUE THREAD

**Issue by danielserranoh** [JaimeObregon/observatoriospublicos.es#124]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de ferrocarril en España

### Ámbito territorial

None

### Tipo

None

### Descripción

Lo tienes duplicado. También aparece como Observatorio de Ferrocarril en España

### En activo

None

**Comment by JaimeObregon** [comment]
¡Gracias! Arreglado :)
