### ISSUE TITLE
Observatori de la Mort

### ISSUE THREAD

**Issue by tabarnia** [JaimeObregon/observatoriospublicos.es#125]
### Nombre del observatorio (OBLIGATORIO)

Observatori de la Mort

### Sitio web

https://observatorisalut.gencat.cat/ca/observatori_mort/

### Organismos públicos de los que depende

Departament de Salut (Generalitat)

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
