### ISSUE TITLE
Observatorio de Drogodependencias de Castilla - La Mancha

### ISSUE THREAD

**Issue by JaySpazio** [JaimeObregon/observatoriospublicos.es#126]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Drogodependencias de Castilla - La Mancha

### Sitio web

https://sanidad.castillalamancha.es/ciudadanos/observatorio-de-drogodependencias-clm/que-es-el-od

### Organismos públicos de los que depende

Consejería de Sanidad de Castilla - La Mancha
Servicio de Salud de Castilla-La Mancha (SESCAM)

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

- [EL PROBLEMA DEL JUEGO DE AZAR EN LA POBLACIÓN DE CASTILLA-LA MANCHA 2023 (Archivo PDF, abre en nueva página)](https://sanidad.castillalamancha.es/sites/sescam.castillalamancha.es/files/documentos/paginas/archivos/el_problema_del_juego_de_azar_en_la_poblacion_de_clm_2023.pdf)
- [INFORME SOBRE CONSUMO DE HIPNOSEDANTES EN CASTILLA-LA MANCHA 2022 (Archivo PDF, abre en nueva página)](https://sanidad.castillalamancha.es/sites/sescam.castillalamancha.es/files/documentos/paginas/archivos/informe_hipnosedantes_observatorio_drogodependencias_de_clm_2022.pdf)
- [INFORME SOBRE TABACO EN CASTILLA-LA MANCHA 2020 (Archivo PDF, abre en nueva página)](https://sanidad.castillalamancha.es/sites/sescam.castillalamancha.es/files/documentos/paginas/archivos/informe_tabaco_2020.pdf)
- [INFORME SOBRE TABACO EN CASTILLA-LA MANCHA 2017 (Archivo PDF, abre en nueva página)](https://sanidad.castillalamancha.es/sites/sescam.castillalamancha.es/files/documentos/paginas/archivos/informe_sobre_tabaco_en_castilla-la_mancha_2017.pdf)
- [INFORME SOBRE DROGODEEPENDENCIAS EN CASTILLA-LA MANCHA 2016 (Archivo PDF, abre en nueva página)](https://sanidad.castillalamancha.es/sites/sescam.castillalamancha.es/files/documentos/paginas/archivos/informe_sobre_drogodependencias_en_castilla-la_mancha_2016_0.pdf)
- [PROBLEMAS DE SALUD RELACIONADOS CON ABUSO DE DROGAS EN MENORES 2016 (Archivo PDF, abre en nueva página)](https://sanidad.castillalamancha.es/sites/sescam.castillalamancha.es/files/documentos/paginas/archivos/informe_problemas_de_salud_relacionados_con_abuso_de_drogas_en_menores_2016_.pdf)
- [INFORME SOBRE DROGODEPENDENCIAS EN CASTILLA-LA MANCHA 2013 (Archivo PDF, abre en nueva página)](https://sanidad.castillalamancha.es/sites/sescam.castillalamancha.es/files/documentos/paginas/archivos/informe_drogas_2013.pdf)
- [INFORME SOBRE DROGODEPENDENCIAS EN CASTILLA-LA MANCHA 2011 (Archivo PDF, abre en nueva página)](https://sanidad.castillalamancha.es/sites/sescam.castillalamancha.es/files/documentos/paginas/archivos/informe_drogas_2011_ultimo.pdf)
- [INFORME SOBRE DROGODEPENDENCIAS EN CASTILLA-LA MANCHA 2009 (Archivo PDF, abre en nueva página)](https://sanidad.castillalamancha.es/sites/sescam.castillalamancha.es/files/documentos/paginas/archivos/informe_drogas_2009.pdf)

### Organismos que lo componen

Consejería de Sanidad de Castilla - La Mancha
Servicio de Salud de Castilla-La Mancha (SESCAM)

### Descripción

El Observatorio de Drogodependencias de Castilla-La Mancha, se crea como órgano asesor técnico de apoyo científico permanente por la Ley 15/2002, de 11 del 07 del 2002 sobre Drogodependencias y Otros Trastornos Adictivos en Castilla-La Mancha.
 
Sus funciones, recogidas en el artículo 39, son las siguientes:
- Recogida y análisis de la información disponible de fuentes nacionales e internacionales.
- Cooperación y colaboración con otros Observatorios de carácter regional, nacional e internacional.
- Promoción de investigaciones y estudios.
- Mantenimiento de un sistema de indicadores que permita el seguimiento de la evolución del consumo de drogas en Castilla-La Mancha.

### Fecha de inicio

Desconocido.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
