### ISSUE TITLE
Observatorio del Mercado de Trabajo de Castilla - La Mancha

### ISSUE THREAD

**Issue by JaySpazio** [JaimeObregon/observatoriospublicos.es#127]
### Nombre del observatorio (OBLIGATORIO)

Observatorio del Mercado de Trabajo de Castilla - La Mancha

### Sitio web

https://empleoyformacion.castillalamancha.es/observatorio

### Organismos públicos de los que depende

Junta de Comunidades de Castilla - La Mancha
Oficina de Orientación, Formación y Empleo

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

- [Indicadores básicos del mercado de trabajo](https://empleoyformacion.castillalamancha.es/observatorio/indicadores-basicos-mercado-trabajo)
- [Informes EPA Castilla-La Mancha](https://empleoyformacion.castillalamancha.es/observatorio/informe-epa)
- [Informe trimestral del mercado laboral en Castilla-La Mancha](https://empleoyformacion.castillalamancha.es/observatorio/informe-trimestral-mercado-laboral)
- [Estudio anual del Mercado de Trabajo de Castilla-La Mancha](https://empleoyformacion.castillalamancha.es/observatorio/estudio-anual-del-mercado-de-trabajo)
- [Estadísticas de paro registrado](https://empleoyformacion.castillalamancha.es/observatorio/estadisticas-de-paro-registrado)

### Descripción

El Observatorio tiene como misión la de presentar un referente regional en cuanto a las tendencias laborales de la Comunidad, anticipando oportunidades y también dificultades, ayudando a la toma de decisiones en materia de empleo y de formación, proporcionando datos de interés a todos los agentes que intervienen en el Mercado Laboral de Castilla-La Mancha mediante sus estudios, publicaciones y consultas.

Es una herramienta de información permanente y actual sobre el mercado de trabajo de la región, que nace con el objetivo de orientar sobre las demandas de empleo y formativas que surjan en determinados momentos y puntos de la comunidad autónoma.

### Fecha de inicio

Desconocido.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
