### ISSUE TITLE
Observatorio de precios en consumo de Castilla - La Mancha

### ISSUE THREAD

**Issue by JaySpazio** [JaimeObregon/observatoriospublicos.es#129]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de precios en consumo de Castilla - La Mancha

### Sitio web

https://consumo.castillalamancha.es/node/23956

### Organismos públicos de los que depende

Consejería de Sanidad de Castilla - La Mancha. 
> Dirección General de Salud Pública.

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

- [Evolución precios Periodo Navidad 2022 - Diciembre 2023](https://consumo.castillalamancha.es/sites/default/files/2023-12/%28ALEJ%29EVOLUCI%C3%93N%20PRECIO%20MEDIO%20POR%20GRUPO%20DE%20ALIMENTOS%20NAVIDAD23%281%29.pdf) (105.45 KB) 

- [Evolución precios aceites Navidad 2023](https://consumo.castillalamancha.es/sites/default/files/2023-12/%28ALEJ%29EVOLUCI%C3%93N%20PRECIO%20MEDIO%20%20ACEITES%20NAVIDAD23.pdf) (73.39 KB) 

- [Evolución precios Periodo Navidad 3 a 18 de diciembre](https://consumo.castillalamancha.es/sites/default/files/2024-01/%28ALEJ%29EVOLUCION%20PRRCIO%20MEDIO%20POR%20GRUPOS%20DE%20ALIMENTOS%20NAVIDAD23-2%C2%BA.pdf) (735.75 KB) 

-  [Evolución precios aceites Navidad 2023 (Actualización)](https://consumo.castillalamancha.es/sites/default/files/2024-01/%28ALEJ%29EVOLUCION%20PRECIO%20MEDIO%20ACEITE%20OVE%20MARCA%20Y%20MARCA%20BLANCA%282%C2%BACONTROLNAVIDAD%29.pdf) (982.56 KB) 

- [Evolución precios aceites provincias Navidad 2023 (2ª Actualización)](https://consumo.castillalamancha.es/sites/default/files/2024-01/%28ALEJ%28EVOLUCION%20PRECIOS%20AOVE%20PROVINCIAS%20%28ABR-DIC2023%29.pdf) (1007.26 KB) 

- [Evolución precio medio aceites Navidad 2023 (2ª actualización)](https://consumo.castillalamancha.es/sites/default/files/2024-01/%28ALEJ%29EVOLUCION%20PRECIO%20MEDIO%20AOVE%20EN%20CLM.pdf) (435.16 KB) 

- [Evolución precios tipos alimentos Navidad 2023 (2ª actualización)](https://consumo.castillalamancha.es/sites/default/files/2024-01/%28ALEJ%29EVOLUCION%20PRECIO%20TIPOS%20ALIMENTOS%20%28NAVIDAD%202023%29.pdf) (753.17 KB)

### Descripción

El Observatorio de Precios en consumo es una herramienta que el Observatorio de Consumo de Castilla- La Mancha pone a disposición de las personas consumidoras de la región.

El Observatorio de Precios en consumo facilita que las personas consumidoras tomen decisiones de compra informadas con arreglo a criterios económicos.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
