### ISSUE TITLE
Observatorios del Ayuntamiento de Alcalá de Henares

### ISSUE THREAD

**Issue by jccabrejas** [JaimeObregon/observatoriospublicos.es#13]
Mención a un "Observatorio Urbano"
https://www.ayto-alcaladehenares.es/el-salon-de-plenos-acoge-el-acto-ejecutivo-del-plan-de-accion-de-la-agenda-urbana-de-alcala/

Observatorio de violencia de género de Alcalá
https://www.ayto-alcaladehenares.es/el-observatorio-de-violencia-de-genero-de-alcala-ha-atendido-a-mas-de-1500-mujeres-desde-2004-2/

Observatorio sociodemográfico del ayuntamiento de Alcalá de Henares
https://urbanismo.ayto-alcaladehenares.es/observatorio-sociodemografico-2/

Observatorio "Alcalá en cifras"
https://www.ayto-alcaladehenares.es/presentacion-del-observatorio-urbano-alcala-en-cifras/

**Comment by JaimeObregon** [comment]
PR mezclada. Cierro. ¡Gracias, amigo! 👍
