### ISSUE TITLE
Observatori SmartCatalonia

### ISSUE THREAD

**Issue by tabarnia** [JaimeObregon/observatoriospublicos.es#130]
### Nombre del observatorio (OBLIGATORIO)

Observatori SmartCatalonia

### Sitio web

https://observatori.smartcatalonia.gencat.cat/about

### Correo electrónico

smartcatalonia@gencat.cat

### Organismos públicos de los que depende

Administració Oberta de Catalunya (Generalitat)

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
