### ISSUE TITLE
Observatorio Regional de la Convivencia Escolar de Castilla - La Mancha

### ISSUE THREAD

**Issue by JaySpazio** [JaimeObregon/observatoriospublicos.es#131]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Regional de la Convivencia Escolar de Castilla - La Mancha

### Sitio web

https://www.educa.jccm.es/educa-jccm/cm/educa_jccm/tkContent?idContent=62664&locale=en_UK&textOnly=false

### Organismos públicos de los que depende

Junta de Comunidades de Castilla - La Mancha.
> Consejería de Educación, Cultura y Deportes.

### Ámbito territorial

autonómico

### Tipo

publico

### Descripción

El Observatorio Regional de la Convivencia Escolar, se constituye el 1 de abril de 2008, en base al Decreto 3/2008 de la Convivencia Escolar en Castilla-La Mancha. Es un órgano colegiado de carácter consultivo, presidido por la Consejera de Educación  en el que hay una amplia representación institucional, social, política y educativa de Castilla-La Mancha, así como cinco expertos en materia de Convivencia.

Este órgano estuvo en funcionamiento hasta 2011, y no se ha vuelto a convocar hasta 2016.

Desde la Consejería de Educación, Cultura y Deportes, se quiere impulsar de nuevo este órgano de participación y con ello la Convivencia  Escolar en Castilla-La Mancha. En reunión de 1 de febrero de 2016, se renuevan los representantes del Pleno  y se constituye la Comisión Permanente, donde a través de dos grupos de trabajo, se inicia una  nueva andadura en la que se trabajará en torno a tres ejes de trabajo:

- Revisión del Reglamento Interno de Funcionamiento del Observatorio.
- Actuaciones encaminadas al fomento de la igualdad y la convivencia dentro del marco legislativo actual.
- Elaboración de propuestas para la mejora de la convivencia.

### Fecha de inicio

1 de abril de 2008
1 de febrero de 2016

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
