### ISSUE TITLE
Observatorio de Promoción Industrial de Castilla - La Mancha

### ISSUE THREAD

**Issue by JaySpazio** [JaimeObregon/observatoriospublicos.es#132]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Promoción Industrial de Castilla - La Mancha

### Sitio web

NaN

### Organismos públicos de los que depende

Junta de Comunidades de Castilla - La Mancha
> Consejería de Economía, Empresas y Empleo

### Ámbito territorial

autonómico

### Tipo

publico

### Organismos que lo componen

Junta de Comunidades de Castilla - La Mancha.
> Consejería de Economía, Empresas y Empleo.
> Consejería de Desarrollo Sostenible y Fomento.

### Descripción

El Observatorio de Promoción Industrial de Castilla-La Mancha es un órgano consultivo y de participación en el marco del diálogo social, con la capacidad de proponer y analizar las medidas y estrategias para la dinamización industrial de la región.

Este Observatorio tiene sobre la mesa los retos identificados para la industria en la región: el crecimiento de la internacionalización de un sector que es responsable de uno de cada tres euros de las exportaciones de la Comunidad Autónoma, así como la digitalización, la sostenibilidad y la innovación en la industria.

### Fecha de inicio

30 de agosto de 2022 (30/08/2022)

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
