### ISSUE TITLE
Observatorio sobre el BREXIT de Castilla - La Mancha

### ISSUE THREAD

**Issue by JaySpazio** [JaimeObregon/observatoriospublicos.es#133]
### Nombre del observatorio (OBLIGATORIO)

Observatorio sobre el BREXIT de Castilla - La Mancha

### Sitio web

https://ipex.es/global-news/articulos-de-interes/observatorio-de-castilla-la-mancha-sobre-el-brexit/

### Organismos públicos de los que depende

Junta de Comunidades de Castilla - La Mancha
Consejería de Economía, Empresas y Empleo de Castilla - La Mancha
IPEX

### Ámbito territorial

estatal

### Tipo

publico

### Descripción

El IPEX, como organismo dependiente de la Consejería de Economía, Empresas y Empleo, encargado de la promoción internacional de las empresas de Castilla-La Mancha, pone en marcha esta oficina de atención virtual que atiende a las empresas de la región para resolver tus dudas sobre el Brexit.

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
