### ISSUE TITLE
Observatorio de la Actividad Física (OBAFI) de Castilla - La Mancha 

### ISSUE THREAD

**Issue by JaySpazio** [JaimeObregon/observatoriospublicos.es#134]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Actividad Física (OBAFI) de Castilla - La Mancha 

### Sitio web

https://obafi.es/

### Organismos públicos de los que depende

Junta de Comunidades de Castilla - La Mancha

> Dirección General de Juventud y Deportes de Castilla - La Mancha

Universidad de Castilla - La Mancha (UCLM)

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

https://obafi.es/informes-de-centro/ **(NO ACCESIBLES)**

### Descripción

OBAFI es un proyecto compartido entre la Dirección General de Juventud y Deportes de la JCCM y la UCLM, que pretende constituir una herramienta de utilidad pública para conocer los hábitos físico-deportivos y la condición física relacionada con la salud de los escolares castellano-manchegos.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
