### ISSUE TITLE
Observatorio de la Vivienda Colaborativa de Castilla - La Mancha

### ISSUE THREAD

**Issue by JaySpazio** [JaimeObregon/observatoriospublicos.es#136]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Vivienda Colaborativa de Castilla - La Mancha

### Sitio web

https://coacmto.com/observatorio-vivienda-colaborativa-toledo

### Organismos públicos de los que depende

Empresa Municipal de Suelo y Vivienda de Toledo.
Colegio de Arquitectos de Castilla - La Mancha. Demarcación de Toledo.

### Ámbito territorial

autonómico

### Tipo

mixto

### Organismos que lo componen

Empresa Municipal de Suelo y Vivienda de Toledo.
Colegio de Arquitectos de Castilla - La Mancha. Demarcación de Toledo.

### Descripción

Conscientes de la importancia que para la ciudadanía tiene el desarrollo de este tipo de modelos, la EMSV y el Colegio de Arquitectos crean este Observatorio como una herramienta que permita divulgar, formar, debatir y concienciar a nuestra sociedad de las ventajas de este nuevo modelo residencial.

El Observatorio dispondrá de una página en la web del Colegio de arquitectos [www.coacmto.com](https://coacmto.com/coacmto-sede-y-horario-colegio-oficial-de-arquitectos-castilla-la-mancha) donde se informará de las actividades, noticias o jornadas que se programen y dispondrá de un sencillo formulario de inscripción abierto a ciudadanos, profesionales, asociaciones, entidades públicas o privadas que estén interesados en participar en esta iniciativa.

### Fecha de inicio

8 de Mayo de 2023

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
