### ISSUE TITLE
Observatorio de Plagas y Enfermedades Agrícolas de Castilla y León

### ISSUE THREAD

**Issue by anasonora** [JaimeObregon/observatoriospublicos.es#137]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Plagas y Enfermedades Agrícolas de Castilla y León

### Sitio web

https://plagas.itacyl.es/

### Correo electrónico

observatorio.plagas@itacyl.es

### Organismos públicos de los que depende

Junta de Castilla y León

### Ámbito territorial

autonómico

### Tipo

publico

### Descripción

Apoyo directo al agricultor en materia de sanidad vegetal por parte de la Junta de Castilla y León, acorde con un modelo sostenible de la producción y del medio ambiente y orientada a facilitar la convivencia con los patógenos dentro de unos parámetros adecuados de rentabilidad y sostenibilidad económica y ambiental.

El objetivo final es aportar información útil al agricultor como apoyo en sus procesos de toma de decisiones.

### Fecha de inicio

2009

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
