### ISSUE TITLE
Observatorio de Derechos Humanos para el Sáhara Occidental de Castilla - La Mancha

### ISSUE THREAD

**Issue by JaySpazio** [JaimeObregon/observatoriospublicos.es#138]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Derechos Humanos para el Sáhara Occidental de Castilla - La Mancha

### Sitio web

NaN

### Ámbito territorial

autonómico

### Tipo

mixto

### Descripción

**Se autodeterminan como ONG**

https://es-la.facebook.com/people/Observatorio-Derechos-Humanos-Castilla-La-Mancha-para-Sahara-Occidental/100068780931028/

### En activo

None

**Comment by JaimeObregon** [comment]
No es un observatorio público.
