### ISSUE TITLE
Observatorio de la Emancipación Juvenil

### ISSUE THREAD

**Issue by anasonora** [JaimeObregon/observatoriospublicos.es#139]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Emancipación Juvenil en España

### Sitio web

https://www.observatorioemancipacion.org/la-emancipacion-juvenil-en-espana-datos-generales/

### Correo electrónico

info@fepa18.org

### Organismos públicos de los que depende

Gobierno de España
Ministerio de Derecho Sociales y Agenda 030

### Ámbito territorial

estatal

### Tipo

publico

### Informes publicados

Parece que los últimos datos son de 2021 pero la página figura actualizada a 2024

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
