### ISSUE TITLE
Observatorio de Servicios Sociales y Dependencia de Castilla - La Mancha

### ISSUE THREAD

**Issue by JaySpazio** [JaimeObregon/observatoriospublicos.es#140]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Servicios Sociales y Dependencia de Castilla - La Mancha

### Sitio web

NaN

### Organismos públicos de los que depende

Junta de Comunidades de Castilla - La Mancha

> Consejería de Bienestar Social de Castilla - La Mancha

### Ámbito territorial

autonómico

### Tipo

publico

### Organismos que lo componen

Junta de Comunidades de Castilla - La Mancha

> Consejería de Bienestar Social de Castilla - La Mancha

Universidad de Castilla - La Mancha

### Descripción

El Observatorio de Servicios Sociales y Dependencia se configura como un órgano colegiado, de composición interdepartamental, con funciones asesoras, de investigación, formación y trasferencia del conocimiento en materia de servicios sociales y dependencia; que ejercerá sus funciones con plena autonomía y sin dependencia funcional de ningún órgano. El Observatorio pretende contribuir también a la reflexión y mejora de la práctica profesional, promoviendo el trabajo interdisciplinar, un buen clima laboral que cuide a las personas cuidadoras, la agilización y simplificación de trámites, la formación continua, así como la evaluación de procesos y resultados.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
