### ISSUE TITLE
Observatorio de Digitalización en el sector agroalimentario

### ISSUE THREAD

**Issue by acarazop** [JaimeObregon/observatoriospublicos.es#141]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Digitalización en el sector agroalimentario

### Sitio web

https://www.boe.es/buscar/doc.php?id=BOE-A-2024-323

### Organismos públicos de los que depende

Ministerio de Agricultura, Pesca y Alimentación

### Ámbito territorial

estatal

### Tipo

mixto

### Informes publicados

https://www.mapa.gob.es/es/desarrollo-rural/temas/innovacion-medio-rural/estudio_3def_tcm30-655779.pdf

### Organismos que lo componen

Ministerio de Agricultura, Pesca y Alimentación
Grupo Cooperativo Cajamar

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
