### ISSUE TITLE
OBSERVATORIO ANDALUZ DE VIOLENCIA DE GÉNERO

### ISSUE THREAD

**Issue by jose-caballero** [JaimeObregon/observatoriospublicos.es#143]
### Nombre del observatorio (OBLIGATORIO)

OBSERVATORIO ANDALUZ DE VIOLENCIA DE GÉNERO

### Sitio web

https://www.juntadeandalucia.es/institutodelamujer/index.php/2013-08-08-10-31-21/observatorio-andaluz-de-violencia-de-genero

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
