### ISSUE TITLE
OBSERVATORIO ANDALUZ DE LA PUBLICIDAD  NO SEXISTA

### ISSUE THREAD

**Issue by jose-caballero** [JaimeObregon/observatoriospublicos.es#144]
### Nombre del observatorio (OBLIGATORIO)

OBSERVATORIO ANDALUZ DE LA PUBLICIDAD  NO SEXISTA

### Sitio web

https://www.juntadeandalucia.es/institutodelamujer/index.php/observatorio-andaluz-de-publicidad-no-sexista

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
