### ISSUE TITLE
Observatorio de la Infancia y Adolescencia de Andalucía

### ISSUE THREAD

**Issue by jose-caballero** [JaimeObregon/observatoriospublicos.es#145]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Infancia y Adolescencia de Andalucía

### Sitio web

https://www.observatoriodelainfancia.es/oia/esp/index.aspx

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
