### ISSUE TITLE
[NUEVO OBSERVATORIO]

### ISSUE THREAD

**Issue by Amititlan** [JaimeObregon/observatoriospublicos.es#146]
### Nombre del observatorio (OBLIGATORIO)

OBSERVATORIO PARA LA CONVIVENCIA ESCOLAR EN ANDALUCÍA

### Sitio web

https://www.juntadeandalucia.es/educacion/portals/web/convivencia-escolar/estructura-y-funcionamiento

### Correo electrónico

convivenciaescolar.ced@juntadeandalucia.es

### Organismos públicos de los que depende

Consejería de desarrollo educativo y formación profesional de la Junta de Andalucía

### Ámbito territorial

autonómico

### Tipo

publico

### Organismos que lo componen

Artículo 53. Estructura organizativa.
1. Los órganos del Observatorio para la Convivencia Esco-
lar en Andalucía son los siguientes:
a) La Presidencia.
b) El Consejo Rector.
c) La Secretaría.
Artículo 54. Presidencia.
1. La Presidencia del Observatorio para la Convivencia
Escolar en Andalucía será ostentada por la persona titular de
la Consejería competente en materia de educación.
2. La Presidencia ejercerá la representación del Obser-
vatorio.
Artículo 55. Composición del Consejo Rector.
1. El Consejo Rector es el órgano de dirección del Obser-
vatorio para la Convivencia Escolar en Andalucía.
2. El Consejo Rector del Observatorio para la Convivencia
Escolar en Andalucía tendrá la siguiente composición:
a) Presidencia: la persona titular de la Consejería compe-
tente en materia de educación.
b) Vicepresidencia: la persona titular de la Dirección Ge-
neral competente en materia de convivencia escolar.
c) Vocales:
a) Una persona representante, con rango al menos de Di-
rector o Directora General, de las Consejerías que ostenten las
competencias en materia de seguridad ciudadana, igualdad y
bienestar social y justicia y administración pública.
b) La persona titular de la Dirección General competente
en materia de formación del profesorado de la Consejería
competente en materia de educación.
c) La persona titular de la Secretaría General Técnica de
la Consejería competente en materia de educación.
d) El inspector o inspectora general de la Consejería com-
petente en materia de educación.
e) Una persona representante de la Delegación del Go-
bierno en Andalucía.
f) La persona titular de la Presidencia del Consejo Escolar
de Andalucía.
g) Una persona representante del Consejo Andaluz de
Universidades.
h) Una persona representante de las Corporaciones Loca-
les andaluzas, cuya designación corresponde a la Federación
Andaluza de Municipios y Provincias.
i) La coordinadora o el coordinador de la Red Andaluza
«Escuela: Espacio de Paz».
j) Dos directoras o directores de centros educativos que
desarrollen proyectos «Escuela: Espacio de Paz» y que desta-
quen por su trabajo de innovación en la convivencia escolar,
designados por la persona titular de la Dirección General com-
petente en materia de convivencia escolar.
k) Una persona representante por cada una de las orga-
nizaciones sindicales con representación en la Mesa Sectorial
de Educación.
l) Una persona representante por cada una de las orga-
nizaciones sindicales con una representación regional de, al
menos, el diez por ciento en el ámbito de la enseñanza pri-
vada sostenida con fondos públicos, en relación con el total de
representantes sindicales en dicho ámbito.
m) Una persona representante de las organizaciones em-
presariales y de titulares de centros de la enseñanza privada
concertada, designado por la organización más representativa
de los mismos en dicho ámbito.
n) Tres representantes de la Confederación de Asociacio-
nes de Madres y Padres de alumnos más representativa en el
sector de la enseñanza pública.
o) Una persona representante de la Confederación de
Asociaciones de Madres y Padres de alumnos más representa-
tiva en el sector de la enseñanza concertada.
p) Dos representantes de la Federación de Asociaciones
de Alumnas y Alumnos más representativa.
q) Cinco especialistas, personalidades de reconocido
prestigio en la materia, designados por la persona titular de
la Dirección General competente en materia de convivencia
escolar.
r) Dos representantes de entidades e instituciones aca-
démicas de Andalucía que destaquen por su trabajo de inves-
tigación en la materia, designados por la persona titular de la
Dirección General competente materia de convivencia escolar

### Descripción

Funciones

a) Proponer la realización de estudios e investigaciones que permita el seguimiento permanente del estado de la convivencia en los centros educativos, identificando los factores de riesgo y proponiendo acciones efectivas para detener, disminuir y prevenir las manifestaciones de la violencia.

b) Realizar propuestas que, con base en los estudios y evaluaciones realizados, favorezcan la toma de decisiones sobre las políticas educativas destinadas al desarrollo de los objetivos y medidas contenidas en el presente Decreto.

c) Proponer actuaciones coordinadas de las administraciones públicas, en el ámbito de sus respectivas competencias, y con entidades e instituciones privadas, para que se adopten medidas para favorecer los factores de protección y de seguridad necesarios para detener, disminuir y prevenir las manifestaciones de la violencia fuera de los espacios escolares. d) Proponer actuaciones de formación en estrategias de mediación y regulación de conflictos para todos los sectores implicados en la educación. e) Realizar propuestas de mejora sobre la normativa relacionada con las medidas correctoras para la mejora de la convivencia en los centros educativos y su aplicación por parte de los mismos. f) Fomentar y promover encuentros entre profesionales y expertos, para facilitar el intercambio de experiencias, investigaciones y trabajos en esta materia. g) Crear un fondo de documentación para la promoción de actividades de información y el estímulo del estudio y la investigación en la materia, así como contribuir a establecer redes de información entre los centros educativos.

h) Publicar y difundir estudios, materiales y experiencias de educación para la convivencia y cultura de paz. i) Elaborar un informe anual sobre el estado de la convivencia y la conflictividad en los centros educativos, para lo que requerirá el apoyo informativo, documental y técnico de otras Administraciones Públicas con competencia en la materia y de los propios órganos y entidades de la Consejería competente en materia de educación, así como de entidades e instituciones privadas. j) Cualquier otra función de apoyo y asesoramiento vinculada a la recogida, análisis, difusión de la información y la investigación y la promoción de actuaciones en todas las materias relacionadas con la mejora de la convivencia en el ámbito de los centros educativos.

### Fecha de inicio

Febrero 2007 (BOJA Nº 25, 2-2-2007)

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
