### ISSUE TITLE
Obervatorio de Contratación Pública (ObCP)

### ISSUE THREAD

**Issue by JaySpazio** [JaimeObregon/observatoriospublicos.es#147]
### Nombre del observatorio (OBLIGATORIO)

Obervatorio de Contratación Pública (ObCP)

### Sitio web

https://www.obcp.es/

### Organismos públicos de los que depende

- Ministerio de Economía, Comercio y Empresas
- Ministerio para la Transformación Digital y de la Función Pública
- Universidad de Zaragoza
- NTT Data

### Ámbito territorial

estatal

### Tipo

publico

### Organismos que lo componen

- Ministerio de Economía, Comercio y Empresas
- Ministerio para la Transformación Digital y de la Función Pública
- Universidad de Zaragoza
- NTT Data
- Gobierno de Aragón
- Grupo de investigación ADESTER - Universidad de Zaragoza
- Universidad de Castilla - La Mancha
- Universidad de Vigo
- Generalitat de Catalunya
- Ayuntamiento de Zaragoza
- Cámara de Cuentas de Aragón
- Cátedra de la Contratación Pública Local - Universidad de Zaragoza
- Transparency International España
- Cátedra de Proyectos e Inversiones Estratégicas de Aragón - Universidad de Zaragoza

### Descripción

El Observatorio de Contratación Pública es un lugar de encuentro para los profesionales de la materia desde el que proceder al debate y análisis de las novedades introducidas en su ordenación jurídica, así como para la realización de nuevas propuestas de actuación para la modernización de la contratación pública y materializar en la misma los principios de eficiencia, integridad y buena administración.

### Fecha de inicio

Octubre de 2011

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
