### ISSUE TITLE
Observatorio para la Convivencia Escolar en Andalucía

### ISSUE THREAD

**Issue by FernandoLazaro** [JaimeObregon/observatoriospublicos.es#148]
### Nombre del observatorio (OBLIGATORIO)

Observatorio para la Convivencia Escolar en Andalucía

### Sitio web

https://www.juntadeandalucia.es/educacion/portals/web/convivencia-escolar/estructura-y-funcionamiento

### Organismos públicos de los que depende

Consejería de Desarrollo Educativo y Formación Profesional

### Ámbito territorial

autonómico

### Tipo

publico

### Descripción

El Observatorio para la Convivencia Escolar en Andalucía tiene por objeto asesorar a la Junta de Andalucía y formular propuestas sobre el desarrollo de actuaciones de investigación, análisis, valoración y seguimiento de la convivencia escolar, así como contribuir al establecimiento de redes de información entre todos los centros educativos para compartir experiencias de buenas prácticas en este ámbito.

La finalidad del Observatorio es la de contribuir a generar una forma de abordar la convivencia escolar en Andalucía basada en el respeto y el diálogo, en la que el tratamiento constructivo del conflicto forme parte del proceso educativo.

### Fecha de inicio

2 de febrero 2007

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
