### ISSUE TITLE
Observatorio CIBIM

### ISSUE THREAD

**Issue by FernandoLazaro** [JaimeObregon/observatoriospublicos.es#149]
### Nombre del observatorio (OBLIGATORIO)

Observatorio CIBIM

### Sitio web

https://cibim.transportes.gob.es/observatorio-cibim

### Organismos públicos de los que depende

Ministerio de Transportes, Movilidad y Agenda Urbana

### Ámbito territorial

estatal

### Tipo

publico

### Informes publicados

2023
Tercer trimestre - Informe nº23
Segundo trimestre - Informe nº22
Primer trimestre - Informe nº21
2022
Cuarto trimestre 2022 - Informe nº20
Tercer trimestre 2022 - Informe Nº19
Primer semestre 2022 - Informe Nº18
2021
Cuarto trimestre 2021 - Informe nº 17
Tercer trimestre 2021 - Informe nº 16
Segundo trimestre 2021 - Informe nº 15
Primer trimestre 2021 - Informe nº14
2020
Cuarto trimestre 2020 - Informe nº13
Tercer trimestre 2020 - Informe nº12
Segundo trimestre 2020 - Informe nº11
Primer trimestre 2020 - Informe nº10
2019
Cuarto trimestre 2019 - Informe nº 9
Tercer trimestre 2019 - Informe nº 8
Primer semestre 2019 - Informe nº 7
2018
Enero a diciembre 2018 - Informe nº6
Enero a septiembre 2018 - Informe nº5
Enero 2017 a junio 2018 - Informe nº4
Enero 2017 hasta marzo 2018 - Informe nº3
2017
Enero 2017 a diciembre 2017 - Informe nº2
Enero 2017 a septiembre 2017 - Informe nº1

### Descripción

El Ministerio de Transportes, Movilidad y Agenda Urbana creó el Observatorio de Licitaciones Públicas BIM en mayo de 2017 con el objetivo de conocer el avance de la implantación de la metodología BIM en España.

El Observatorio CIBIM revisa periódicamente la publicación de licitaciones públicas en la Plataforma de Contratación del Sector Público y plataformas existentes en Comunidades Autónomas, para identificar la incorporación de requisitos BIM y llevar a cabo un análisis cuantitativo y cualitativo de licitaciones con BIM publicadas en España a lo largo de los últimos años, según distintas clasificaciones.

### Fecha de inicio

Mayo 2017

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
