### ISSUE TITLE
observatorio territorial 

### ISSUE THREAD

**Issue by Spurgus** [JaimeObregon/observatoriospublicos.es#150]
### Nombre del observatorio (OBLIGATORIO)

observatorio territorial de navarra

### Sitio web

https://www.nasuvinsa.es/es/servicios/lursarea/observatorio

### Organismos públicos de los que depende

Nasuvinsa I(empresa publcia 100%) Y presidencia del gobierno de Navarra

El resultado obtenido es útil para orientar políticas sectoriales desde la perspectiva de la ordenación del territorio y la sostenibilidad. También para el seguimiento y la evaluación de la [Estrategia Territorial de Navarra (ETN).](http://www.navarra.es/home_es/Temas/Territorio/Urbanismo/Instrumentos/Instrumentos+OT/ETN/DEFAULT.htm)

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

No constan

### Organismos que lo componen

Nasuvinsa es una empresa publica.
En su web dice que asiste alConsejo Social de politica  territorial  https://participa.navarra.es/assemblies/organo-41?locale=es aque a su vez es una de las herramientas del departamento de Gobierno Abierto (d elos que te gustan, Jaime) y su vocaciòn es ser un espacio de encuentro e interlocución estable..  Lo preside el Vicepresisdente del Gobierno de Navarra, por tanto depende de PRESIDENCIA. 

### Descripción

El CSPT es un órgano de asesoramiento y participación para que los agentes institucionales, sociales, económicos y ambientales puedan colaborar en el seguimiento e impulso del desarrollo territorial sostenible de Navarra, en los términos previstos en el Decreto Foral Legislativo 1/2017, de 26 de julio, por el que se aprueba el [Texto Refundido de la Ley Foral de Ordenación del Territorio y Urbanismo](http://www.lexnavarra.navarra.es/detalle.asp?r=39197).

[Fichas Comarcales](https://www.nasuvinsa.es/es/Ficha_Comarcal)
[BehaLUR-Observaciones Territoriales](https://behalur.nasuvinsa.es/)
[Cooperación transfronteriza](https://www.nasuvinsa.es/es/servicios/lursarea/observatorio/cooperacion-transfronteriza)
[Seguimiento Estrategia Territorial de Navarra (ETN)](https://etn.nasuvinsa.es/)
[Centro de Recursos Territoriales](https://www.nasuvinsa.es/servicios/lursarea/observatorio/centro)

### Fecha de inicio

2017 .- Conforme al  Decreto Foral Legislativo 1/2017, de 26 de julio, por el que se aprueba el [Texto Refundido de la Ley Foral de Ordenación del Territorio y Urbanismo](http://www.lexnavarra.navarra.es/detalle.asp?r=39197).

### Cese de actividad

no consta cese

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
