### ISSUE TITLE
de salud publica de Navarra 

### ISSUE THREAD

**Issue by Spurgus** [JaimeObregon/observatoriospublicos.es#151]
### Nombre del observatorio (OBLIGATORIO)

OBSERVATORIO DE SALUD PUBLICA DE NAVARRA

### Sitio web

https://portalsalud.navarra.es/es/observatorio

### Organismos públicos de los que depende

Deapartamento de Salud/Osasumbidea, Gobierno de Navarra 

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

Indicadores socioeconómicos .-  series estqdísticas  https://portalsalud.navarra.es/documents/11746728/14014754/Indicadores+Navarra+Sociodemograficos.pdf/edf990af-6ce2-b1f6-683a-379b5e19b719?t=1686728893883
Estilos de vida.- https://portalsalud.navarra.es/documents/11746728/14014754/Indicadores+Navarra+Estilos+de+Vida+2023.pdf/e3767ecc-b4e4-f78b-cae5-5e0fc812afdd?t=1678092313421

Mortalidad https://portalsalud.navarra.es/documents/11746728/14014754/Indicadores+Navarra+Mortalidad+2023.pdf/e1f02986-2443-625a-5a86-56a0e314abb4?t=1678092314189

### Organismos que lo componen

Dpto de Salud

### Descripción

pretende ser una cadena de transmisión entre la información y la acción, y un instrumento que ayude a priorizar y manejar de manera efectiva los recursos destinados a la protección, prevención y promoción de la salud, y a actuar en la raíz de las desigualdades. Más allá de fomentar las actuaciones comunitarias de los servicios sanitarios, busca también promover la acción intersectorial, la salud en todas las políticas y los procesos de participación ciudadana.

Objetivo general

Crear conocimiento y generar una estrategia de comunicación de la situación de salud de Navarra, que dé respuesta a las necesidades de información para la acción que tienen los agentes implicados en la promoción y mejora de la salud.

Objetivos específicos:

Contribuir a conocer, analizar e interpretar el estado de salud de la población de la Comunidad de Navarra, y valorar su evolución en el tiempo

Conocer, analizar e interpretar la situación de los principales determinantes de la salud, incluyendo los activos en salud, y valorar su evolución en el tiempo

Conocer, analizar y valorar la evolución en el tiempo de las desigualdades en salud

Establecer canales y crear productos que permitan un acceso fácil a la información, y que ésta sea comprensible para las partes interesadas

Crear evidencia y conocimiento útil para la acción en salud, que permita identificar necesidades prioritarias de actuación a nivel global y local

Facilitar la acción intersectorial y comunitaria en salud, adaptando la información a cada contexto y cada uno de los sectores

### Fecha de inicio

desconocido. 

### Cese de actividad

a dìa de hoy sigue funcionando. Publica algunas excel con datos hasta al menos 2023

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
