### ISSUE TITLE
OBSERVATORIO DE LA JUVENTUD

### ISSUE THREAD

**Issue by Spurgus** [JaimeObregon/observatoriospublicos.es#153]
### Nombre del observatorio (OBLIGATORIO)

OBSERVATORIO JOVEEN

### Sitio web

https://www.juventudnavarra.es/es/observatorio-joven

### Organismos públicos de los que depende

cONSEJO DE LA JUVENTUD

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

Se crea y regula por la [Orden Foral 116/2012, de 27 de marzo](http://www.lexnavarra.navarra.es/detalle.asp?r=26089)

hAY INFORMES en diversas aspectos DESDE  2012 en adelante. entre los últimos,  una encusta sobre emancipacion de la población joven de 2023 y un estudio de  Juventud y cuidados de 2024

### Descripción

 es el órgano encargado de analizar y estudiar la situación de la población joven de la Comunidad Foral de Navarra. El trabajo que realizamos desde el observatorio joven permite analizar y evaluar la situación, demandas y necesidades de la juventud Navarra, para, de esta manera, poder diseñar, elaborar y evaluar diferentes iniciativas, políticas y estrategias destinadas a mejorar las condiciones de vida del colectivo joven.

### Fecha de inicio

2012

### Cese de actividad

no cesa

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
