### ISSUE TITLE
OBSERVATORIO TURÍSTICO

### ISSUE THREAD

**Issue by Spurgus** [JaimeObregon/observatoriospublicos.es#154]
### Nombre del observatorio (OBLIGATORIO)

OBSERVATORIO TURÍSTICO DE NAVARRA

### Sitio web

https://turismoprofesional.navarra.es/es/observatorio-turistico

### Correo electrónico

EN LA WEB

### Organismos públicos de los que depende

departamento de turismo 

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

publica informes, estudios y directivas publicas sobre turismo en navarra  coomel modelo de integracion del turismo itinerante.- https://www.visitnavarra.es/documents/8257989/19042206/Ordenación+T.Itinerante-VD.pdf/123ae990-82b8-f299-4139-4e12333f9515?t=1662553688136

estudios de caracterizaciòn de turistas de otros países, como francia   p ej.. https://turismoprofesional.navarra.es/documents/8257989/28313355/inspektour%28DB22%29_Profile+study_Module+1_Report_Source+market+France_Destination+Région+de+Navarre.pdf/2707f26c-e7cb-8580-5a29-1cec0f401b78?t=1694420417005

### Organismos que lo componen

Depende del servicio de desarrollo sostenible (art 26 y ss de l DF 256/23 que regula este departamento de turismo

### Descripción

facilita diversos estudios, directivas, información de y para operadores turísticos regionales

### Fecha de inicio

2023

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
