### ISSUE TITLE
OBSERVATORIOBANDA ANCHA 

### ISSUE THREAD

**Issue by Spurgus** [JaimeObregon/observatoriospublicos.es#155]
### Nombre del observatorio (OBLIGATORIO)

BANDA ANCHA DE NAVARRA

### Sitio web

https://bandaancha.navarra.es/es/inicio

### Correo electrónico

bandaanchanavarra@navarra.es

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

NO PARECE QEU FACILITE inrmes sino que es un instrumento de desarrollo del plan director de banda ancha de navarra , recopilando información sobre la red, de forma que permita "identificar de manera preliminar las zonas que reúnen las condiciones para ser consideradas como elegibles en actuaciones según los términos de la normativa de ayudas de Estado"

### Organismos que lo componen

se ignora

### Descripción

objetivo es el impulso del despliegue de servicios de banda ancha por parte de operadores de telecomunicaciones. Esta convocatoria financia a operadores con hasta un 80% de subvención el despliegue de servicios de banda ancha de más de 300Mbps en zonas donde no existen servicios de banda ancha de más de 100Mbps. Cada operador presenta una solicitud única para cada una de las comunidades autónomas asignándose la ayuda para cada una de ellas al operador que mejor oferta presente.

### Fecha de inicio

2023

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
