### ISSUE TITLE
[NUEVO OBSERVATORIO] Observatorio de precios agrarios

### ISSUE THREAD

**Issue by Omoloc** [JaimeObregon/observatoriospublicos.es#156]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de precios agrarios

### Sitio web

https://www.larioja.org/agricultura/es/estadistica-agraria/observatorio-precios-agrarios

### Correo electrónico

estadistica.agri@larioja.org

### Organismos públicos de los que depende

Gobierno de la Rioja 

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

Publica uno por semana desde 2010

### Descripción

El Observatorio de precios agrarios muestra semanalmente la evolución del precio que percibe el productor (origen) y el que paga el consumidor (destino). También incorpora costes de producción de diferentes cultivos y especies ganaderas que se irán completando semana a semana.

### Fecha de inicio

2010

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
