### ISSUE TITLE
Observatorio Económico de la Ciudad Autónoma de Melilla

### ISSUE THREAD

**Issue by garbagen** [JaimeObregon/observatoriospublicos.es#157]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Económico de Melilla

### Sitio web

https://elfarodemelilla.es/echa-a-andar-el-observatorio-economico-de-melilla/

### Organismos públicos de los que depende

Consejería de Presidencia

### Ámbito territorial

autonómico

### Tipo

mixto

### Fecha de inicio

11/12/2023

### En activo

Sí

**Comment by garbagen** [comment]
https://melillahoy.es/imbroda-ofrece-a-salomon-serfaty-la-coordinacion-del-nuevo-observatorio-economico-de-melilla/

**Comment by JaimeObregon** [comment]
Añadido.
