### ISSUE TITLE
[Observatori Català de l’Esport]

### ISSUE THREAD

**Issue by carlesreig** [JaimeObregon/observatoriospublicos.es#159]
### Nombre del observatorio (OBLIGATORIO)

Observatori Català de l’Esport

### Sitio web

https://inefc.gencat.cat/ca/inefc/projectes_institucionals/observatori-de-lesport/index.html

### Correo electrónico

observatori@gencat.cat

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

https://inefc.gencat.cat/ca/inefc/projectes_institucionals/observatori-de-lesport/publicacions/projectes/arxivem-esport-temps-covid19/

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
