### ISSUE TITLE
[Observatori Català de la Joventut]

### ISSUE THREAD

**Issue by carlesreig** [JaimeObregon/observatoriospublicos.es#160]
### Nombre del observatorio (OBLIGATORIO)

Observatori Català de la Joventut

### Sitio web

https://dretssocials.gencat.cat/ca/ambits_tematics/joventut/observatori_catala_de_la_joventut/index.html

### Correo electrónico

ocj.dretssocials@gencat.cat

### Organismos públicos de los que depende

Agència Catalana de la Joventut

### Ámbito territorial

estatal

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido :D
