### ISSUE TITLE
Observatorio da Lusofonía Valentín Paz Andrade

### ISSUE THREAD

**Issue by resinor** [JaimeObregon/observatoriospublicos.es#161]
### Nombre del observatorio (OBLIGATORIO)

Observatorio da Lusofonía Valentín Paz Andrade

### Sitio web

No

### Organismos públicos de los que depende

Xunta de Galicia.

Decreto 134/2023, de 28 de septiembre, por el que se crea y se regula el Observatorio de la Lusofonía Valentín Paz Andrade (DOG de 10 de octubre de 2023).

### Ámbito territorial

autonómico

### Tipo

publico

### Organismos que lo componen

El Observatorio se adscribe a la consellería competente en materia de acción exterior y para alcanzar sus objetivos contará con el apoyo y soporte de la Secretaría General de Política Lingüística

### Descripción

El Observatorio tendrá como finalidad asesorar al Gobierno, formular planes de acción y programar actividades de conocimiento, intercambio y programación. Atendiendo a su finalidad, servirá de foro de diálogo permanente entre las distintas administraciones públicas y otras organizaciones representativas de intereses en el ámbito de la lusofonía, a fin de asegurar su participación activa en el abordaje de las relaciones de Galicia en dicho ámbito, así como aglutinará esfuerzos, coordinará las actuaciones público-privadas y procurará la consolidación en el tiempo de Galicia en el mundo de la lusofonía.

### Fecha de inicio

10/10/2023

### En activo

Sí

**Comment by resinor** [comment]
[A Xunta creará o Observatorio da Lusofonía Valentín Paz Andrade para reforzar os lazos entre Galicia e o mundo lusófono](https://www.xunta.gal/notas-de-prensa/-/nova/83523/xunta-creara-observatorio-lusofonia-valentin-paz-andrade-para-reforzar-los-lazos)

[Observatorio de la Lusofonía Valentín Paz Andrade](https://laadministracionaldia.inap.es/noticia.asp?id=1237710)

**Comment by JaimeObregon** [comment]
Añadido.
