### ISSUE TITLE
Observatorio da Industria Aeroespacial

### ISSUE THREAD

**Issue by resinor** [JaimeObregon/observatoriospublicos.es#162]
### Nombre del observatorio (OBLIGATORIO)

Observatorio da Industria Aeroespacial

### Sitio web

https://www.consorcioaeronautico.com/observatorio-aeroespacial/gl/

### Organismos públicos de los que depende

El Observatorio de la industria Aeroespacial es una iniciativa que se desarrolla en el marco de la Civil UAVs Initiative, promovida por la Xunta de Galicia a través da Vicepresidencia Primera y Consellería de Economía, Empleo e Innovación, y llevado a cabo por el Consorcio Aeronáutico Gallego.

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

[financiamento da I+D no sector dos UAVs](https://www.consorcioaeronautico.com/observatorio-aeroespacial/gl/financiamento-da-id-no-sector-dos-uavs/)
[Análise da cadea de valor do sector aeroespacial](https://www.consorcioaeronautico.com/observatorio-aeroespacial/gl/analise-da-cadea-de-valor-do-serctor-aeroespacial/)
[Instrumentos de apoio á internacionalización](https://www.consorcioaeronautico.com/observatorio-aeroespacial/gl/instrumentos-de-apoio-a-internacionalizacion/)
[Análise da evolución das empresas do sector aeronáutico e aeroespacial en Galicia](https://www.consorcioaeronautico.com/observatorio-aeroespacial/gl/diagnostico-da-creacion-neta-de-empresas-aeroespaciais/)
[Informe das contas anuais do sector](https://www.consorcioaeronautico.com/observatorio-aeroespacial/gl/informe-das-contas-anuais-do-sector/)

### Organismos que lo componen

El Observatorio de la industria Aeroespacial es una iniciativa que se desarrolla en el marco de la Civil UAVs Initiative, promovida por la Xunta de Galicia a través da Vicepresidencia Primera y Consellería de Economía, Empleo e Innovación, y llevado a cabo por el Consorcio Aeronáutico Gallego.

### Descripción

Como resultado del convenio firmado entre la Agencia Gallega de Innovación y el CAG, se puso en marcha este observatorio para la generación, atracción, compilación y divulgación de conocimiento experto y estudios científicos en materia aeroespacial. El observatorio persigue ser un centro de referencia a nivel nacional e internacional en la realización y difusión de estudios científicos económicos, estadísticos y de perspectiva del sector aeroespacial.

Elaboración de estudios científicos por actores expertos y con un alto grado de excelencia en el sector aeroespacial, entre los que se encuentran las empresas, las universidades y los centros tecnológicos.
Creación de un espacio común que centralice y potencie la generación y el acceso a conocimiento experto del sector aeroespacial en Galicia.
Estudio y definición de las tendencias nacionales e internacionales en materia aeroespacial para su aprovechamiento por el sector.
Realización de eventos y actos de difusión de los resultados de los estudios realizados.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
