### ISSUE TITLE
Observatorio da Eólica Mariña de Galicia

### ISSUE THREAD

**Issue by resinor** [JaimeObregon/observatoriospublicos.es#163]
### Nombre del observatorio (OBLIGATORIO)

Observatorio da Eólica Mariña de Galicia

### Sitio web

https://www.inega.gal/es/inega/puntos-de-encuentro-energeticos/observatorios

### Organismos públicos de los que depende

Xunta de Galicia

### Ámbito territorial

autonómico

### Tipo

publico

### Organismos que lo componen

Para una adecuada coordinación entre los diferentes agentes, el pleno del Observatorio está compuesto por la Administración Autonómica (con representantes de la Consellería de Economía, Empresa e Innovación, de la Consellería do Mar y de la Consellería de Medio Ambiente, Territorio y Vivenda de la Xunta de Galicia), por el sector pesquero (con representantes de la Cofradías de Pescadores y Consello Galego de Pesca) y por el sector industrial (con representantes de la Asociación de Industrias del Metal y Tecnologías Asociadas de Galicia - ASIME).

El Instituto Enerxético de Galicia coordina la secretaría técnica del Observatorio.

### Descripción

El principal objetivo del Observatorio de la Eólica Marina de Galicia es el de servir de foro de diálogo, encuentro y análisis para la búsqueda de la coexistencia y compatibilidad del potencial desarrollo de la eólica marina en Galicia con todas las actividades existentes, con especial atención a las actividades marítimo-pesqueras.

Generando conocimiento en relación con esta tecnología, identificando oportunidades de desarrollo de actividades industriales relacionadas con ella e identificando necesidades de elaboración de estudios de interés, siempre con la premisa del respeto por todas las actividades que se desarrollan en el mar.

Y, entre sus funciones estará la de:

- Promover foros técnicos de conocimiento para el análisis de las compatibilidades y de los usos del espacio marítimo.
- Crear un espacio de información entre las administraciones públicas y los sectores económicos sobre cuestiones reglamentarias, normativas o de planificación, tanto del espacio marítimo como de infraestructuras.
- Y la elaboración de estudios sobre oportunidades, impacto y potencial industrial en Galicia.

### En activo

Sí

**Comment by manucaballero** [comment]
Observatorio que ya ha sido añadido a la lista previamente.

**Comment by JaimeObregon** [comment]
Añadido. Quitado el duplicado.
