### ISSUE TITLE
Observatorio Galego da Biomasa

### ISSUE THREAD

**Issue by resinor** [JaimeObregon/observatoriospublicos.es#164]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Galego da Biomasa

### Sitio web

http://www.observatoriobiomasa.gal/

### Ámbito territorial

autonómico

### Tipo

publico

### Descripción

El principal objetivo del Observatorio Galego da Biomasa es el de proporcionar información relacionada con el sector que facilite su conocimiento, potencial, alternativas de aplicación, principales indicadores de impacto y difusión de casos de éxito.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
