### ISSUE TITLE
Observatorio do Comercio de Galicia

### ISSUE THREAD

**Issue by resinor** [JaimeObregon/observatoriospublicos.es#165]
### Nombre del observatorio (OBLIGATORIO)

Observatorio do Comercio de Galicia

### Sitio web

No

### Organismos públicos de los que depende

Adscrito a la dirección xeral competente en materia de comercio de la Xunta de Galicia

### Ámbito territorial

autonómico

### Tipo

publico

### Descripción

La Lei 13/2010, de 17 de diciembre, del comercio interior de Galicia, establece la creación del Observatorio del Comercio de Galicia, como un órgano asesor, consultivo, de estudio y formación en materia de comercio, adscrito a la dirección xeral competente en materia de comercio, cuya organización y funcionamento se establecerán reglamentariamente, que tiene atribuídas las siguientes funciones:

 1. Producir y gestionar los conocimientos propios en materia de comercio a través del análisis de la información recibida, de la elaboración de informes y estudios propios e además del diseño de instrumentos de observación sectorial y espacial de la Comunidad Autónoma de Galicia.

2. Elaborar planes estratégicos para la modernización, la dinamización y el fortalecimiento comercial gallego.

3. Gestionar el depósito de conocimientos en materia de comercio, recompilando la información generada por otras instancias públicas o privadas, mediante la adecuada organización de los dispositivos de conexión e seguimiento de estas.

4. Difundir y divulgar el conocimiento en materia de comercio a través de actividades formativas programadas, como cursos, seminarios, mesas redondas e demás iniciativas análogas, así como de la elaboración y la difusión de publicaciones, tanto en soporte  papel coma electrónicas.

5. Promover la participación de la sociedad en la mejora y desarrollo de la actividad comercial en Galicia.

### Fecha de inicio

17/12/2010

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
