### ISSUE TITLE
Observatorio do Solo Empresarial de Galicia

### ISSUE THREAD

**Issue by resinor** [JaimeObregon/observatoriospublicos.es#166]
### Nombre del observatorio (OBLIGATORIO)

Observatorio do Solo Empresarial de Galicia

### Sitio web

https://www.observatoriodosoloempresarial.gal

### Organismos públicos de los que depende

Instituto Galego da vivenda e solo

### Ámbito territorial

autonómico

### Tipo

publico

### Organismos que lo componen

Al lado de la Xunta de Galicia, participan en este portal web del Observatorio promotores, inversores patrimoniales, entidades gestoras de áreas empresariales, asociaciones y clústeres  empresariales, así como profesionales de la arquitectura o personal técnico de planificación urbanística y, en general, todas las administraciones (ayuntamientos y diputaciones), colegios y asociaciones vinculados de alguna manera al suelo empresarial.

### Descripción

Hace falta tener en cuenta que el desarrollo del suelo empresarial facilita la implantación de empresas en la comunidad, así como la mejora de las condiciones de las ya existentes, a través de su instalación en espacios especialmente diseñados para ellas, dotados de todos los servicios y las infraestructuras que les pueden resultar de utilidad y adaptados a los estándares de calidad que demandan. La ordenación del territorio incidirá, pues, en el asentamiento de empresas y en la mejora de su situación, lo que ayudará al desarrollo del tejido productivo y redundará en la creación de empleo y el crecimiento económico de Galicia.

Mediante el Observatorio se busca, pues, suministrar información de todos los aspectos relativos al suelo empresarial, con el objetivo de que administraciones, empresas públicas y privadas, y cualquier persona interesada en este ámbito se encuentren en las condiciones idóneas para adoptar decisiones eficaces y adaptadas a las necesidades del país.

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
