### ISSUE TITLE
OBSERVATORIO DE LA VIVIENDA Y EL SUELO

### ISSUE THREAD

**Issue by jrcosio** [JaimeObregon/observatoriospublicos.es#167]
### Nombre del observatorio (OBLIGATORIO)

OBSERVATORIO DE LA VIVIENDA Y EL SUELO DE CANTABRIA

### Sitio web

https://www.observatoriovivienda.cantabria.es/

### Correo electrónico

bobsvivi@cantabria.es

### Organismos públicos de los que depende

Dirección General de Vivienda

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

https://www.observatoriovivienda.cantabria.es/informes-de-instituciones-observatorio

### Organismos que lo componen

Presidente:

Consejera de Empleo y Políticas Sociales
Vicepresidente:

Directora General de Vivienda 
Vocales:

Dos representantes de la Dirección General de vivienda
Un representante de las entidades financieras
Dos representantes de la CEOE-CEPYME Cantabria
Un representante de la Federación de Municipios de la Comunidad Autónoma de Cantabria
Un representante de cada uno de los dos sindicatos mayoritarios
Un representante de la Dirección General de Urbanismo y  Ordenación del Territorio

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido con el número 132.
