### ISSUE TITLE
Observatorio da Vivenda de Galicia

### ISSUE THREAD

**Issue by resinor** [JaimeObregon/observatoriospublicos.es#168]
### Nombre del observatorio (OBLIGATORIO)

Observatorio da Vivenda de Galicia

### Sitio web

https://www.observatoriodavivenda.gal

### Correo electrónico

https://www.observatoriodavivenda.gal/gl/contact

### Organismos públicos de los que depende

Instituto Galego da Vivenda e solo

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

[Zonas tensionadas por municipios 2023](https://www.observatoriodavivenda.gal/gl/documentos/zonas-tensionadas-por-concellos-2023)

[La vivienda vacía en Galicia 2023](https://www.observatoriodavivenda.gal/gl/documentos/vivenda-baleira-en-galicia-2023)

[Ocupaciones de viviendas en Galicia 2023](https://www.observatoriodavivenda.gal/gl/documentos/ocupacions-de-vivendas-en-galicia-2023)

[Pacto de Vivienda de Galicia 2021-2025. Seguimiento 2022.](https://www.observatoriodavivenda.gal/gl/documentos/pacto-de-vivenda-de-galicia-2021-2025-seguimiento-2022)

[Pacto de vivienda de Galicia 2021-2025. Presentación del seguimiento 2021-2022](http://www.observatoriodavivenda.gal/gl/documentos/pacto-de-vivenda-de-galicia-2021-2025-0)

[La población de Galicia según el Censo de población 2021](https://www.observatoriodavivenda.gal/gl/documentos/censo-de-poboacion-2021)

[Vivienda y emancipación de la juventud en Galicia. 2020](https://www.observatoriodavivenda.gal/gl/documentos/vivenda-e-emancipacion-da-mocidade-en-galicia-2020)

[Estadística del alquiler segundo las fianzas en el año 2019. 2020](https://www.observatoriodavivenda.gal/gl/documentos/estatistica-do-alugueiro-segundo-fianzas-no-ano-2019-2020)

### Organismos que lo componen

Esta web es la cara pública de un organismo en el que, del lado de la Xunta de Galicia, participan los ayuntamientos gallegos a través de la Fegamp, las empresas promotoras, inmobiliarias y constructoras, los colegios profesionales de arquitectos, ingenieros y arquitectos técnicos, asociaciones del ámbito profesional y también las dedicadas al trabajo social, sindicatos y, en general, todas aquellas administraciones, colegios y asociaciones relacionados de una u otro manera con el ámbito de la vivienda.

### Descripción

A través del Observatorio pretendemos facilitar el acceso a la información y al conocimiento de todos los aspectos relacionados con el mundo de la vivienda, de manera que administraciones, empresas públicas y personales y cualquier interesado en este mundo estén en las mejores condiciones para adoptar decisiones eficaces y adaptadas a las necesidades del país.

Del trabajo de unos y otros saldrá la información, estudios y trabajos que periódicamente verano a luz a través de esta web y de los boletines y publicaciones del Observatorio que estarán la disposición de los interesados en las diferentes secciones de este sitio.

### En activo

None

**Comment by JaimeObregon** [comment]
Incorporado :)
