### ISSUE TITLE
Observatorio Andaluz de la Publicidad no sexista

### ISSUE THREAD

**Issue by alexcadiz** [JaimeObregon/observatoriospublicos.es#169]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Andaluz de la Publicidad no sexista

### Sitio web

https://www.juntadeandalucia.es/institutodelamujer/index.php/observatorio-andaluz-de-publicidad-no-sexista

### Organismos públicos de los que depende

Junta de Andalucía

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

["Estereotipos sexistas en la publicidad de juguetes: situación y evolución". Análisis de las campañas de Navidad 2020-2023. AUC (PDF)](https://www.consumo.gob.es/sites/consumo.gob.es/files/consumo_masinfo/informe_juguetes.pdf)
["Código de autorregulación de la publicidad infantil de juguetes" (PDF)](https://www.juntadeandalucia.es/institutodelamujer/images/FONDO_DOCUMENTAL/OBSERVATORIO_ANDALUZ_DE_LA_PUBLICIDAD/Codigo%20Autorregulacion%20Publicidad%20Infantil%20Juguetes.pdf)
["El Libro Blanco de la Influencia Responsable". iCmedia (PDF)](https://www.influencerstrustlabeleu.org/wp-content/uploads/2021/11/El-Libro-blanco-de-la-Influencia-Responsable-ISEM-ICMEDIA-NEWLINK_AAFF.pdf)
["Manual de tratamiento periodístico del deporte femenino y las mujeres deportistas". (PDF)](https://teika.es/manual-deporte-femenino/)
["Manual para un lenguaje administrativo no sexista". IAM (PDF)](https://www.juntadeandalucia.es/institutodelamujer/ugen/sites/default/files/documentos/107.pdf)
["Un lenguaje neutral en cuanto al género". Parlamento Europeo (PDF)](https://www.europarl.europa.eu/cmsdata/187095/GNL_Guidelines_ES-original.pdf)
["Lectura fácil y lenguaje no sexista". Plena Inclusión (PDF)](https://www.plenainclusion.org/sites/default/files/lectura_facil_y_lenguaje_no_sexista.pdf)
["Mujeres sin nombre. Presencia de la mujer en los medios de comunicación. 2023" (PDF)](https://resources.llorenteycuenca.com/es/mujeres-sin-nombre.-avances-en-la-presencia-de-la-mujer-en-medios-de-comunicaci%C3%B3n-y-el-desaf%C3%ADo-pendiente?hsCtaTracking=819f4941-2325-4c55-ab58-f44fe09fde65%7Cf3526b6e-e240-41a7-9190-c1b1f939beba)
["La violencia digital de género: Una realidad invisible". Observatorio Nacional de la Tecnología y Sociedad. Políticas públicas contra la violencia de género 2022 (PDF)](https://www.ontsi.es/sites/ontsi/files/2022-04/violenciadigitalgenerounarealidadinvisible_2022.pdf)
["Manual Práctico Comunicación e Imagen con Perspectiva de Género 2022" (PDF)](https://www.juntadeandalucia.es/export/drupaljda/M20.PDF)
["Cuaderno Nº13 La salud de las mujeres en los medios, la publicidad y las redes sociales". IAM (PDF)](https://www.juntadeandalucia.es/iam/catalogo/doc/iam/2022/143682315.pdf)
["Libertad para jugar. Guía para la elección de juguetes sin estereotipos sexistas". Ministerio de Consumo (PDF)](https://www.consumo.gob.es/es/system/tdf/prensa/Guia_juguetes_sin_estereotipos_sexistas.pdf?file=1&type=node&id=1181&force=)
["Guía de buenas prácticas para impulsar la igualdad de la mujer en los medios audiovisuales y el adecuado tratamiento de la violencia de género”. Consejo Audiovisual de Andalucía y Plataforma de Reguladores del Sector Audiovisual de Iberoamérica (PDF)](https://consejoaudiovisualdeandalucia.es/2022/03/08/guia-de-buenas-practicas-por-la-igualdad-y-contra-la-violencia-de-genero/)
["Violencia contra las mujeres y medios de comunicación”. Edición Ministerio de Igualdad](https://violenciagenero.igualdad.gob.es/violenciaEnCifras/estudios/investigaciones/2021/estudios/Violencias_machistas__medios_comunicacion.htm)
["Hola, tú a mí no me conoces". Diccionario visual sobre las mujeres del siglo XXI. Instituto de las Mujeres. Club de Creativos/as](https://www.inmujeres.gob.es/areasTematicas/comunicacion/programas/docs/TU_A_MI_NO_ME_CONOCES.pdf)

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido. Los informes referidos no parecen publicados por este observatorio, sino recopilados de otras fuentes.
