### ISSUE TITLE
Observatorios de A Coruña

### ISSUE THREAD

**Issue by nuno-andre** [JaimeObregon/observatoriospublicos.es#17]
Añado tres observatorios del Concello de A Coruña. 

- Observatorio Urbano de A Coruña
  - parent: Concello de A Coruña
  - website: https://www.coruna.gal/encifras/es/observatorios-municipales/observatorio-urbano-de-a-coruna

- Observatorio municipal de igualdade e diversidade
  - parent: Concello de A Coruña
  - website: https://www.coruna.gal/igualdade/es/servicios/observatorio

- Observatorio turístico de A Coruña
  - parent: Concello de A Coruña, Universidade da Coruña
  - website: https://acorunaot.udc.es/

Haría un PR, pero entiendo que querrás modificar `scopes` antes de que se vaya de madre 🙃

Quizás sería más práctico un `scopes` del tipo `{'estatal', 'autonómico', 'provincial', 'local'}` y añadir un campo `location` al objeto.

**Comment by vgpastor** [comment]
+1 a los scopes, creo que tienen más sentido

**Comment by JaimeObregon** [comment]
¡Añadido! Sí: lo de los `scopes` ahora no está bien. Lo cambio en breve. Todo el código es de momento una guarrada. Iremos haciendo limpieza :)
