### ISSUE TITLE
Observatorio de precios de la Comunitat Valenciana

### ISSUE THREAD

**Issue by ajut400** [JaimeObregon/observatoriospublicos.es#170]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de precios de la Comunitat Valenciana

### Sitio web

https://argos.gva.es/es/web/prospectiva/observatori

### Organismos públicos de los que depende

Consellería de Economía Sostenible, Sectores Productivos, Comercio y Trabajo de la Comunitat Valenciana

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

[11_noviembre_23.pdf](https://github.com/JaimeObregon/observatoriospublicos.es/files/14648255/11_noviembre_23.pdf)

### Descripción

Crear un observatorio de precios, de la mano de la Oficina del Consumidor, que permita identificar posibles subidas injustificadas
de precios de venta al público.

### Fecha de inicio

Abril de 2022

### En activo

Sí

**Comment by ajut400** [comment]
Hola, el observatorio de precios de la Comunidad valenciana, está triplicadoooooo. Ni idea de cómo hacer limpieza... ToDoList !!!

https://argos.gva.es/es/web/prospectiva/observatori

**Comment by manucaballero** [comment]
Buenas @ajut400 , el último informe del observatorio es de noviembre de 2023. ¿Sigue en activo?

**Comment by JaimeObregon** [comment]
¡Añadido y quitados los duplicados! :)
