### ISSUE TITLE
Observatorio Municipal Galego

### ISSUE THREAD

**Issue by resinor** [JaimeObregon/observatoriospublicos.es#171]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Municipal Galego

### Sitio web

http://www.observatorioredlocalis.com/

### Correo electrónico

 infogen@uvigo.es

### Organismos públicos de los que depende

Universidade de Vigo

### Ámbito territorial

autonómico

### Tipo

publico

### Organismos que lo componen

[Grupo GEN](http://infogen.webs.uvigo.es/)
[Federación Galega de Municipios e Provincias (FEGAMP)](http://www.fegamp.gal/)
[Xunta de Galicia](http://www.xunta.gal/)

### Descripción

A Red Localis, xestionada polo grupo de investigación GEN da Universidade de Vigo, desenvolve o primeiro Observatorio Municipal Galego, que recolle e difunde información relacionada coa economía e fiscalidade local dos 313 concellos.

Un dos eixos deste proxecto é dispoñer dunha web para que a cidadanía coñeza a realidade das actuacións en materia de gasto e ingresos dos municipios galegos. Para iso, disponse dunha páxina web interactiva donde se pode consultar, entre outra, información orzamentaria e tributaria.

No observatorio pódese consultar en qué se gasta, canto se gasta, para qué se gasta ou canto se ingresa e as principais partidas de ingresos a nivel municipal. Ademáis, resulta posible facer comparacións por tamaño municipal ou a nivel provincial.
Información básica do área xeográfica

Neste apartado disponse de información económica e demográfica sobre cada un dos concellos.

Entre outra, hai datos sobre a poboación, superficie, dispersión poboacional, número de entidades de pobación, produto interior bruto por habitante, renta dispoñible bruta por habitante e desemprego.
Liquidación Orzamentos Ingresos/Gastos

Neste apartado figura información sobre as liquidacións dos orzamentos de ingresos (por capítulos) e de gastos (por capítulos e áreas) para coñecer as principais partidas para cada concello
Recaudación de impostos

Neste apartado disponse de información sobre os diferentes impostos locais para cada concello:

Imposto sobre Bens Inmobles, Imposto sobre Actividades Económicas, Imposto sobre Vehiculos de Tracción Mecánica, Imposto sobre o Incremento do Valor dos Terreos de Natureza Urbana (Plusvalía muncipal) e o Imposto sobre Instalacións, Construccións e Obras.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
