### ISSUE TITLE
Observatorio Aragonés de la Juventud

### ISSUE THREAD

**Issue by dmbuil** [JaimeObregon/observatoriospublicos.es#172]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Aragonés de la Juventud

### Sitio web

https://www.aragon.es/-/presentacion-1#anchor1

### Organismos públicos de los que depende

 - Instituto Aragonés de la Juventud

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

- https://www.aragon.es/documents/20127/2555757/Informe-IAJ-paginas-sinlogos.pdf/d0078bfc-5a3e-b099-1b2b-fd9fd16230d9?t=1624345162241
- https://www.aragon.es/documents/20127/2555757/estudio+poblaci%C3%B3n+joven+2017.pdf/6737909d-73a0-2108-54ed-f61681b78672?t=1564133166888
- https://www.aragon.es/documents/20127/2555757/estudio+poblacion+joven+2015.pdf/5b72de7a-57c9-4466-f583-df71f91ab852?t=1564133102597
- https://www.aragon.es/documents/20127/2555757/estudio+poblacion+joven+2013.pdf/50359e1c-6c93-d649-369e-2eef4c0f2e7c?t=1564132952115
- https://www.aragon.es/documents/20127/2555757/informe+sobre+las+actividades+juveniles+2018.pdf/56765c1f-76ab-cc90-f35d-446dc4089cca?t=1564133341013
- https://www.aragon.es/documents/20127/2555757/Informe+final+%2B+anexo_nuevo+%281%29.pdf/263d9298-49c2-d118-464c-1be388dcff6b?t=1592307413095
- https://www.aragon.es/documents/20127/2555757/estuido+vivienda+joven+teruel.pdf/729d9573-f3e7-8836-4ab1-df674df4dd5b?t=1564133522455
- https://www.aragon.es/documents/20127/2555757/estudio+violencia+en+el+lenguaje.pdf/ffb47bb0-7e97-be8c-4bd8-8bfcc8214c72?t=1564133700506

### Descripción

El Instituto Aragonés de la Juventud crea el Observatorio Aragonés de la Juventud partiendo de la necesidad de obtener una información detallada de la juventud aragonesa con el objeto de obtener una imagen fidedigna que permita detectar necesidades y orientar las áreas prioritarias de actuación.
A través del Observatorio se establecerá una información precisa sobre la situación de la juventud en Aragón, lo que nos permitirá diseñar propuestas, servicios y actuaciones a favor de los jóvenes.

### Fecha de inicio

25 de marzo de 2015

### En activo

Sí

**Comment by JaimeObregon** [comment]
¡Añadido!
