### ISSUE TITLE
Observatorio de la I+D+i de Canarias

### ISSUE THREAD

**Issue by adandavilam** [JaimeObregon/observatoriospublicos.es#175]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la I+D+i de Canarias

### Sitio web

https://www.obidic.es/

### Organismos públicos de los que depende

Gobierno de Canarias

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
