### ISSUE TITLE
OECAN

### ISSUE THREAD

**Issue by adandavilam** [JaimeObregon/observatoriospublicos.es#176]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Energia de Canarias

### Sitio web

https://www3.gobiernodecanarias.org/ceic/energia/oecan/

### Organismos públicos de los que depende

Gobierno de Canarias

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
