### ISSUE TITLE
OCSALUD

### ISSUE THREAD

**Issue by adandavilam** [JaimeObregon/observatoriospublicos.es#177]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Canario de la Salud

### Sitio web

https://www3.gobiernodecanarias.org/sanidad/scs/contenidoGenerico.jsp?idDocument=ba5d4671-60dc-11ed-9e04-cd68079ec7ca&idCarpeta=61e907e3-d473-11e9-9a19-e5198e027117

### Organismos públicos de los que depende

Gobierno de Canarias

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
