### ISSUE TITLE
Implementar nuevos observatorios masivamente

### ISSUE THREAD

**Issue by tintintino** [JaimeObregon/observatoriospublicos.es#179]
Valdría la pena implementar un scrap de la web de issues para extraer y poder volcar masivamente todas las solicitudes de observatorios?
O no se si se puede acceder de otra forma más sencilla con una API.

**Comment by JaimeObregon** [comment]
Hacer _scraping_ no lo veo, porque hay que hacer un poco de revisión manual. Comprobar, por ejemplo, que se trata de un observatorio público o público privado. Para que no se cuelen observatorios privados, que alguno ha llegado. También hago una revisión general y trato de completar campos que faltan…

La verdad es que está siendo bastante caótico porque lancé el proyecto sin definir antes un mecanismo eficaz de entrada de datos. No pensé que fuera a haber tantas contribuciones :)

De todas formas, dejo esto abierto porque no descarto el _scraping_. Lo que sí me parece excesivo es implementar una API, pues eso significaría desplegar y mantener una base de datos… Prefiero que el proyecto sea completamente estático, como ahora, que es mucho más sencillo de mantener y administrar.

**Comment by JaimeObregon** [comment]
También trato de revisar que no haya duplicados.

**Comment by JaimeObregon** [comment]
Esto ya está resuelto. Lo cierro.
