### ISSUE TITLE
Observatorio Turístico de Canarias

### ISSUE THREAD

**Issue by adandavilam** [JaimeObregon/observatoriospublicos.es#180]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Turístico de Canarias

### Sitio web

https://www.gobiernodecanarias.org/turismo/estadisticas_y_estudios/

### Organismos públicos de los que depende

Gobierno de Canarias

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido :)
