### ISSUE TITLE
OCTSI

### ISSUE THREAD

**Issue by adandavilam** [JaimeObregon/observatoriospublicos.es#181]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Canario de las Telecomunicaciones y de la Sociedad de la Información

### Sitio web

https://www.octsi.es/

### Organismos públicos de los que depende

Gobierno de Canarias

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
¡Incorporado! :) Gracias.
