### ISSUE TITLE
OIC

### ISSUE THREAD

**Issue by adandavilam** [JaimeObregon/observatoriospublicos.es#182]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Industrial de Canarias

### Sitio web

https://oic.itccanarias.org/

### Organismos públicos de los que depende

Gobierno de Canarias

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
¡Dentro! :D
