### ISSUE TITLE
Observatorio Canario de la Juventud

### ISSUE THREAD

**Issue by adandavilam** [JaimeObregon/observatoriospublicos.es#185]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Canario de la Juventud

### Sitio web

https://www.gobiernodecanarias.org/juventud/programas/observatorio-canario-de-la-juventud/

### Organismos públicos de los que depende

Gobierno de Canarias

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido :)
