### ISSUE TITLE
Observatorio Canario del Cambio Climático

### ISSUE THREAD

**Issue by adandavilam** [JaimeObregon/observatoriospublicos.es#186]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Canario del Cambio Climático

### Sitio web

https://www.gobiernodecanarias.org/medioambiente/organos/observatorio-canario-del-cambio-climatico/

### Organismos públicos de los que depende

Gobierno de Canarias

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido :)
