### ISSUE TITLE
OCEA

### ISSUE THREAD

**Issue by adandavilam** [JaimeObregon/observatoriospublicos.es#187]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Canario de la Economía Azul

### Sitio web

https://www.gobiernodecanarias.org/economia/ocea/

### Organismos públicos de los que depende

Gobierno de Canarias

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido :)
