### ISSUE TITLE
Observatorio de Emancipación CJE

### ISSUE THREAD

**Issue by davidsoler95** [JaimeObregon/observatoriospublicos.es#190]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Emancipación CJE

### Sitio web

https://www.cje.org/observatorio-de-emancipacion/

### Organismos públicos de los que depende

Consejo de la Juventud de España

### Ámbito territorial

estatal

### Tipo

mixto

### Informes publicados

Observatorio de Emancipación del Consejo de la Juventud de España - Estatal

### Organismos que lo componen

Consejo de la Juventud de España

### Descripción

Seguimiento periódico y exhaustivo de algunos elementos objetivables relacionados con el empleo y la vivienda que definen las condiciones de vida y los procesos de transición hacia la vida adulta de la población joven en España.

### Fecha de inicio

Septiembre de 2013

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido :)
