### ISSUE TITLE
Observatorio de márgenes empresariales

### ISSUE THREAD

**Issue by rubparsa** [JaimeObregon/observatoriospublicos.es#191]
**Duplicado** - [Primera aparición](https://github.com/JaimeObregon/observatoriospublicos.es/issues/50)

### Nombre del observatorio (OBLIGATORIO)

Observatorio de márgenes empresariales

### Sitio web

https://www.bde.es/wbe/es/inicio/observatorio-margenes-empresariales/

### Organismos públicos de los que depende

[Agencia Estatal de Administración Tributaria (AEAT) / Ministerio de Hacienda](https://datos.gob.es/es/catalogo/ea0028512-observatorio-de-margenes-empresariales)

### Ámbito territorial

estatal

### Tipo

publico

### Informes publicados

- [Objetivo del Observatorio y primer informe trimestral (Julio 2023)](https://www.bde.es/f/webbe/INF/MenuHorizontal/Observatorio_margenes_empresariales/20230703_OME_Briefing.pdf)
- [Informe Trimestral 2023 T3](https://www.bde.es/f/webbe/INF/MenuHorizontal/Observatorio_margenes_empresariales/20231218_OME_T3.pdf)

### Organismos que lo componen

- [Ministerio de Asuntos Económicos y Transformación Digital (MINECO)](https://portal.mineco.gob.es/es-es/comunicacion/Paginas/observatorio-de-m%C3%A1rgenes.aspx)
- [Banco de España (BdE)](https://www.bde.es/wbe/es/inicio/observatorio-margenes-empresariales/)
- [Agencia Estatal de Administración Tributaria (AEAT)](https://sede.agenciatributaria.gob.es/Sede/estadisticas/observatorio-margenes-empresariales/observatorio-margenes-empresariales.html)

### Descripción

El Observatorio de márgenes empresariales es un proyecto conjunto del Ministerio de Asuntos Económicos y Transformación Digital, el Banco de España y la Agencia Tributaria que tiene como objetivo disponer de información para el seguimiento y el análisis de los márgenes empresariales y de mejorar el conocimiento sobre su evolución y sus implicaciones para el conjunto de la economía.

En esta web se ofrecen varias bases de datos, anuales y trimestrales, procedentes del Impuesto sobre Sociedades y de los modelos de IVA y retenciones sobre rendimientos del trabajo. En el caso del Impuesto sobre Sociedades, se proporciona una selección de variables de la Cuenta de Pérdidas y Ganancias. De las declaraciones del IVA y de retenciones sobre rendimientos del trabajo se facilitan cifras de ventas totales (interiores, exportaciones) y compras totales (interiores, importaciones), en el primer caso, y de masa salarial y perceptores de salarios, en el segundo.

La población objeto de estudio en cada año son todas aquellas empresas no financieras que tengan declaraciones del Impuesto sobre Sociedades, del IVA y de retenciones por rendimientos del trabajo. Tan solo se excluyen algunas actividades con un alto porcentaje de operaciones exentas a efectos del IVA. Las actividades se clasifican a dos dígitos de la CNAE, excepto en el comercio mayorista y minorista (tres dígitos y en algún caso a cuatro) y algunas agrupaciones especiales.

### Fecha de inicio

3 de julio de 2023

### En activo

Sí

**Comment by adaig** [comment]
great!
