### ISSUE TITLE
Observatorio Navarro de la Cultura

### ISSUE THREAD

**Issue by afermar** [JaimeObregon/observatoriospublicos.es#192]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Navarro de la Cultura

### Sitio web

https://www.culturanavarra.es/es/presentacion-8

### Organismos públicos de los que depende

Dirección General de Cultura - Institución Príncipe de Viana

### Ámbito territorial

autonómico

### Tipo

publico

### Descripción

Profundizar en el conocimiento sobre los sectores culturales y creativos, y sistematizar la información cuantitativa y cualitativa en el ámbito de la cultura y la creatividad en Navarra que:

- ayude en la elaboración de las políticas culturales y la toma de decisiones,
- investigue en tendencias, conexiones con otros sectores, etc.,
- identifique las buenas prácticas y experiencias que se desarrollan dentro y fuera de Navarra, y
- fomente el conocimiento de los públicos de la cultura y la creatividad.

### En activo

Sí

**Comment by carloshm** [comment]
great
