### ISSUE TITLE
Observatorio estatal de la dependencia

### ISSUE THREAD

**Issue by jczamor** [JaimeObregon/observatoriospublicos.es#199]
### Nombre del observatorio (OBLIGATORIO)

Observatorio estatal de la dependencia 

### Sitio web

fedea.net

### Correo electrónico

info@fedea.es

### Ámbito territorial

estatal

### Tipo

publico

### Fecha de inicio

2007

### En activo

Sí

**Comment by jczamor** [comment]
La actividad de Fedea tiene tres facetas fundamentales: investigación, divulgación e influencia sobre el diseño de las políticas públicas.

Aunque Fedea no es un centro de investigación académica pura, la investigación de relevancia social es la base sobre la que se sustenta la institución. Nuestro principal objetivo es el de extraer de la investigación académica lecciones de utilidad práctica para el diseño de buenas políticas económicas y sociales

**Comment by JaimeObregon** [comment]
Este no le añadimos, pues FEDEA parece de una entidad privada.

**Comment by jczamor** [comment]
Ok, eso me parecía ..........pero tengo más..😅

Juan Carlos Zamora
agente comercial - distribuidor
t. 687 468 246
