### ISSUE TITLE
Dipsalut

### ISSUE THREAD

**Issue by oscar-genomcore** [JaimeObregon/observatoriospublicos.es#201]
### Nombre del observatorio (OBLIGATORIO)

L'Observatori Social, Ambiental i de Salut De la Diputació de Girona

### Sitio web

https://observatori.dipsalut.cat/es

### Organismos públicos de los que depende

Dioutación de Girona

### Ámbito territorial

provincial

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido :)
