### ISSUE TITLE
Observatorio de Servicios Sociales de Araba

### ISSUE THREAD

**Issue by NussAl** [JaimeObregon/observatoriospublicos.es#207]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Servicios Sociales de Araba

### Sitio web

https://www.dataraba.eus/

### Organismos públicos de los que depende

Instituto Foral de Bienestar Social (IFBS) de la Diputación Foral de Álava

### Ámbito territorial

provincial

### Tipo

publico

### Informes publicados

Valoraciones de dependencia. Álava 2022 [PDF]
Plazas en servicios residenciales y de atención diurna. Álava 2022 [PDF]
Personas usuarias de servicios sociales. Álava 2022 [PDF]
Gasto público en servicios y prestaciones sociales. Álava 2020 [PDF]

### Descripción

El Observatorio Social de Álava se crea precisamente como una herramienta de información complementaria sobre la actividad de los Servicios Sociales en el Territorio Histórico. A través de esta web, la Diputación Foral de Álava pretende poner a disposición de los técnicos que trabajan en el área de Bienestar Social y de la ciudadanía en general un núcleo de datos estadísticos que permitan:

Conocer las principales magnitudes de la red alavesa de Servicios Sociales.
Realizar comparaciones entre diferentes cuadrillas y/o municipios.
Valorar la adecuación de los recursos disponibles a las necesidades presentes en el Territorio Histórico.
Evaluar la adecuación de los servicios en referencia a una serie de estándares de buena práctica.
Realizar un seguimiento de la evolución de los Servicios Sociales en el Territorio Histórico.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
