### ISSUE TITLE
Observatorio de residuos

### ISSUE THREAD

**Issue by NussAl** [JaimeObregon/observatoriospublicos.es#208]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de residuos

### Sitio web

https://web.araba.eus/es/medio-ambiente/residuos/observatorio-de-residuos

### Organismos públicos de los que depende

Diputación Foral de Álava / Arabako Foru Aldundia

### Ámbito territorial

provincial

### Tipo

publico

### Informes publicados

Inventario de residuos domésticos 2022

Resumen ejecutivo 2022

### Descripción

El Observatorio de Residuos Urbanos es un instrumento identificado como acción número 15 del vigente Plan de prevención y gestión de residuos urbanos de Araba-Álava, 2017-2030, abreviadamente PRU2030.

Es un instrumento de información, conocimiento y seguimiento permanente de aspectos relativos a la gestión de los residuos urbanos así como un punto de encuentro de todos los agentes interesados, favoreciendo la difusión de información técnica y académica sobre esta materia.

Para este fin actúa como figura integradora de referencia de elementos como el Inventario anual de residuos, Caracterizaciones y Seguimiento y evaluación del plan de residuos, PRU2030.

### Fecha de inicio

2015

### En activo

Sí

**Comment by JaimeObregon** [comment]
¡Añadido!
