### ISSUE TITLE
Propuesta para añadir "Inicio de actividad", "Cese de actividad" y "Activo"

### ISSUE THREAD

**Issue by jccabrejas** [JaimeObregon/observatoriospublicos.es#21]
Muchos de estos observatorios fueron flor de un día y ahora solo quedan notas de prensa. Un ejemplo de 2013 es https://www.ayto-alcaladehenares.es/presentacion-del-observatorio-urbano-alcala-en-cifras/ 

propuesta. Si @JaimeObregon lo aprueba puedo hacer un PR

const observatories = [
  // {
  //   name: '', // Nombre del observatorio
...
  //   comment: '', //
  //   from_date: '', // Inicio de actividad. Fecha de creación o fecha del anuncio
  //   to_date: '', // Cese de actividad. Fecha de última actividad conocida
  //   is_active: '', // Sí, No,
  // },

**Comment by JaimeObregon** [comment]
¡A por ello, @jccabrejas! :D 👍. Haz un `pull` antes, porfa, que acabo de empujar cambios en la estructura de ficheros :)

**Comment by JaimeObregon** [comment]
:D
