### ISSUE TITLE
Observatorio de Convivencia

### ISSUE THREAD

**Issue by NussAl** [JaimeObregon/observatoriospublicos.es#210]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Convivencia

### Sitio web

https://www.vitoria-gasteiz.org/wb021/was/contenidoAction.do?idioma=es&uid=u50993cf2_1781a8edc14__7e4c

### Correo electrónico

bizikidetza.convivencia@vitoria-gasteiz.org

### Organismos públicos de los que depende

Ayuntamiento de Vitoria-Gasteiz

### Ámbito territorial

local

### Tipo

publico

### Informes publicados

Guía completa de recursos para la no discriminación (pdf)
Guía de buenas prácticas para la convivencia
Estudio Diagnóstico sobre la Diversidad Religiosa en Vitoria-Gasteiz
Estudio diagnóstico sobre la acogida lingüística en Vitoria-Gasteiz

### Descripción

El Observatorio de Convivencia es un conjunto de herramientas y mecanismos diversos y flexibles tanto para el análisis como para la búsqueda de respuestas a las necesidades de cohesión social de nuestra ciudad, que se adaptan a una realidad cada vez más diversa y cuya gestión resulta compleja.

Su creación es uno de los compromisos recogidos en el [Plan de Convivencia y Diversidad 2018-2020](https://www.vitoria-gasteiz.org/wb021/was/contenidoAction.do?idioma=es&uid=u12aa3e5_1576eff20cf__7e6c&idioma=es) y persigue dos objetivos:

Generar conocimiento actualizado y permanente sobre el estado de la convivencia y sobre recursos de denuncia e intervención en situaciones de discriminación en Vitoria-Gasteiz.
Diseñar y gestionar estrategias con carácter preventivo y restaurativo para garantizar la cohesión social.
¿Sobre qué pilares se asienta?
El Observatorio se erige sobre tres pilares o principios de actuación:

1. El enfoque de Derechos Humanos
La intervención desde este enfoque identifica a toda la ciudadanía como titular de derechos y procura fortalecer su capacidad para reivindicarlos. Asimismo, atribuye a las políticas públicas el deber de garantizarlos. La finalidad de este enfoque es alcanzar la paz positiva; es decir, una situación de justicia en la que las relaciones intergrupales son de tipo coo­perativo y pacífico y los derechos humanos se encuentran vigentes en su plenitud.

2. El paradigma de la interculturalidad
La interculturalidad es un modelo de acomodación de la diversidad que propugna la interacción positiva y el encuentro en condiciones de igualdad entre grupos de origen cultural e identitario diverso, a partir del reconocimiento mutuo de sus respectivos valores, saberes y formas de vida, a fin de generar expresiones culturales compartidas y nuevas.

3. La gestión positiva de la diversidad
La gestión positiva de la diversidad conlleva un proceso de deconstrucción de las conductas individuales y colectivas y de las estructuras de poder que mantienen la desigualdad y la discriminación. Su objetivo es generar un modelo de convivencia nuevo en el que la diversidad misma adquiera el estatus de cultura pública y cívica.

¿Cuáles son sus líneas de actuación?
El Observatorio desarrolla su actividad de acuerdo a cuatro líneas de actuación:

[Línea 1: Formación y sensibilización](https://www.vitoria-gasteiz.org/wb021/was/contenidoAction.do?idioma=es&uid=u50993cf2_1781a8edc14__7e49).

[Línea 2: Información sobre recursos existentes](https://www.vitoria-gasteiz.org/wb021/was/contenidoAction.do?idioma=es&uid=u50993cf2_1781a8edc14__7e47).

[Línea 3: Fomento de la cohesión social](https://www.vitoria-gasteiz.org/wb021/was/contenidoAction.do?idioma=es&uid=u50993cf2_1781a8edc14__7e48).

[Línea 4: Conocimiento sobre el estado de la convivencia](https://www.vitoria-gasteiz.org/wb021/was/contenidoAction.do?idioma=es&uid=u50993cf2_1781a8edc14__7e46).

### En activo

Sí

**Comment by JaimeObregon** [comment]
¡Incorporado! 🚀
