### ISSUE TITLE
L'Observatori del Sistema Penal i els Drets Humans

### ISSUE THREAD

**Issue by arodrrosa** [JaimeObregon/observatoriospublicos.es#211]
### Nombre del observatorio (OBLIGATORIO)

L'Observatori del Sistema Penal i els Drets Humans

### Sitio web

https://www.ub.edu/portal/web/observatori-sistema-penal

### Correo electrónico

observatori.ospdh@ub.edu

### Organismos públicos de los que depende

Universidad de Barcelona

### Ámbito territorial

estatal

### Tipo

publico

### Descripción

1. Observar, analizar e informar sobre el funcionamiento de las instituciones del sistema penal (prisiones, centros de detención, centros de internamiento de extranjeros, jueces, fuerzas de seguridad).
2. Contribuir a la defensa de los derechos humanos, cada vez más amenazados por las políticas de seguridad, vigilancia y control.
3. Velar por el cumplimiento de la estricta legalidad en el sistema penal y trabajar para promover su transparencia.
4. Dar herramientas para que las personas y organizaciones sociales desarrollen más poder y tengan los instrumentos necesarios en su lucha por los derechos y la libertad.

### Fecha de inicio

Mayo de 2001

### En activo

Sí

**Comment by manucaballero** [comment]
Observatorio que ya ha sido añadido a la lista previamente.

**Comment by JaimeObregon** [comment]
Efectivamente. Cierro.
