### ISSUE TITLE
Observatorio Galego da Familia e da Infancia

### ISSUE THREAD

**Issue by Jorganes** [JaimeObregon/observatoriospublicos.es#212]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Galego da Familia e da Infancia

### Sitio web

https://www.xunta.gal/dog/Publicados/2019/20190429/AnuncioG0425-150419-0001_gl.html

### Organismos públicos de los que depende

consellería competente en materia de familia

### Ámbito territorial

autonómico

### Tipo

publico

### Organismos que lo componen

 titular da consellería competente en materia de familia
 titular da dirección xeral competente en materia de familia
 funcionaria da consellería competente en materia de familia
 persoa en representación do órgano competente en materia de estatística
persoa en representación da Delegación do Goberno en Galicia
persoa en representación da Federación Galega de Municipios e Provincias (Fegamp)
persoa en representación de cada unha das tres universidades galegas
persoa representante da Fiscalía da Comunidade Autónoma de Galicia
Un número de persoas equivalente ao de representantes sindicais en representación da Confederación de Empresarios de Galicia (CEG)
persoa en representación de cada unha das organizacións sindicais intersectoriais máis representativas de Galicia, así como das presentes na Mesa Xeral de Negociación das Administracións Públicas que non teñan a condición de máis representativas
persoa representante da Plataforma de Organizacións da Infancia de Galicia (POI Galicia)
persoa en representación da Fundación UNICEF-Comité Español

### Descripción

1. Este observatorio, para a consecución dos seus fins, exercerá as seguintes funcións:

a) Actuar como órgano de recompilación, análise e intercambio da información dispoñible en diferentes fontes autonómicas, estatais e internacionais sobre a familia e os nenos, nenas e adolescentes.

b) Propoñer a realización de estudos, investigacións e informes técnicos que permitan un mellor coñecemento da situación da familia e da infancia en Galicia e a detección das súas necesidades e demandas sociais.

c) Avaliar o impacto das políticas fiscais, laborais e sociais desenvolvidas polos distintos departamentos das administracións na situación das familias e da infancia galegas.

d) Formular propostas e recomendacións sobre liñas estratéxicas e prioridades de actuación en materia de políticas familiares e de infancia no ámbito da Comunidade Autónoma Galega.

e) Servir de canle para a actuación coordinada e harmónica entre os distintos departamentos das administracións públicas no ámbito da familia e a infancia.

f) Canalizar as propostas das organizacións sociais que desenvolven as súas actividades no ámbito da familia e da infancia.

g) Promover as actuacións necesarias para sensibilizar a toda a cidadanía no coñecemento e respecto dos dereitos da infancia en Galicia e no mundo.

h) Promover a elaboración e desenvolvemento dos plans e estratexias de familia, de infancia e adolescencia e avaliar a súa execución.

i) Elaborar informes e ditames por petición dos órganos competentes da Comunidade Autónoma sobre as materias da súa competencia.

j) Impulsar a incorporación da perspectiva da familia e infancia no ordenamento xurídico galego, de xeito que se tomen en consideración as necesidades da infancia, da adolescencia e das familias galegas.

k) Participar, elevar propostas e manter contactos con outros órganos de similar natureza, promovendo os encontros entre profesionais e persoas expertas, tanto no ámbito autonómico e estatal como internacional, para facilitar o intercambio de experiencias, investigacións e traballos nesta materia.

2. No exercicio das funcións establecidas neste artigo terase en conta e integrarase de xeito transversal a perspectiva de xénero e a relación recíproca entre familia e infancia e igualdade de xénero.

### Fecha de inicio

29 de abril de 2019

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
