### ISSUE TITLE
O Observatorio Galego de Condicións de Traballo

### ISSUE THREAD

**Issue by Jorganes** [JaimeObregon/observatoriospublicos.es#215]
### Nombre del observatorio (OBLIGATORIO)

O Observatorio Galego de Condicións de Traballo

### Sitio web

https://issga.xunta.gal/gl/observatorio

### Organismos públicos de los que depende

INSTITUTO DE SEGURIDADE E SAÚDE LABORAL DE GALICIA - ISSGA

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

La siniestralidad laboral en Galicia en el año 2023
Las enfermedades profesionales en Galicia en el año 2023 
Siniestralidad laboral de los conductores profesionales_Galicia_2014 -2018
Siniestralidad laboral en los servicios de alojamiento y de comidas y bebidas_Galicia_2014 -2018
Análise da mortalidade por accidente de traballo en Galicia. 2005-2017 
Siniestralidad del personal trabajador por cuenta propia o autónomo. Años 2009-2016 

### Descripción

Procesar e difundir a información dispoñible sobre a sinistralidade laboral en Galicia, con propostas de mellora respecto á PRL e condicións de traballo.
Elaboración de documentación estatística derivada do tratamento dos datos que atanen á sinistralidade laboral, entendendo tanto accidentes de traballo como enfermidades profesionais e enfermidades relacionadas co traballo.
Elaboración de informes, documentos técnicos e estudos das distintas disciplinas preventivas en PRL, que a súa vez son o resultado do traballo do persoal técnico do ISSGA a través de programas executados polo propio Instituto. Isto tendo en conta os sucesivos mandatos tanto das estratexias galegas en materia de SST, como dos plans anuais de actividades do ISSGA.
Realización de campañas, alertas e difusión de documentación técnica para a promoción da PRL e o mellor cumprimento da normativa.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
