### ISSUE TITLE
Observatorio de Personas Tituladas de la Universidade de Vigo

### ISSUE THREAD

**Issue by osiris000** [JaimeObregon/observatoriospublicos.es#217]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Personas Tituladas de la Universidade de Vigo

### Sitio web

http://observatorio.uvigo.gal/es/

### Ámbito territorial

autonómico

### Tipo

publico

### Organismos que lo componen

Universidade de Vigo

### Descripción

El Observatorio de Personas Tituladas es un proyecto del Consejo Social de la Universidade de Vigo creado con el propósito de que la universidad realice un seguimiento de las personas tituladas y coordine todo lo relativo al antiguo estudiantado.

### Fecha de inicio

29 de abril de 2016

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
