### ISSUE TITLE
Observatorio de la realidad de las personas jóvenes

### ISSUE THREAD

**Issue by NussAl** [JaimeObregon/observatoriospublicos.es#219]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la realidad de las personas jóvenes

### Sitio web

https://www.vitoria-gasteiz.org/wb021/was/contenidoAction.do?idioma=es&uid=u7538efd3_12da74c12a4__7fa5

### Correo electrónico

gazteria@vitoria-gasteiz.org

### Organismos públicos de los que depende

Ayuntamiento de Vitoria-Gasteiz

### Ámbito territorial

local

### Tipo

publico

### Informes publicados

Informe especial: Estudio-diagnóstico sobre el estado de la salud mental en la población joven de Vitoria-Gasteiz
Informe del Observatorio de la realidad joven de Vitoria-Gasteiz
Informe especial: Mascarilla, cuadrilla y pintalabios. El impacto de la pandemia y sus repercusiones en la población joven LGTBI+ en Vitoria-Gasteiz
Informe especial: El impacto de los ERTE en la población joven de Vitoria-Gasteiz
Informe especial: El impacto del covid-19 en la población joven de Vitoria-Gasteiz
Informe del Observatorio Plan Joven año 2020

### Descripción

El Observatorio de la realidad de las personas jóvenes es una herramienta fundamental para mantener un conocimiento actualizado de la realidad y poder plantear y ejecutar acciones que respondan a las necesidades y expectativas de las y los destinatarios de las políticas de juventud que materializa este Plan Joven.

Los informes analizan diferentes ámbitos de la realidad, especialmente aquellos relacionados con la emancipación del colectivo joven: empleo, formación y vivienda, pero complementándolo con otros aspectos que ayudan en el camino de autonomía de las personas jóvenes: salud, actividad deportiva, euskera..

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
