### ISSUE TITLE
Observatorio de la vivienda y el suelo en Cantabria 

### ISSUE THREAD

**Issue by jczamor** [JaimeObregon/observatoriospublicos.es#221]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la vivienda y el suelo en Cantabria 

### Sitio web

https://www.observatoriovivienda.cantabria.es/estadistica-observatorio

### Organismos públicos de los que depende

Consejería de empleo y políticas sociales

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

Sí

**Comment by jczamor** [comment]
Lo de estar en activo es un decir porque parece que lo más actualizado corresponde al 2019

**Comment by JaimeObregon** [comment]
Añadido.
