### ISSUE TITLE
Observatorio de Salud Pública de Cantabria[NUEVO OBSERVATORIO]

### ISSUE THREAD

**Issue by cbragado-eurocastalia** [JaimeObregon/observatoriospublicos.es#228]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Salud Pública de Cantabria

### Sitio web

https://fmvaldecilla.es/unidad/observatorio-de-salud-publica-de-cantabria/

### Correo electrónico

rasines.l@fmvaldecilla.es

### Organismos públicos de los que depende

Fundación Marqués de Valdecilla
Servicio Cántabro de Salud
Gobierno de Cantabria

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

https://fmvaldecilla.es/unidad/proyectos-ospc/

[Estudio de Covid persistente en Cantabria 2023](https://fmvaldecilla.es/proyectos-ospc/estudio-de-covid-persistente-en-cantabria-2023/)
[Historia social en Atención Primaria de salud de Cantabria 2012-2013](https://fmvaldecilla.es/proyectos-ospc/historia-social-en-atencion-primaria-de-salud-de-cantabria-2012-2013/)
[Informe encuesta discapacidad auditiva 2023](https://fmvaldecilla.es/proyectos-ospc/informe-encuesta-discapacidad-auditiva-2023/)
[Encuesta daño cerebral 2023](https://fmvaldecilla.es/proyectos-ospc/encuesta-dano-cerebral/)
[Estudio sobre determinantes de la salud de la población gitana cántabra](https://fmvaldecilla.es/proyectos-ospc/estudio-sobre-determinantes-de-la-salud-de-la-poblacion-gitana-cantabra/)
[Estudio sobre determinantes de la salud y acceso a servicios sanitarios de la población inmigrante en Cantabria](https://fmvaldecilla.es/proyectos-ospc/estudio-sobre-determinantes-de-la-salud-y-acceso-a-servicios-sanitarios-de-la-poblacion-inmigrante-en-cantabria/)
[Estudio sobre las necesidades de los servicios y la asistencia sociosanitaria en personas en situación de discapacidad en Cantabria 2019](https://fmvaldecilla.es/proyectos-ospc/estudio-sobre-las-necesidades-de-los-servicios-y-la-asistencia-sociosanitaria-en-personas-en-situacion-de-discapacidad-en-cantabria/)
[Análisis de género](https://fmvaldecilla.es/proyectos-ospc/analisis-de-genero/)

### Descripción

El Observatorio de Salud Pública de Cantabria (OSPC) es una unidad de investigación, análisis e información sobre la situación de la salud pública de Cantabria, dependiente de la Consejería de Sanidad del Gobierno de Cantabria e incardinada en la Fundación Marques de Valdecilla (FMV).

### Fecha de inicio

El Patronato de la FMV, en sesión celebrada el 8 de julio de 2005, acordó crear un Observatorio de Salud iniciando su actividad en septiembre de 2006.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
