### ISSUE TITLE
Observatorio de vivienda y suelo de Cantabria

### ISSUE THREAD

**Issue by Numix1986** [JaimeObregon/observatoriospublicos.es#231]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de vivienda y suelo de Cantabria

### Sitio web

https://www.observatoriovivienda.cantabria.es/

### Correo electrónico

bobsvivi@cantabria.es

### Organismos públicos de los que depende

Gobierno de Cantabria
Consejería de Empleo y Políticas Sociales
Dirección General de Vivienda

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

En "novedades" hay un informe que data de abril de 2021

### Descripción

El Observatorio de la Vivienda y Suelo de debate es un foro de debate, de análisis crítico, de reflexión y generador de  propuestas de actuaciones para avanzar en un modelo de sociedad en el que la vivienda cumpla con las características que se recogen en la Nueva Agenda Urbana, un modelo  de ciudad en que se facilite el acceso a una vivienda digna accesible, eficiente, sostenible y en el que quepamos por igual.

Esta web pretende ser la ventana hacia la sociedad de manera que la información fluya en ambas direcciones. La participación ciudadana en esencial a la hora de tomar decisiones que inevitablemente afectan a la vida cotidiana. La vivienda, las ciudades, los espacios libres, etc. son elementos que forman parte de nuestra vida y que están ahí porque alguien el algún momento decidió que así fuese. Inevitablemente no llueve a gusto de todos y todos es susceptible de mejora.

La sociedad demanda una mayor implicación a todos los niveles en la toma de decisiones y tolera menos las imposiciones que se realizan y que afectan a la convivencia y el desarrollo de las ciudades.

La Agenda para el Desarrollo Sostenible (Agenda 2030), aprobada en 2015 en el marco de las Naciones Unidas, plantea como parte de su Objetivo 11 ¿Asegurar de aquí al 2030 el acceso de todas las personas a viviendas y servicios básicos adecuados, seguros y asequibles (...)".

Y  una buena parte del resto de las metas planteadas por los Objetivos de Desarrollo Sostenible, tiene relación directa con el acceso de las personas a una vivienda adecuada.

Por otra parte, la Nueva Agenda Urbana, aprobada en la Conferencia de las Naciones Unidas sobre la Vivienda y el Desarrollo Urbano Sostenible (Habitat III) que se llevó a cabo en 2016 en Quito, recoge en numerosos puntos la relevancia del derecho a la vivienda y su relación con el desarrollo urbano sostenible y pone a la vivienda en el centro de las agendas locales y nacionales, integrándolo dentro de los marcos y las estrategias nacionales de desarrollo. 

En el seno del Observatorio se van tratar todos estos temas de indudable interés y actualidad que nos preocupan como qué tipo de medidas se deben llevar a cabo para facilitar el acceso a la vivienda  en un momento en que muchas familias tienen dificultades  al carecer de recursos para poder adquirirla o para poder mantenerla o dificultades de acceso a una vivienda de alquiler en el mercado libre. En definitiva,  impulsar iniciativas que canalicen los problemas y preocupaciones de los ciudadanos para buscar soluciones consensuadas y eficaces para construir desde la reflexión y el análisis el derecho de acceso a la vivienda.

### Fecha de inicio

2016

### Cese de actividad

parece que en 2021 "muere"

### En activo

None

**Comment by JaimeObregon** [comment]
Incorporado.
