### ISSUE TITLE
Buscador rápdio

### ISSUE THREAD

**Issue by hectorfausm** [JaimeObregon/observatoriospublicos.es#234]
He creado un buscador rápido en mi local clonando el proyecto para mostrar la idea.

![imagen](https://github.com/JaimeObregon/observatoriospublicos.es/assets/7032994/08824fbe-10b5-4a6d-9b88-e32fa854875d)

Tendría las siguientes características:
 - Filtrado por cualquiera de los campos del objeto. (Solo pasándo los atributos a un método de una lista) (Hecho)
 - Filtrado lowerCase.(Hecho)
 - Filtrado tokenizado. Cada palabra introducida en el buscador es una nueva palabra de filtro separada de las anteriores. (Si os parece buena idea, lo hago también)
 - Resaltada cada una de las coincidencias en la tarjeta donde corresponda. (Si os parece buena idea, lo hago también)

**Comment by resinor** [comment]
Muy útil.

¿Sería muy complicado realizar un indicador del porcentaje de lo completado que está el observatorio?, así se identificarían más rápidamente los observatorios a los que hace falta completar información.

**Comment by JaimeObregon** [comment]
¡Mola, @hectorfausm! Si envías una PR, lo mezclo 👍

**Comment by hectorfausm** [comment]
Tiene un fallo la modificación, al filtrar se desactivan los eventos de click. Tengo preparado el arreglo.
