### ISSUE TITLE
En el archivo observatories.json hay claves duplicadas o en mal sitio

### ISSUE THREAD

**Issue by luciferfran** [JaimeObregon/observatoriospublicos.es#236]
En el archivo principal del proyecto hay claves duplicadas

Habría que unificar de alguna forma las que son duplicadas y las que parecen estar en mal sitio:

![image](https://github.com/JaimeObregon/observatoriospublicos.es/assets/562258/f830b14e-f527-46cd-8fa6-1d23c17bd9ef)

Por ejemplo en esa imagen el segundo parent parece parte de la descripción.

Un saludo

**Comment by JaimeObregon** [comment]
Gracias por apuntarlo. He eliminado todas las claves duplicadas, reordenado las claves por orden alfabético y limpiado muchos datos que, al igual que el ejemplo que apuntas, estaban mal.
