### ISSUE TITLE
Observatorio de costes del transporte de mercancías - Ministerio de Transportes

### ISSUE THREAD

**Issue by osiris000** [JaimeObregon/observatoriospublicos.es#238]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de costes del transporte de mercancías (MINT)

### Sitio web

https://www.transportes.gob.es/transporte-terrestre/servicios-al-transportista/observatorios-del-transporte/observatorios-del-transporte-de-mercancias-por-carretera/observatorios-costes-transporte-mercancias

### Ámbito territorial

estatal

### Tipo

publico

### Informes publicados

https://www.transportes.gob.es/recursos_mfom/listado/recursos/observatoriocostesenero2023.pdf

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
