### ISSUE TITLE
Observatorio Europeo Multidisciplinar de los Fondos Marinos y de la Columna de Agua-Consorcio de Infraestructuras de Investigación Europeas (EMSO ERIC).

### ISSUE THREAD

**Issue by osiris000** [JaimeObregon/observatoriospublicos.es#240]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Europeo Multidisciplinar de los Fondos Marinos y de la Columna de Agua-Consorcio de Infraestructuras de Investigación Europeas (EMSO ERIC).

### Sitio web

https://www.boe.es/eli/es/ai/2019/05/03/(1)

### Ámbito territorial

estatal

### Tipo

publico

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
