### ISSUE TITLE
Observación del territorio

### ISSUE THREAD

**Issue by osiris000** [JaimeObregon/observatoriospublicos.es#242]
### Nombre del observatorio (OBLIGATORIO)

Observación del territorio

### Sitio web

https://www.transportes.gob.es/instituto-geografico-nacional/observacion-del-territorio#:~:text=El%20objetivo%20de%20la%20observaci%C3%B3n,sat%C3%A9lite%20y%20las%20fotograf%C3%ADas%20a%C3%A9reas.

### Ámbito territorial

estatal

### Tipo

publico

### En activo

Sí

**Comment by JaimeObregon** [comment]
Pero esto no es un observatorio.
