### ISSUE TITLE
Observatorio Universitario de Becas, Ayudas al Estudio y Rendimiento Académico

### ISSUE THREAD

**Issue by osiris000** [JaimeObregon/observatoriospublicos.es#244]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Universitario de Becas, Ayudas al Estudio y Rendimiento Académico

### Sitio web

https://www.boe.es/eli/es/rd/2010/10/01/1220/con

### Organismos públicos de los que depende

Min. Educación. Min. Universidades

### Ámbito territorial

estatal

### Tipo

publico

### Descripción

Se reúne después de 7 años en 2020.
https://www.universidades.gob.es/el-observatorio-de-becas-se-reune-siete-anos-despues-para-abordar-la-reforma-del-sistema/

### Fecha de inicio

2010

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
