### ISSUE TITLE
Observatorio de Politicas Ambientales

### ISSUE THREAD

**Issue by osiris000** [JaimeObregon/observatoriospublicos.es#246]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Politicas Ambientales

### Sitio web

https://www.actualidadjuridicaambiental.com/wp-content/uploads/2022/11/2022-OPAM.pdf

### Organismos públicos de los que depende

Ministerio de Ciencia e Innovación

### Ámbito territorial

estatal

### Tipo

publico

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
