### ISSUE TITLE
Observatorio del edadismo

### ISSUE THREAD

**Issue by osiris000** [JaimeObregon/observatoriospublicos.es#249]
### Nombre del observatorio (OBLIGATORIO)

Observatorio del edadismo

### Sitio web

https://www.observatoriodeledadismo.es/

### Organismos públicos de los que depende

Ministerio de derechos sociales consumo y agenda 2030

https://blogciudades.imserso.es/-/el-observatorio-del-edadismo-publica-guia-para-una-comunicacion-libre-de-edadismo-hacia-las-personas-mayores-y-el-edadismo-hacia-las-personas-mayores-en-las-sentencias-del-tribunal-constitucional

### Ámbito territorial

estatal

### Tipo

publico

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
