### ISSUE TITLE
Observatorio Social de las personas mayores

### ISSUE THREAD

**Issue by osiris000** [JaimeObregon/observatoriospublicos.es#252]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Social de las personas mayores

### Sitio web

https://1mayo.ccoo.es/noticia:682134--CCOO_presenta_el_Observatorio_Social_de_las_personas_mayores_2023&opc_id=2910c4b71f6f452242c8bad8cf5f8f7e

### Organismos públicos de los que depende

Ministerio de Sanidad y Política Social 
Comisiones Obreras
https://imserso.es/documents/20123/0/enclaverural600054.pdf/653f3c37-2372-3c0d-55bd-857f1ed6edbc
https://www.ccoo.es/5aff3a3f46f581965359353a8f53ff10000059.pdf

### Ámbito territorial

estatal

### Tipo

mixto

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
