### ISSUE TITLE
Observatorio de la Infancia y Adolescencia de Andalucía

### ISSUE THREAD

**Issue by josesalmu** [JaimeObregon/observatoriospublicos.es#257]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Infancia y Adolescencia de Andalucía

### Sitio web

https://www.observatoriodelainfancia.es/oia/esp/index.aspx

### Correo electrónico

observatorioinfancia.assda@juntadeandalucia.es

### Organismos públicos de los que depende

Agencia de Servicios Sociales y Dependencia de Andalucía

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
