### ISSUE TITLE
Observatorio de Prácticas Innovadoras en el Manejo de Enfermedades Crónicas Complejas

### ISSUE THREAD

**Issue by josesalmu** [JaimeObregon/observatoriospublicos.es#259]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Prácticas Innovadoras en el Manejo de Enfermedades Crónicas Complejas

### Sitio web

https://www.opimec.org/

### Organismos públicos de los que depende

Consejería de Salud y Consumo de la Junta de Andalucía

### Ámbito territorial

autonómico

### Tipo

publico

### Descripción

La misión de OPIMEC es “Coordinar, desarrollar y establecer desde Andalucía, como eje en España y el ámbito internacional, las estructuras básicas precisas para la creación y consolidación de una comunidad global en el campo de las enfermedades crónicas complejas y la pluripatología, mediante la búsqueda sistemática y selección rigurosa de innovaciones y contenidos de interés así como la promoción de la colaboración y el intercambio científico y técnico".  

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
