### ISSUE TITLE
Observatorio de Inteligencia Artificial

### ISSUE THREAD

**Issue by monofilipino** [JaimeObregon/observatoriospublicos.es#266]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Inteligencia Artificial

### Sitio web

https://www.rebiun.org/observatorio-de-inteligencia-artificial

### Ámbito territorial

estatal

### Tipo

publico

### Descripción

El Observatorio de Inteligencia Artificial de REBIUN tiene como misión conocer, analizar y evaluar las principales iniciativas en materia de inteligencia artificial para determinar su incidencia y/o aplicabilidad en las bibliotecas universitarias y científicas. Establecerá sinergias con otros sectores para promover el uso de esta tecnología e impulsar su aplicación práctica, ética y deontológica.

Los objetivos del Observatorio de inteligencia artificial para el año 2024, aprobados en la Asamblea extraordinaria celebrada en formato online el 27 de febrero de 2024, son los siguientes:
AA1. Promocionar, visualizar y difundir el Observatorio
Objetivo 1. Objetivo 1. Crear y mantener página web Observatorio IA.
AA2. Identificar tendencias y buenas prácticas
Objetivo 1. Recopilar recursos de interés en el ámbito de la literatura académica, bibliotecas y organizaciones profesionales sobre IA.
AA3. Fomentar la colaboración con otros sectores
Objetivo 1. Colaborar con el Clúster FESABID.
Objetivo 2. Afianzar relaciones con CRUE.
Objetivo 3. Identificar y establecer contacto con sectores relevantes relacionados con IA.
AA4. Promover la formación del personal en IA en colaboración con la línea 3
Objetivo 1. Realizar una Jornada sobre IA online.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Es de la CRUE, las universidades españolas. No tengo claro si añadirlo o no, porque ni el observatorio ni la CRUE parecen directamente catalogables como «entidad pública».

**Comment by JaimeObregon** [comment]
El oráculo ChatGPT dice que no :)
![image](https://github.com/JaimeObregon/observatoriospublicos.es/assets/417226/b5215900-a8a7-4eba-adea-883ff45a14d4)
