### ISSUE TITLE
Observatorio de Márgenes Empresariales

### ISSUE THREAD

**Issue by JosepMor** [JaimeObregon/observatoriospublicos.es#285]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Márgenes Empresariales

### Sitio web

https://www.bde.es/wbe/es/inicio/observatorio-margenes-empresariales/

### Organismos públicos de los que depende

Ministerio de Asuntos Económicos y Transformación Digital (MINECO), 
Agencia Estatal de Administración Tributaria (AEAT)
Banco de España.

### Ámbito territorial

estatal

### Tipo

publico

### Informes publicados

Observatorio de Márgenes Empresariales – Informe Trimestral 2023/T1 Archivo PDF: Abre en nueva ventana (1 MB)
Observatorio de Márgenes Empresariales – Segundo Informe Trimestral Archivo PDF: Abre en nueva ventana (874 KB)
Observatorio de Márgenes Empresariales – Informe Trimestral 2023/T3 Archivo PDF: Abre en nueva ventana (334 KB)

### Descripción

Facilitar el acceso a los analistas, investigadores y cualquier ciudadano interesado en la información sobre los márgenes empresariales. Su objetivo es dar transparencia a las tareas realizadas y previstas por el OME y difundir la información y análisis realizados con ella.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Este ya lo tenemos en el catálogo.
