### ISSUE TITLE
Observatorio del tráfico aéreo de Barcelona

### ISSUE THREAD

**Issue by JosepMor** [JaimeObregon/observatoriospublicos.es#287]
### Nombre del observatorio (OBLIGATORIO)

Observatorio del tráfico aéreo de Barcelona

### Sitio web

https://www.cambrabcn.org/es/que-te-ofrecemos/estudios-economicos-infraestucturas/observatorio-trafico-aereo-barcelona

### Organismos públicos de los que depende

Cámara de Comercio de Barcelona

### Ámbito territorial

provincial

### Tipo

publico

### Informes publicados

48_Observatorio del tráfico aéreo de Barcelona - Carga aérea 2023 (ES/EN)
46_Observatorio del tráfico aéreo de Barcelona - Verano 2023 (ES/EN)
44_Observatorio del tráfico aéreo de Barcelona - Invierno 2022-23 (ES/EN)
42_Observatorio del tráfico aéreo de Barcelona - Carga aérea 2021 (ES/EN)
40_Observatorio del tráfico aéreo de Barcelona - Informe trimestral Julio 2021 (ES/EN)
38_Observatorio del tráfico aéreo de Barcelona - Informe trimestral Diciembre 2020 (ES/EN)
36_Observatorio del tráfico aéreo de Barcelona - Carga aérea 2019 (ES/EN)
34_Observatorio del tráfico aéreo de Barcelona - Informe trimestral Julio 2019 (ES/EN)
32_Observatorio del tráfico aéreo de Barcelona - Carga aérea 2018 (ES/EN)
30_Observatorio del tráfico aéreo de Barcelona - Invierno 2017 (ES/EN)
28_Observatorio del tráfico aéreo de Barcelona - Pasajeros 1T 2017 (ES/EN)
26_Observatorio del tráfico aéreo de Barcelona - Carga aérea 2015 (ES/EN)
24_Observatorio del tráfico aéreo de Barcelona - Carga aérea 2014 (ES/EN)
22_Observatorio del tráfico aéreo de Barcelona - Pasajeros 3T 2014 (ES/EN)
20_Observatorio del tráfico aéreo de Barcelona - Pasajeros 1T 2014 (ES/EN)
18_Observatorio del tráfico aéreo de Barcelona - Pasajeros 4T 2013 (ES/EN)
16_Observatorio del tráfico aéreo de Barcelona - Pasajeros 2T 2013 (ES/EN)
14_Observatorio del tráfico aéreo de Barcelona - Carga aérea 2012 (ES/EN)
47_Observatorio del tráfico aéreo de Barcelona - Invierno 2023-24 (ES/EN)
45_Observatorio del tráfico aéreo de Barcelona - Carga aérea 2022 (ES/EN)
43_Observatorio del tráfico aéreo de Barcelona - Verano

### Descripción

El objetivo del Observatorio del Tráfico Aéreo en Barcelona es hacer un seguimiento exhaustivo de la evolución de la actividad del Aeropuerto de Barcelona.
Su serie de informes compila semestralmente datos que presentan la evolución del tráfico de pasajeros en Barcelona, así como una comparativa con magnitudes equivalentes en los aeropuertos de España y de Europa.
Anualmente, este observatorio también publica informes de carga aérea en España y en Barcelona, con la colaboración de Barcelona Centre Logístic.
Esta publicación está disponible en formato bilingüe: español / inglés.

### En activo

Sí

**Comment by JaimeObregon** [comment]
No parece un observatorio público (la Cámara es una organización privada, AFAIK).
