### ISSUE TITLE
Observatorio del tráfico aéreo de Barcelona

### ISSUE THREAD

**Issue by JosepMor** [JaimeObregon/observatoriospublicos.es#289]
### Nombre del observatorio (OBLIGATORIO)

Observatorio del tráfico aéreo de Barcelona

### Sitio web

https://www.cambrabcn.org/es/que-te-ofrecemos/estudios-economicos-infraestucturas/observatorio-trafico-aereo-barcelona

### Organismos públicos de los que depende

Cámara e Comercio de Barcelona

### Ámbito territorial

provincial

### Tipo

publico

### Descripción

Información sobre la actividad aeroportuaria de Barcelona.
El objetivo del Observatorio del Tráfico Aéreo en Barcelona es hacer un seguimiento exhaustivo de la evolución de la actividad del Aeropuerto de Barcelona.
Su serie de informes compila semestralmente datos que presentan la evolución del tráfico de pasajeros en Barcelona, así como una comparativa con magnitudes equivalentes en los aeropuertos de España y de Europa.
Anualmente, este observatorio también publica informes de carga aérea en España y en Barcelona, con la colaboración de Barcelona Centre Logístic.
Esta publicación está disponible en formato bilingüe: español / inglés.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Duplicado de #287
