### ISSUE TITLE
Observatorio de la Calidad de Tenerife

### ISSUE THREAD

**Issue by Marcediaz76** [JaimeObregon/observatoriospublicos.es#296]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Calidad de Tenerife

### Sitio web

https://www.calidadtenerife.org/

### Correo electrónico

observatorio@tenerife.es

### Organismos públicos de los que depende

Cabildo de Tenerife

### Ámbito territorial

local

### Tipo

publico

### Organismos que lo componen

Cabildo de Tenerife

### Descripción

El Observatorio de la Calidad de Tenerife es una iniciativa del Cabildo Insular, orientada al estudio, análisis y evolución de las nuevas tendencias y modelos de calidad de gestión en el ámbito nacional e internacional, dirigida especialmente a monitorizar y fomentar la implantación de la calidad en Tenerife.

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
