### ISSUE TITLE
Observatorio Ambiental Granadilla

### ISSUE THREAD

**Issue by Marcediaz76** [JaimeObregon/observatoriospublicos.es#298]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Ambiental Granadilla

### Sitio web

https://www.oag-fundacion.org/

### Correo electrónico

info@oag-fundacion.org

### Organismos públicos de los que depende

Gobierno de Canarias- Consejería de Transición Ecológica y Energía   

### Ámbito territorial

local

### Tipo

publico

### Organismos que lo componen

Gobierno de Canarias- Consejería de Transición Ecológica y Energía   
Autoridad Portuaria de S/C de Tenerife   
Ministerio para la Transición Ecológica   
Universidad de La Laguna  

### Descripción

El fin fundacional del OAG es garantizar que el puerto de Granadilla se construya y gestione de manera respetuosa con el medio ambiente, controlando el estado y las tendencias de la biodiversidad local y garantizando al mismo tiempo, la aplicación adecuada de las medidas correctores y compensatorias

### En activo

None

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
