### ISSUE TITLE
Observatorio de Vivienda y Suelo

### ISSUE THREAD

**Issue by JosepMor** [JaimeObregon/observatoriospublicos.es#301]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Vivienda y Suelo

### Sitio web

https://www.mivau.gob.es/urbanismo-y-suelo/suelo/observatorio-de-vivienda-y-suelo

### Organismos públicos de los que depende

Ministerio de Vivienda y Agenda Urbana

### Ámbito territorial

estatal

### Tipo

publico

### Informes publicados

[](https://www.mivau.gob.es/urbanismo-y-suelo/suelo/observatorio-de-vivienda-y-suelo)

### Descripción

una herramienta que facilita, a través de la publicación de boletines estadísticos electrónicos, la utilización integrada de los datos disponibles en las principales fuentes estadísticas oficiales

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
