### ISSUE TITLE
Observatorio Municipal de Protección Animal de Alcoi

### ISSUE THREAD

**Issue by AlexRVillalobos** [JaimeObregon/observatoriospublicos.es#303]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Municipal de Protección Animal de Alcoi

### Sitio web

https://www.alcoi.org/es/areas/sanidad/bienestar_animal/observatorio_proteccion.html

### Correo electrónico

sanitat@alcoi.org

### Organismos públicos de los que depende

Ayuntamiento de Alcoy

### Ámbito territorial

local

### Tipo

publico

### Informes publicados

[Acta 2022 ](https://www.alcoi.org/export/sites/default/es/areas/sanidad/descargas/Acta_2022_11.pdf)

### Descripción

De acuerdo con la Declaración Universal del derecho de los Animales que es aprobada por la Unesco el 27 de octubre de 1978 y ratificada posteriormente por las Naciones Unidas, los animales son seres vivos sensibles que tienen unos derechos que la especie humana tiene que respetar. Los animales de compañía son cada vez más variados, y en todas las legislaciones modernas se les otorga la consideración de un bien juridíco a proteger.

El Ayuntamiento tiene el deber de proteger a los animales, de acuerdo a las normas y principios constitucionales vigentes, sin prejuicio también de velar por la seguridad de las personas y de sus bienes. Por otra parte, es prioridad de este gobierno municipal aumentar la protección de los animales y aumentar la convivencia de estos con las personas.

Por todo esto se ha creado el Observatorio de Protección Animal del ayuntamiento de Alcoy.

### En activo

None

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
