### ISSUE TITLE
Observatori de la Seguretat Viària

### ISSUE THREAD

**Issue by JosepMor** [JaimeObregon/observatoriospublicos.es#305]
### Nombre del observatorio (OBLIGATORIO)

Observatori de la Seguretat Viària

### Sitio web

https://transit.gencat.cat/ca/seguretat_viaria/observatori/

### Organismos públicos de los que depende

 Servei Català de Trànsit

### Ámbito territorial

autonómico

### Tipo

publico

### Descripción

Reducir la frecuencia y gravedad de los accidentes de tráfico e incrementar los medios y recursos destinados a la prevención de siniestros y a la atención de las víctimas

### En activo

Sí

**Comment by JaimeObregon** [comment]
¡Gracias! Lo añado manualmente, que hay demasiados conflictos de mezclado.
