### ISSUE TITLE
Observatorio turístico de Alcoi

### ISSUE THREAD

**Issue by AlexRVillalobos** [JaimeObregon/observatoriospublicos.es#307]
### Nombre del observatorio (OBLIGATORIO)

Observatorio turístico de Alcoi

### Sitio web

https://www.alcoyturismo.com/pag/4174/observatorio-turistico.html

### Correo electrónico

touristinfo@alcoi.org

### Organismos públicos de los que depende

Ayuntamiento de Alcoy

### Ámbito territorial

local

### Tipo

publico

### Informes publicados

[Informes Tourist Info (2014-2023)](https://www.alcoyturismo.com/pag/4174/observatorio-turistico.html)

### Fecha de inicio

2014

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
