### ISSUE TITLE
	Observatorio Hispano-Francés de Tráfico en los Pirineos

### ISSUE THREAD

**Issue by JosepMor** [JaimeObregon/observatoriospublicos.es#309]
### Nombre del observatorio (OBLIGATORIO)

	Observatorio Hispano-Francés de Tráfico en los Pirineos

### Sitio web

https://cpage.mpr.gob.es/producto/observatorio-hispano-frances-de-trafico-en-los-pirineos-11/

### Organismos públicos de los que depende

Ministerio de Transportes, Movilidad y Agenda Urbana

### Ámbito territorial

estatal

### Tipo

publico

### Informes publicados

Núm. 9, suplemento, 2021. --Principales cifras actualizadas para el año 2018

### En activo

None

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
