### ISSUE TITLE
Observatori del Sistema Penal i els Drets Humans

### ISSUE THREAD

**Issue by Devba** [JaimeObregon/observatoriospublicos.es#313]
### Nombre del observatorio (OBLIGATORIO)

Observatori del Sistema Penal i els Drets Humans

### Sitio web

https://twitter.com/OSPDH1

### Correo electrónico

alvaro@1mag1na.xyz

### Organismos públicos de los que depende

Pues yo diria que de la Generalidad de Cataluña

### Ámbito territorial

autonómico

### Tipo

publico

### Descripción

Ni idea , me lo acabo de encontrar en X

### En activo

Sí

**Comment by JaimeObregon** [comment]
Estos datos son incorrectos, pero el observatorio ya ha sido añadido con datos más exactos.

**Comment by JaimeObregon** [comment]
Este ya le tenemos fichado :)
