### ISSUE TITLE
OBSERVATORIO DE SALUD EN ASTURIAS

### ISSUE THREAD

**Issue by jamfer65** [JaimeObregon/observatoriospublicos.es#315]
### Nombre del observatorio a editar (OBLIGATORIO)

OBSERVATORIO DE SALUD EN ASTURIAS

### Sitio web

https://obsaludasturias.com/obsa/

### Correo electrónico

obsalud@asturias.org

### Organismos públicos de los que depende

Dirección General de Salud Pública, en la Consejería de Sanidad del Gobierno del Principado de Asturias.

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

https://obsaludasturias.com/obsa/wp-content/uploads/EVALUACION-PSM-15-20-1.pdf
https://obsaludasturias.com/obsa/wp-content/uploads/Informe%20de%20los%20rankings%20por%20concejos%202016.pdf
https://obsaludasturias.com/obsa/wp-content/uploads/Informe%20de%20los%20rankings%20por%20variables%202016.pdf

### Organismos que lo componen

[Gobierno del Principado de Asturias. School of Medicine and Public Health. University of Wisconsin.

### Descripción

Visión del estado de salud sn Asturias

### Fecha de inicio

27 de mayo 2011

### En activo

Sí

**Comment by jamfer65** [comment]
Última actualización de la página 4 de Octubre de 2011. Desde 2020 no hay ningún informe. El anterior de 2016. Equipo de trabajo 7 personas (incluido consejero). Supongo que algo habrá cambiado desde 2011.

**Comment by JaimeObregon** [comment]
Añadido.
