### ISSUE TITLE
OBSERVATORIO ASTURIANO DE ASUNTOS SOCIALES

### ISSUE THREAD

**Issue by jamfer65** [JaimeObregon/observatoriospublicos.es#316]
### Nombre del observatorio (OBLIGATORIO)

OBSERVATORIO ASTURIANO DE ASUNTOS SOCIALES

### Sitio web

https://observass.com/que-es-observass/

### Correo electrónico

NO CONSTA

### Organismos públicos de los que depende

CONSEJERIA DE SERVICIOS SOCIALES

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

https://observass.com/wp-content/uploads/2023/04/Indicador-sint%C3%A9tico-resistencia-a-la-pobrezadef.pdf
https://observass.com/wp-content/uploads/2021/06/PREVISIO%CC%81N-DEMANDA-CUIDADOS-RESIDENCIALES-PERSONAS-MAYORES.pdf

### Descripción

1. El OBSERVASS tiene como objetivos el estudio, análisis y seguimiento del sistema público de servicios sociales y de
su capacidad de respuesta a las necesidades de las personas y de los diferentes colectivos y sus especificidades. Para ello
desarrollará actuaciones de investigación y documentación, así como el establecimiento de un sistema de información
que permita el adecuado conocimiento del sistema público de servicios sociales y del efecto que tienen en las personas
sus prestaciones y servicios.

### Fecha de inicio

31/05/2017 SALIÓ EN EL BOPA

### En activo

Sí

**Comment by JaimeObregon** [comment]
Este ya le tenemos fichado :)
