### ISSUE TITLE
Observatori de la Producció Audiovisual (OPA)

### ISSUE THREAD

**Issue by osiris000** [JaimeObregon/observatoriospublicos.es#319]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Producción Audidovisual

### Sitio web

https://www.upf.edu/web/opa

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

https://www.upf.edu/web/opa/estudis/-/asset_publisher/IrXIFT9fCBC2/content/la-produccio-de-cinema-a-catalunya-2022-1/maximized

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
