### ISSUE TITLE
Observatorio Aragonés para el Sahara Occidental

### ISSUE THREAD

**Issue by mrmx** [JaimeObregon/observatoriospublicos.es#321]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Aragonés para el Sahara Occidental

### Sitio web

https://observatorioaragonessahara.org/

### Correo electrónico

info@observatorioaragonessahara.org

### Ámbito territorial

autonómico

### Tipo

publico

### Fecha de inicio

Noviembre 2013

### En activo

Sí

**Comment by JaimeObregon** [comment]
No parece público o público-privado. Cierro.
