### ISSUE TITLE
Observatori del Partits Polítics de Catalunya

### ISSUE THREAD

**Issue by osiris000** [JaimeObregon/observatoriospublicos.es#323]
### Nombre del observatorio (OBLIGATORIO)

Observatori del Partits Polítics de Catalunya

### Sitio web

https://www.upf.edu/web/opcat

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
