### ISSUE TITLE
Observatori Català de la Justícia en Violència Masclista

### ISSUE THREAD

**Issue by osiris000** [JaimeObregon/observatoriospublicos.es#325]
### Nombre del observatorio (OBLIGATORIO)

Observatori Català de la Justícia en Violència Masclista

### Sitio web

https://cejfe.gencat.cat/ca/observatori/

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

Sí

**Comment by JaimeObregon** [comment]
Está repetido. Cierro.
