### ISSUE TITLE
Observatori per al Desenvolupament Sostenible de la Garrotxa

### ISSUE THREAD

**Issue by osiris000** [JaimeObregon/observatoriospublicos.es#327]
### Nombre del observatorio (OBLIGATORIO)

Observatori per al Desenvolupament Sostenible de la Garrotxa

### Sitio web

https://www.observatorigarrotxa.cat/

### Correo electrónico

info@observatorigarrotxa.cat

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
