### ISSUE TITLE
Observatorio de la Cultura Emprendedora

### ISSUE THREAD

**Issue by osiris000** [JaimeObregon/observatoriospublicos.es#329]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Cultura Emprendedora

### Sitio web

https://observatorioculturaemprendedora.es/

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

Sí

**Comment by JaimeObregon** [comment]
Lo cierro sin añadir porque no parece que sea un observatorio público o público-privado. Si no es así, porfa reabre y lo añadimos :)

**Comment by osiris000** [comment]
No sé si ahora es privado sólamente, pero se puso en marcha con
subvenciones públicas,
 “desgraciada y casualmente” el pdf al que apunta el registro, no existe.
Cuando meta los csv de jurídicas en la bd a ver si cruzando datos, para
estos casos, arroja más información.
Porque me estoy encontrando muchos casos de subvenciones en los que la
páginas o archivos a que referencian ya no existen.

EXTREMADURA
CONSEJERÍA DE EDUCACIÓN Y EMPLEO
Subv.Nominativa 2019 a la Fundación Universidad-Sociedad de la
Universidad de Extremadura para la puesta en marcha del Proyecto
Observatorio de Cultura Emprendedora.
NULLhttp://doe.gobex.es/pdfs/doe/2019/160o/19010002.pdf

**Comment by osiris000** [comment]
Parece que lo gestiona de alguna manera la junta de extremadura a través de
la fundación universidades.

https://www.uexfundacion.es/actividad/observatorio-de-cultura-emprendedora-en-extremadura/
Observatorio de Cultura Emprendedora en Extremadura
WEB: https://observatorioculturaemprendedora.es/ EMAIL:
***@***.*** INSTAGRAM:
https://www.instagram.com/culturaemprendedoraext/ FACEBOOK:
https://www.facebook.com/search/top?q=cultura%20emprendedora TWITTER:
https://twitter.com/CulEmprendedora Dirección: Avd Elvas s/n 06006 Badajoz

**Comment by osiris000** [comment]
Al final todos los caminos llevan a Roma :-D
