### ISSUE TITLE
Observatori del Paisatge de Catalunya

### ISSUE THREAD

**Issue by osiris000** [JaimeObregon/observatoriospublicos.es#331]
### Nombre del observatorio (OBLIGATORIO)

Observatori del Paisatge de Catalunya

### Sitio web

https://www.catpaisatge.net/ca

### Correo electrónico

observatori@catpaisatge.net

### Organismos públicos de los que depende

https://www.miteco.gob.es/es/ceneam/recursos/quien-es-quien/observatori.html

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

[Facebook](https://www.facebook.com/catpaisatge/?locale=es_ES) - [Instagram](https://www.instagram.com/arxiucatpaisatge/) - [Vimeo](https://vimeo.com/catpaisatge) - [X](https://twitter.com/catpaisatge?lang=es)

### En activo

Sí

**Comment by JaimeObregon** [comment]
Este ya le tenemos fichado :)
