### ISSUE TITLE
Observatorio Agenda Provincia de Cáceres

### ISSUE THREAD

**Issue by unstoppabl0** [JaimeObregon/observatoriospublicos.es#333]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Agenda Provincia de Cáceres

### Sitio web

https://observatoriodipcc.dip-caceres.es/

### Correo electrónico

datos-territoriales@dip-caceres.es

### Organismos públicos de los que depende

Diputación de Cáceres

### Ámbito territorial

provincial

### Tipo

publico

### Informes publicados

Mñ´´as que informes parece que se limita a recoger indicadores sobre diferentes objetivos, relacionados con los denominados Objetivos de Desarrollo Sostenibles

### Descripción

El “Observatorio Agenda Provincia de Cáceres” se concibe con el objetivo de integrar de forma estructurada tanto la información socioeconómica, como la generada en las distintas acciones incluidas en el Plan de Acción de Diputación de Cáceres.

Este observatorio permitirá realizar el seguimiento de la evolución de los indicadores registrados actualmente y de aquellos que se incorporen durante la consecución de las acciones incluidas en el Plan de Acción de Diputación de Cáceres, constituyendo una herramienta fundamental tanto para las tareas de planificación de Diputación de Cáceres como para la transferencia de resultados a la ciudadanía.

### Fecha de inicio

11 de diciembre de 2021 

"Diputación de Cáceres desarrolla el “Observatorio Agenda Provincia de Cáceres” con cargo a la ayuda concedida el 11 de diciembre de 2021 por el Ministerio de Transportes, Movilidad y Agenda Urbana, para la elaboración de proyectos piloto de planes de acción local de la Agenda Urbana Española."

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
