### ISSUE TITLE
[NUEVO OBSERVATORIO]  Observatorio socio-economico de la Diputación de Cáceres

### ISSUE THREAD

**Issue by unstoppabl0** [JaimeObregon/observatoriospublicos.es#335]
### Nombre del observatorio (OBLIGATORIO)

Observatorio socio-economico de la Diputación de Cáceres

### Sitio web

http://observatorio.dip-caceres.es/Observatorio2/bienvenida.do

### Correo electrónico

observatorio@dip-caceres.es

### Ámbito territorial

estatal

### Tipo

publico

### Informes publicados

Estudios monográficos

Análisis del sector agroalimentario de la Provincia de Cáceres. Abril 2018
Estudio de tendencias y oportunidades del emprendimiento - Resumen. Abril 2017
Estudio de tendencias y oportunidades del emprendimiento - Completo. Abril 2017
[Informe de Indicadores de Sostenibilidad OTALEX C](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20recientes/18-INFORME%20INDICADORES%20SOSTENIBILIDAD%20OTALEXC.pdf)
[Estudio de Accesibilidad Viaria OTALEX C](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20recientes/19-Estudio%20de%20Accesibilidad%20Viaria%20OTALEX-C.pdf)
Estudio Socioeconómico OTALEX C

Informes socioeconómicos

Informe socioeconómico de la provincia de Cáceres. Abril 2015
Informe socioeconómico de la provincia de Cáceres. I semestre de 2012
[Informe socioeconómico de la provincia de Cáceres. Primer semestre de 2010](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20antiguos/6-Informe%20socioeconomico%20de%20la%20provincia%20de%20Caceres.%20Primer%20semestre%20de%202010.pdf)
[Informe socioeconómico de la provincia de Cáceres. Segundo semestre de 2009](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20antiguos/5-Informe%20socioeconomico%20de%20la%20provincia%20de%20Caceres.%20Segundo%20semestre%20de%202009.pdf)
[Informe socioeconómico de la provincia de Cáceres. Primer semestre de 2009](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20antiguos/4-Informe%20socioeconomico%20de%20la%20provincia%20de%20Caceres.%20Primer%20semestre%20de%202009.pdf)
[Análisis socioeconómico provincial perteneciente al Proyecto ISLA 2011. Mayo de 2008](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20antiguos/2-Analisis%20socioeconomico%20provincial%20perteneciente%20al%20Proyecto%20ISLA%202011.%20Mayo%20de%202008.pdf)

Estudios del mercado laboral

[Estudio del mercado laboral y tejido productivo de Aldea del Cano. 2016](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20recientes/22-Mercado_laboral_tejido_productivo_Aldea_Cano_2016.pdf)
Análisis del sistema de afiliaciones de la provincia de Cáceres
Análisis del mercado laboral del municipio de Moraleja
[Agrupación de Mancomunidades atendiendo a las actividades económicas de las personas ocupadas](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Agrupacion%20de%20Mancomunidades%20atendiendo%20a%20las%20actividades%20economicas%20de%20las%20personas%20ocupadas.pdf)
Análisis del desempleo juvenil en la provincia de Cáceres
Estudio del mercado laboral de la ciudad de Cáceres
Informe del mercado laboral de la provincia de Cáceres. II semestre de 2011

Estrategía de los Grupos de Acción Local

[Estrategia de Desarrollo Local ADEME](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20recientes/13-EDL%20ADEME%20FINAL.pdf)
[Estrategia de Desarrollo Local ADISGATA](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20recientes/14-EDL%20ADISGATA%20FINAL.pdf)
[Estrategia de Desarrollo Local ADISMONTA](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20recientes/15-EDL%20ADISMONTA%20FINAL.pdf)
[Estrategia de Desarrollo Local APRODERVI](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20recientes/16-EDL%20APRODERVI%20FINAL.pdf)
[Estrategia de Desarrollo Local TAGUS](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20recientes/17-EDL%20TAGUS%20FINAL.pdf)

Informes temáticos

[Estrategia DUSI de Plasencia y entorno. 2017](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20recientes/20-Estrategia_DUSI_Plasencia-entorno-FINAL.pdf)
[Población y territorio en la provincia de Cáceres. 2016](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20recientes/21-Poblacion%20y%20territorio%20en%20la%20provincia%20de%20Caceres.pdf)
Análisis Territorial de Valencia de Alcántara
Comercio y turismo en el centro de la ciudad de Cáceres
Análisis de la población por barrios y barriadas de la ciudad de Cáceres
Sector turístico en la Reserva de la Biosfera de Monfragüe
[Análisis territorial del ámbito territorial de la Reserva de la Biosfera de Monfragüe. Julio de 2008](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20antiguos/3-Analisis%20territorial%20del%20ambito%20territorial%20de%20la%20Reserva%20de%20la%20Biosfera%20de%20Monfrague.%20Julio%20de%202008.pdf)
[Informe de situación de AEDL](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20antiguos/7-Informe%20de%20situacion%20de%20AEDL.pdf)

Mapas temáticos

[Despoblamiento de la provincia de Cáceres - Estructura de la población](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/mapas_observatorio/Demo1.jpg)
[Despoblamiento de la provincia de Cáceres - Situación territorial](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/mapas_observatorio/Demo2.jpg)
[Despoblamiento de la provincia de Cáceres - Variación de la población](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/mapas_observatorio/Dif_pob_2007_2016.jpg)
[Demografía de la provincia de Cáceres (Mancomunidades)](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/mapas_observatorio/demo_mancomunidades.pdf)
[Demografía de la provincia de Cáceres (Municipios)](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/mapas_observatorio/demo_municipios.pdf)
[Tejido empresarial de la provincia de Cáceres (Mancomunidades)](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/mapas_observatorio/empresa_manco.pdf)
[Tejido empresarial de la provincia de Cáceres (Municipios)](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/mapas_observatorio/empresa_muni.pdf)
[Mercado laboral de la provincia de Cáceres (Mancomunidades)](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/mapas_observatorio/laboral_manco.pdf)
[Mercado laboral de la provincia de Cáceres (Municipios)](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/mapas_observatorio/laboral_muni.pdf)
[Recursos turísticos de la provincia de Cáceres](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/mapas_observatorio/turismo.pdf)
[Oferta turística de la provincia de Cáceres (Mancomunidades)](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/mapas_observatorio/turismo_manco.pdf)
[Oferta turística de la provincia de Cáceres (Municipios)](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/mapas_observatorio/turismo_muni.pdf)
[Mancomunidades integrales](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/mapas_observatorio/Mancomunidades_integrales.pdf)

### Descripción

Desde el Observatorio Socioeconómico Provincial se pretende facilitar a los Ayuntamientos de la provincia la tarea de acercar la información fiscal a los ciudadanos de una forma más transparente, y ayudarles a comunicar de forma gráfica y accesible de donde vienen sus ingresos y en qué se gastan los impuestos recaudados. 

### Fecha de inicio

21/04/2014

https://www.expansion.com/2014/04/16/extremadura/1397658694.html

### En activo

Sí

**Comment by JaimeObregon** [comment]
Este ya le tenemos fichado :)
