### ISSUE TITLE
Observatorio de Finanzas Islámicas en España 

### ISSUE THREAD

**Issue by arodrrosa** [JaimeObregon/observatoriospublicos.es#337]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Finanzas Islámicas en España SCIEF-Casa Árabe

### Sitio web

https://www.casaarabe.es/eventos-arabes/show/observatorio-de-finanzas-islamicas-en-espana

### Organismos públicos de los que depende

Ministerio de Asuntos Exteriores
Unión Europea y de Cooperación (MAEUEC)
Agencia Española de Cooperación Internacional para el Desarrollo (AECID)
Junta de Andalucía
Comunidad de Madrid
Ayuntamiento de Madrid
Ayuntamiento de Córdoba

### Ámbito territorial

estatal

### Tipo

mixto

### Descripción

Sus actividades incluyen la reunión periódica de sus miembros sobre temas particulares relativos al desarrollo de la industria en España, la realización de estudios de caso y conferencias de expertos, así como la elaboración de un informe anual sobre el estado de las finanzas islámicas en España.

### Fecha de inicio

20 de junio de 2017

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! En un ratillo aparecerá publicado.
