### ISSUE TITLE
[NUEVO OBSERVATORIO]

### ISSUE THREAD

**Issue by bermix15** [JaimeObregon/observatoriospublicos.es#340]
### Nombre del observatorio (OBLIGATORIO)

Observatorio estatal de la soledad no deseada

### Sitio web

https://www.soledades.es/

### Ámbito territorial

estatal

### Tipo

publico

### Informes publicados

[Estudio sobre juventud y soledad no deseada en españa](https://www.soledades.es/estudios/estudio-sobre-juventud-y-soledad-no-deseada-en-espana)
[El coste de la soledad no deseada en España](https://www.soledades.es/estudios/el-coste-de-la-soledad-no-deseada-en-espana)

### Organismos que lo componen

Fundación ONCE, Plataforma de mayores y pensionistas

### Descripción

Fundación ONCE motivada por la sensibilización y generación de conocimiento sobre la soledad no deseada
La mejora en las políticas y programas para combatir la soledad no deseada requiere de un seguimiento, observación y análisis de la problemática de la soledad a nivel estatal.

La soledad no deseada es un problema social que afecta cada vez a más personas en Europa y en especial en España. Supone una fuente de sufrimiento, limita el derecho de participación en la sociedad y tiene consecuencias negativas en varios aspectos de la vida, generando costes sociales. Se presenta en todos los grupos de edad, aunque afecta especialmente a las personas mayores, así como a las personas con discapacidad.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Es de la Fundación ONCE, que no es una entidad pública.
