### ISSUE TITLE
Observatori socioeconòmic d'osona

### ISSUE THREAD

**Issue by Patunikos** [JaimeObregon/observatoriospublicos.es#344]
### Nombre del observatorio (OBLIGATORIO)

Observatori socioeconòmic d'Osona

### Sitio web

http://www.observatorisocioeconomicosona.cat/

### Correo electrónico

observatori@creaccio.cat

### Ámbito territorial

provincial

### Tipo

publico

### Organismos que lo componen

Ajuntament de Vic - Creacció
Ajuntament de Manlleu
Cambra d'Osona
UVic
CEDO

### Descripción

-eina de monitorització de la realitat i la competitivitat comarcal 
-Observatori de prospectiva i anàlisi de les megatendències de futur.

### Fecha de inicio

2017

### En activo

Sí

**Comment by JaimeObregon** [comment]
¡Gracias! Lo añado manualmente, que hay demasiados conflictos de mezclado.
