### ISSUE TITLE
[NUEVO OBSERVATORIO] Observatori Social de les Illes Balears

### ISSUE THREAD

**Issue by AlejandroHinojosaRubio** [JaimeObregon/observatoriospublicos.es#349]
### Nombre del observatorio (OBLIGATORIO)

Observatori Social de les Illes Balears

### Sitio web

https://osib.uib.cat/

### Organismos públicos de los que depende

- Govern de les Illes Balears
- Universitat de les Illes Balears

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

- [La renda mínima d'inserció i la gestió del risc social](https://osib.uib.cat/digitalAssets/235/235725_informe01.pdf)
- [La diversidad familiar en las islas Baleares. Continuidades y nuevas tendencias.](https://osib.uib.cat/digitalAssets/235/235728_informe02.pdf)

### Organismos que lo componen

- Govern de les Illes Balears
- Universitat de les Illes Balears
- Càtedra d’Innovació Social “la Caixa”

### Descripción

Aquest projecte va néixer a la UIB l'any 2008 com a resultat del conveni de col·laboració entre el Govern Balear i la Universitat de les Illes Balears en matèria de serveis socials. Aquella primera etapa es va desenvolupar entre 2008 i 2012. Ara, en un context difícil de nou, la Universitat de les Illes Balears, a través de la Càtedra d’Innovació Social “la Caixa”, dóna un nou impuls a l'Observatori Social de les Illes Balears, amb l’objectiu de recollir i generar informació per millorar el coneixement de la situació social de Mallorca, Menorca, Eivissa i Formentera i detectar situacions emergents, punts crítics i respostes innovadores que facilitin la cohesió i la justícia social.

### Fecha de inicio

2008

### En activo

Sí

**Comment by JaimeObregon** [comment]
¡Añadido! Muchas gracias :)
