### ISSUE TITLE
[NUEVO OBSERVATORIO] Observatori per a la igualtat

### ISSUE THREAD

**Issue by AlejandroHinojosaRubio** [JaimeObregon/observatoriospublicos.es#351]
### Nombre del observatorio (OBLIGATORIO)

Observatori per a la igualtat

### Sitio web

https://observatori-igualtat.es/es/

### Correo electrónico

ibdona@ibdona.caib.es

### Organismos públicos de los que depende

- Govern de les Illes Balears
- Institut Balear de la Dona
- Conselleria Famílies i Afers Socials

### Ámbito territorial

autonómico

### Tipo

publico

### Organismos que lo componen

- Govern de les Illes Balears
- Institut Balear de la Dona
- Conselleria Famílies i Afers Socials

### Descripción

El Observatorio tiene como finalidad analizar y difundir información sobre la evolución de los indicadores relativos a la igualdad entre mujeres y hombres, para mejorar la planificación y evaluación de las políticas públicas desde la perspectiva de género.

### Fecha de inicio

N/A

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
