### ISSUE TITLE
[NUEVO OBSERVATORIO] Observatorio de Turismo Sostenible de Mallorca

### ISSUE THREAD

**Issue by AlejandroHinojosaRubio** [JaimeObregon/observatoriospublicos.es#353]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Turismo Sostenible de Mallorca

### Sitio web

https://stomallorca.com

### Correo electrónico

hello@stomallorca.com

### Organismos públicos de los que depende

- Consell de Mallorca
- Fundación Mallorca Turismo
- Conselleria Model Econòmic, Turisme i Treball

### Ámbito territorial

local

### Tipo

publico

### Informes publicados

[Informe de coyuntura 2022](https://stomallorca.com/informes/)

### Organismos que lo componen

- La Agencia de Estrategia Turística de las Islas Baleares (AETIB)
- La Federación de Entidades Locales de las Islas Baleares (FELIB)
- La Cámara de Comercio de Mallorca
- AENA (Aeropuertos Españoles y Navegación Aérea)
- La Autoridad Portuaria de Baleares (APB)
- La Agencia Estatal de Meteorología (AEMET)
- El Instituto de Estadística de las Illes Balears (IBESTAT)
- Federación Empresarial Hotelera de Mallorca
- Agrupación de Cadenas Hoteleras Baleares
- Agrupación Empresarial de Agencias de Viaje de Baleares
- Creado en 1905, Fomento del Turismo de Mallorca
- La Fundación Impulsa Balears
- El clúster internacional de las Tecnologías de la Información y la Comunicación aplicadas al Turismo (TURISTEC)
- La Universitat de les Illes Balears (UIB)

### Descripción

STO Mallorca nace en el marco del [Plan de Recuperación, Transformación y Resiliencia del Gobierno de España](https://www.mincotur.gob.es/es-es/recuperacion-transformacion-resiliencia/paginas/plan-recuperacion-transformacion-resiliencia.aspx) con los fondos europeos Next Generation EU alineados con el plan estratégico de la FMT.

El Observatorio de Turismo Sostenible de Mallorca tiene como misión generar información de valor que permita guiar las decisiones del sector público y privado, dotando de inteligencia toda la cadena de valor de forma que se incrementa su competitividad y productividad, teniendo siempre en consideración los principios directores de la sostenibilidad.  

El Observatorio de Turismo Sostenible de Mallorca tiene como misión generar información de valor que permita guiar las decisiones del sector público y privado, dotando de inteligencia toda la cadena de valor de forma que se incrementa su competitividad y productividad, teniendo siempre en consideración los principios directores de la sostenibilidad.  

### Fecha de inicio

N/A

### En activo

None

**Comment by JaimeObregon** [comment]
¡Gracias! Lo añado manualmente, que hay demasiados conflictos de mezclado.
