### ISSUE TITLE
Observatorio ciutadano de la Sequía

### ISSUE THREAD

**Issue by ajut400** [JaimeObregon/observatoriospublicos.es#355]
### Nombre del observatorio (OBLIGATORIO)

Observatorio ciutadano de la Sequía

### Sitio web

https://www.creaf.cat/es/observatorio-ciutadano-de-la-sequia

### Correo electrónico

contacte@creaf.uab.cat

### Ámbito territorial

estatal

### Tipo

publico

### Descripción

El Observatorio Ciudadano de la Sequía es un proyecto de ciencia ciudadana que tiene por objetivo avanzar en el mejor conocimiento del riesgo de sequía en España. 

### Fecha de inicio

Noviembre 2020

### En activo

None

**Comment by JaimeObregon** [comment]
¡Gracias! Lo añado manualmente, que hay demasiados conflictos de mezclado.
