### ISSUE TITLE
[NUEVO OBSERVATORIO] Observatorio SABE

### ISSUE THREAD

**Issue by JCGF-OSM** [JaimeObregon/observatoriospublicos.es#359]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la cuenca Saja-Besaya

### Sitio web

https://observatoriosabe.es

### Correo electrónico

info@observatoriosabe.es

### Organismos públicos de los que depende

IHCantabria (Instituto de Hidráulica Ambiental)
Universidad de Cantabria (UniCan)

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

https://observatoriosabe.es/documentos

### Organismos que lo componen

Consejo Asesor:

> El Consejo Asesor está compuesto por Soledad Nogués, profesora titular de Urbanística y Ordenación del Territorio de la Universidad de Cantabria y Torrelaveguense ilustre 2016, Jesús Tortosa, Director General de la Cámara de Comercio de Cantabria, Leandro Morante, exdirector del CIMA de Torrelavega, Sonsoles Pérez, Jefa de seguridad, higiene, medio ambiente y calidad de Solvay, Felipe González, delegado en Cantabria de SEO Birdlife, y Fernando Isasi, Director gerente de la Red Cántabra de Desarrollo Rural.

Consejo Rector:

>  14 personas (6 de las entidades incorporadas, 6 del Consejo Asesor y 2 de la secretaría y dirección).

### Descripción

El Observatorio de la cuenca Saja-Besaya, denominado Observatorio SABE, es un órgano independiente, de carácter técnico y multidisciplinar, que trabaja por implementar mejoras en nuestros ecosistemas, paisajes, estuarios, zonas forestales o urbanas, entre otras.

### Fecha de inicio

1 de Junio del 2022

### En activo

Sí

**Comment by JaimeObregon** [comment]
¡Gracias! Lo añado manualmente, que hay demasiados conflictos de mezclado.
