### ISSUE TITLE
[NUEVO OBSERVATORIO] Observatorio de Salud en Asturias.

### ISSUE THREAD

**Issue by asturcillo** [JaimeObregon/observatoriospublicos.es#361]
### Nombre del observatorio (OBLIGATORIO)

OBSERVATORIO DE SALUD EN ASTURIAS (OBSA)

### Sitio web

https://obsaludasturias.com/obsa/

### Correo electrónico

obsalud@asturias.org

### Organismos públicos de los que depende

Dirección General de Salud Pública. Consejería de Sanidad. Gobierno del Principado de Asturias.

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

-Informe del efecto del cambio climático en la salud de la población asturiana. 2023
https://obsaludasturias.com/obsa/wp-content/uploads/INF-CAMBIO-CLIMATICO-ASTURIAS-2023b-1.pdf
–Plan de Salud del Principado de Asturias 2019-2030.
https://obsaludasturias.com/obsa/wp-content/uploads/Plan_Salud_Principado_Asturias_2019_2030_versi%C3%B3n-web_20193007.pdf
-Documentos técnicos sobre el proyecto de rankings geográficos 2016.
https://obsaludasturias.com/obsa/wp-content/uploads/Informe%20de%20los%20rankings%20por%20concejos%202016.pdf
-Informe de situación de salud en Asturias 2012-2015.
https://obsaludasturias.com/obsa/wp-content/uploads/ASSA2015-VFinal.pdf

### Organismos que lo componen

Dirección General de Salud Pública. Consejería de Sanidad. Gobierno del Principado de Asturias.
Supervisión: School of Public Health and Medicine de la Universidad de Wisconsin-Madison.

### Descripción

El Observatorio tratará de desarrollar tres líneas fundamentales: generar un espacio de conocimiento sobre la información en salud en Asturias a través de una serie de informes periódicos; garantizar que esta información llegue de la forma más comprensible al mayor número de agentes de salud posibles, destacando la importancia de un abordaje de los determinantes sociales de la salud y, finalmente, vincular la información en salud de los indicadores a las diferentes actuaciones comunitarias en salud que se están desarrollando en Asturias.

### Fecha de inicio

Mayo de 2011
Financiado a cargo de los "fondos para las estrategias 2010 del Ministerio de Sanidad y Política Social que fueron aprobados en el Consejo Interterritorial del Sistema Nacional de Salud de fecha 10 de febrero de 2010, como apoyo a la implementación a la estrategias de calidad”

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
