### ISSUE TITLE
[NUEVO OBSERVATORIO] Observatorio de Convivencia Escolar de Cantabria

### ISSUE THREAD

**Issue by JCGF-OSM** [JaimeObregon/observatoriospublicos.es#363]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Convivencia Escolar de Cantabria

### Sitio web

https://www.educantabria.es/diversidad/convivencia

### Organismos públicos de los que depende

Consejería de Educación, Formación Profesional y Universidades de Cantabria.

### Ámbito territorial

autonómico

### Tipo

publico

### Organismos que lo componen

Presidencia: (Consejero de Educación, Formación Profesional y Universidades)
Vicepresidencia (Directora General de Centros e Infraestructuras Educativas)
Secretario.
Vocales.

### Descripción

El Observatorio para la Convivencia Escolar de Cantabria es una organización colegiada de carácter consultivo que tiene como objetivo dotar a la administración educativa de las herramientas necesarias para la prevención y mejora del clima escolar en Cantabria.

### Fecha de inicio

13 de octubre de 2006

### En activo

Sí

**Comment by JaimeObregon** [comment]
¡Gracias! Lo añado manualmente, que hay demasiados conflictos de mezclado.
