### ISSUE TITLE
[NUEVO OBSERVATORIO] Observatorio Asturiano de Servicios Sociales.

### ISSUE THREAD

**Issue by asturcillo** [JaimeObregon/observatoriospublicos.es#365]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Asturiano de Servicios Sociales. (OBSERVASS)

### Sitio web

https://observass.com/

### Correo electrónico

Formulario Web

### Organismos públicos de los que depende

Consejería de Derechos Sociales y Bienestar. Gobierno del Principado de Asturias.

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

-INFORME | 17 DE ABRIL DE 2023

[Indicador Sintético de Resistencia a la Pobreza y la Exclusión Social]
(https://observass.com/wp-content/uploads/2023/04/Indicador-sint%C3%A9tico-resistencia-a-la-pobrezadef.pdf)

-ESTUDIO | 18 DE JUNIO DE 2021

[Previsión de Demanda de Cuidados Residenciales Para Personas Mayores en Asturias]
(https://observass.com/wp-content/uploads/2021/06/PREVISIO%CC%81N-DEMANDA-CUIDADOS-RESIDENCIALES-PERSONAS-MAYORES.pdf)

-INFORME | 5 DE ABRIL DE 2019

[Mujeres y Servicios Sociales. Asturias]
(https://observass.com/wp-content/uploads/2019/04/InfoObservASS-MUJERES-Y-SERVICIOS-SOCIALES-1.pdf)

-INFORME | 5 DE ABRIL DE 2019

[Anexo estadístico. Mujeres y Servicios Sociales. Asturias]
(https://observass.com/wp-content/uploads/2019/04/ANEXO-ESTADISTICO-INOBSERVASS-N3.xls)

### Organismos que lo componen

 Se organiza en un Consejo Rector y una Comisión Asesora cuya composición se detalla en el [Decreto 35/2017, de 31 de mayo, por el que se crea y se regula el Observatorio Asturiano de Servicios Sociales (OBSERVASS)], BOPA 132 de 9-vi-2017 (https://sede.asturias.es/bopa/2017/06/09/2017-06449.pdf)

### Descripción

Sistema de información que permita la adecuada dirección, planificación y evaluación de los servicios sociales.

La creación del Observatorio Asturiano de Servicios Sociales tiene la finalidad de:
-Aportar y analizar información que permita un mejor conocimiento de la situación de los servicios sociales del Principado de Asturias con el fin favorecer la toma de decisiones en el diseño y desarrollo de políticas sociales.
-Asesorar a la Dirección General con competencia en materia de planificación de servicios sociales en el ejercicio de sus funciones como unidad estadística.
-Facilitar la labor a profesionales del ámbito técnico y/o científico relacionados con los servicios sociales.
-Materializar el derecho que tiene la ciudadanía de acceso a la información que obra en poder de la Administración sobre los servicios que presta y de su impacto en la sociedad.

### Fecha de inicio

31/05/2017
[Decreto 35/2017, de 31 de mayo, por el que se crea y se regula el Observatorio Asturiano de Servicios Sociales (OBSERVASS)] BOPA 132 de 9-vi-2017 
(https://sede.asturias.es/bopa/2017/06/09/2017-06449.pdf)

### En activo

Sí

**Comment by JaimeObregon** [comment]
¡Gracias! Lo añado manualmente, que hay demasiados conflictos de mezclado.
