### ISSUE TITLE
[NUEVO OBSERVATORIO] Observatorio de la Publicidad e Información no Sexista.

### ISSUE THREAD

**Issue by asturcillo** [JaimeObregon/observatoriospublicos.es#367]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Publicidad e Información no Sexista del Principado de Asturias.

### Sitio web

https://iam.asturias.es/observatorio-de-la-publicidad-e-informacion-no-sexista

### Correo electrónico

institutoasturianodelamujer@asturias.org

### Organismos públicos de los que depende

Instituto Asturiano de la Mujer. Consejería de Presidencia, Reto Demográfico, Igualdad y Turismo. Gobierno del Principado de Asturias.

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

-Denuncias recibidas (2014-2023):
 https://iam.asturias.es/documents/269132/3354977/DENUNCIAS+PUBLICIDAD.pdf/3d615fff-1cfc-5817-b401-32c1e2d5b31f
- Díptico Observatorio:
 https://iam.asturias.es/documents/269132/3354977/DENUNCIAS+PUBLICIDAD.pdf/3d615fff-1cfc-5817-b401-32c1e2d5b31f

### Organismos que lo componen

Instituto Asturiano de la Mujer.

### Descripción

El Observatorio de la Publicidad e Información no Sexista nace para recoger todas aquellas quejas o denuncias que puedan atentar contra la imagen o dignidad de las mujeres en medios de comunicación y/o publicitarios.

### Fecha de inicio

2013

### En activo

Sí

**Comment by JaimeObregon** [comment]
¡Gracias! Lo añado manualmente, que hay demasiados conflictos de mezclado.
