### ISSUE TITLE
Convivencia escolar Andslucia

### ISSUE THREAD

**Issue by jjmedinaariza** [JaimeObregon/observatoriospublicos.es#38]
### Nombre del observatorio (OBLIGATORIO)

Observatorio para la Convivencia Escolar en Andalucía  

### Sitio web

https://www.juntadeandalucia.es/educacion/portals/web/convivencia-escolar/estructura-y-funcionamiento

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido :D
