### ISSUE TITLE
Observatorio de Agresiones a Profesionales del sistema sanitario público

### ISSUE THREAD

**Issue by jjmedinaariza** [JaimeObregon/observatoriospublicos.es#39]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Agresiones a Profesionales del sistema sanitario público

### Sitio web

https://www.sspa.juntadeandalucia.es/servicioandaluzdesalud/todas-noticia/constituido-el-observatorio-de-agresiones-profesionales-del-sistema-sanitario-publico

### Ámbito territorial

autonómico

### Tipo

publico

### Comentarios

Aún no han creado su propia pagina pero su constitución aparece mencionada en varias páginas oficiales de la Junta de Andalucía, arriba uno de las noticias al respecto 

### En activo

None

**Comment by JaimeObregon** [comment]
¡Añadido!
