### ISSUE TITLE
[NUEVO OBSERVATORIO] Observatorio Igualdad y Empleo

### ISSUE THREAD

**Issue by asturcillo** [JaimeObregon/observatoriospublicos.es#390]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Igualdad y Empleo

### Sitio web

https://www.observatorioigualdadyempleo.es/

### Organismos públicos de los que depende

- Unión Europea. Fondo Social Europeo – Programa Operativo de Inclusión Social y Economía.
- Gobierno de España Ministerio de Derechos Sociales y Agenda 2030.
- Gobierno de España. Ministerio de Igualdad.
- Gobierno de España. Ministerio de Trabajo y Economía Social.

### Ámbito territorial

estatal

### Tipo

mixto

### Informes publicados

-Resultados 2022 Eje 6 – Innovación Social:
https://www.observatorioigualdadyempleo.es/download/resultados-2022-eje-6-innovacion/

### Organismos que lo componen

Fundación Mujeres.

### Descripción

Acción de divulgación, análisis y sensibilización dirigido a mejorar el conocimiento sobre las desigualdades de género que se producen en el ámbito de empleo y emprendimiento y las claves para superarlas desde la corresponsabilidad de los distintos agentes que operan en el ámbito laboral.

### Fecha de inicio

2016

### En activo

Sí

**Comment by JaimeObregon** [comment]
Este ya lo tenemos.
