### ISSUE TITLE
Observatorio de palabras de la RAE

### ISSUE THREAD

**Issue by jlpscot** [JaimeObregon/observatoriospublicos.es#392]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de palabras

### Sitio web

https://www.rae.es/portal-linguistico/observatorio-de-palabras

### Organismos públicos de los que depende

RAE

### Ámbito territorial

estatal

### Tipo

publico

### En activo

Sí

**Comment by jlpscot** [comment]
Este observatorio podría ser una de las excepciones que confirmen la regla y ser, además de funcional, un lugar donde se ofrece información sobre palabras de nuevo uso, que aún no están en el diccionario y que en algún lugar han generado dudas (o eso dice la web del observatorio). __

**Comment by JaimeObregon** [comment]
Este no tiene cabida porque la RAE es una entidad privada (aunque reciba pasta pública… no va directamente a este observatorio).
