### ISSUE TITLE
[NUEVO OBSERVATORIO]

### ISSUE THREAD

**Issue by ubuntinux** [JaimeObregon/observatoriospublicos.es#40]
### Nombre del observatorio (OBLIGATORIO)

Observatori Agroalimentari de Preus

### Sitio web

https://agricultura.gencat.cat/ca/departament/estadistiques/observatori-agroalimentari-preus/

### Correo electrónico

estudis_prospectiva.daam@gencat.cat

### Organismos públicos de los que depende

Gencat

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido :)
