### ISSUE TITLE
Observatorio Vasco de la Cultura

### ISSUE THREAD

**Issue by tomatodressing** [JaimeObregon/observatoriospublicos.es#41]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Vasco de la Cultura

### Sitio web

https://www.euskadi.eus/observatorio-vasco-cultura/

### Correo electrónico

kulturabehatokia@euskadi.eus

### Organismos públicos de los que depende

Gobierno Vasco
Cultura y Política Lingüística
Viceconsejería de Cultura
Dirección de Promoción de la Cultura

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

Edición del libro en euskera 2022: 
https://www.euskadi.eus/2024/edicion-del-libro-en-euskera-2022/web01-a3kebarg/eu/

Comercio interior del libro en la CAE 2022: https://www.euskadi.eus/2024/comercio-interior-del-libro-en-la-cae-2022/web01-a3kebarg/eu/

Análisis de la programación cultural de la CAE. Año 2023: https://www.euskadi.eus/2023/analisis-de-la-programacion-cultural-de-la-cae-ano-2023/web01-a3kebarg/eu/

### Fecha de inicio

14/02/2006

### En activo

Sí

**Comment by JaimeObregon** [comment]
¡Añadido! :D
