### ISSUE TITLE
Observatorio I+D+i UPM

### ISSUE THREAD

**Issue by samujan92** [JaimeObregon/observatoriospublicos.es#415]
### Nombre del observatorio (OBLIGATORIO)

Observatorio I+D+i Universidad Politécnica de Madrid

### Sitio web

https://www.upm.es/observatorio/vi/index.jsp

### Organismos públicos de los que depende

Consejo Social UPM

### Ámbito territorial

estatal

### Tipo

publico

### Descripción

El Observatorio de I+d+I tiene como objetivo aunar toda la información de la actividad investigadora y de la innovación que se realiza en la universidad para que sea pública y accesible para la comunidad universitaria, el tejido empresarial y en general para cualquier usuario interesado en la producción científica que se realiza en la UPM y en los resultados generados.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
