### ISSUE TITLE
[NUEVO OBSERVATORIO]  Observatorio de Mujeres, Ciencia e Innovación

### ISSUE THREAD

**Issue by javigs** [JaimeObregon/observatoriospublicos.es#417]
### Nombre del observatorio (OBLIGATORIO)

 Observatorio de Mujeres, Ciencia e Innovación

### Sitio web

https://www.ciencia.gob.es/Secc-Servicios/Igualdad/OMCI.html

### Organismos públicos de los que depende

Gobierno de España

### Ámbito territorial

estatal

### Tipo

publico

### Descripción

El Observatorio de Mujeres, Ciencia e Innovación (OMCI) es un órgano colegiado interministerial que tiene la responsabilidad de analizar y realizar el seguimiento y medición de impactos sobre la situación de las mujeres en el ámbito de la investigación, el desarrollo y la innovación; así como fomentar, proponer, asesorar e impulsar la realización de políticas públicas y de actuaciones en dichos ámbitos para acabar con los obstáculos visibles e invisibles para una igualdad de género real y efectiva; y promover la mejora de la situación de las mujeres en el Sistema Español de Ciencia, Tecnología e Innovación.

### Fecha de inicio

23/11/2018

### En activo

None

**Comment by JaimeObregon** [comment]
Este ya le tenemos en el catálogo.
