### ISSUE TITLE
[NUEVO OBSERVATORIO] Observatorio contra la Violencia Doméstica y de Género del Consejo General del Poder Judicial

### ISSUE THREAD

**Issue by javigs** [JaimeObregon/observatoriospublicos.es#419]
### Nombre del observatorio (OBLIGATORIO)

Observatorio contra la Violencia Doméstica y de Género del Consejo General del Poder Judicial

### Sitio web

https://www.poderjudicial.es/cgpj/es/Temas/Violencia_domestica_y_de_genero/El_Observatorio_contra_la_violencia_domestica_y_de_genero

### Organismos públicos de los que depende

Consejo General del Poder Judicial (CGPJ)

### Ámbito territorial

estatal

### Tipo

publico

### Organismos que lo componen

- Consejo General del Poder Judicial
- Ministerio de Justicia
- Ministerio de Sanidad, Servicios Sociales e Igualdad
- Ministerio del Interior
- Fiscalía General del Estado
- CCAA con competencias transferidas en Justicia
- Consejo General de la Abogacía Española
- Consejo General de Procuradores de España

### Descripción

El Observatorio contra la Violencia Doméstica y de Género es un instrumento de análisis y de actuación que, en el ámbito de la Administración de la Justicia, promueve iniciativas y medidas dirigidas a erradicar el problema social de la violencia doméstica y de género.

### Fecha de inicio

26/09/2002

### En activo

None

**Comment by JaimeObregon** [comment]
Este ya le tenemos.
