### ISSUE TITLE
[OBSERVATORIO DE DERECHOS SOCIALES DE CANARIAS]

### ISSUE THREAD

**Issue by tomatodressing** [JaimeObregon/observatoriospublicos.es#443]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Derechos Sociales de Canarias

### Sitio web

https://odesocan.org/

### Correo electrónico

info@odesocan.org

### Organismos públicos de los que depende

Ministerio del Interior

ACUFADE

### Ámbito territorial

autonómico

### Tipo

mixto

### Informes publicados

EL ACTUAL NÚMERO DE HORAS TRABAJADAS EN EL SECTOR SERVICIO INCREMENTA LA INCIDENCIA EN TRASTORNOS LIGADOS A LA SALUD MENTAL EN CANARIAS.: https://odesocan.org/el-actual-numero-de-horas-trabajadas-en-el-sector-servicio-incrementa-la-incidencia-en-trastornos-ligados-a-la-salud-mental-en-canarias/

"CANARIAS, DE LAS QUE MÁS HORAS TRABAJA Y MAYOR RIESGO TIENE DE PÉRDIDA DE LA VIVIENDA POR IMPAGO": https://odesocan.org/canarias-de-las-que-mas-horas-trabaja-y-mayor-riesgo-tiene-de-perdida-de-la-vivienda-por-impago/

INFORME SOBRE LOS PRESUPUESTOS DE 2024: https://odesocan.org/informe-sobre-los-presupuestos-de-2024/

### Organismos que lo componen

Creado por ACUFADE- dependiente del Ministerio del Interior

Dividido en Equipo técnico y Patronato

### Descripción

"(...) colaborar con la sociedad canaria en la tarea fundamental de supervisar y evaluar el cumplimiento de los derechos sociales."

### Fecha de inicio

19 de octubre de 2023 o antes

### En activo

Sí

**Comment by tomatodressing** [comment]
La información que se aporta se encuantra en internet, y redes sociales oficiales del observatorio.

**Comment by JaimeObregon** [comment]
No veo el dinero público, al menos de manera directa. Acufade parece una entidad privada, según leo en su web. Colaboran entidades públicas con Acufade, pero no veo que financien directamente el observatorio. Por ello prefiero cerrarlo sin incorporar al catálogo. Pero si estoy equivocado, siéntete libre de reabrir y proporcionar los datos, y lo incorporamos. ¡Gracias!
