### ISSUE TITLE
Observatorio del Comercio 4.0

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#45]
### Nombre del observatorio (OBLIGATORIO)

Observatorio del Comercio 4.0

### Sitio web

https://comercio.gob.es/ComercioInterior/Observatorio/Paginas/default.aspx

### Correo electrónico

sgfomon.sscc@mincotur.es

### Organismos públicos de los que depende

Ministerio de Economía, Comercio y Empresa

### Ámbito territorial

estatal

### Tipo

publico

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido :)
