### ISSUE TITLE
Observatori esportiu de Mallorca

### ISSUE THREAD

**Issue by socrates24** [JaimeObregon/observatoriospublicos.es#450]
### Nombre del observatorio (OBLIGATORIO)

Observatori esportiu de Mallorca (observatorio deportivo de Mallorca) 

### Sitio web

https://esports.conselldemallorca.es/observatori-esportiu-de-mallorca

### Correo electrónico

esportbase@conselldemallorca.net

### Organismos públicos de los que depende

Consell de Mallorca

### Ámbito territorial

local

### Tipo

publico

### Informes publicados

Meorias de

### Descripción

El Observatorio Deportivo de Mallorca tiene el objetivo de fomentar una práctica deportiva responsable, unos hábitos saludables y la formación en torno a diferentes temas de actualidad deportiva.

Plan de asesoramiento: formación y orientación dirigida a clubs, asociaciones de madres y padres de alumnos, federaciones deportivas, entrenadores...
Els valors de l’esport: charlas impartidas por deportistas de alto nivel, que profundizan en los valores que aporta el ejercicio físico al desarrollo personal.

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido. ¡Gracias!
