### ISSUE TITLE
[EDITAR OBSERVATORIO]

### ISSUE THREAD

**Issue by Coiasg** [JaimeObregon/observatoriospublicos.es#452]
### Nombre del observatorio a editar (OBLIGATORIO)

Observatorio del trabajo del Servicio de Ocupación de las Islas Baleares

### Sitio web

https://www.caib.es/sites/observatorideltreball/es/portada-10648/

### Correo electrónico

otib@dgplaes.caib.es

### Organismos públicos de los que depende

Consejería de Empresa, Ocupación y Energía

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

Estadísticas mensuales Islas Baleares: incluye datos sobre: población empadronada, centros de trabajo por sectores económicos, afiliados de alta en la Seguridad Social por regímenes de actividad, contratos laborales por sector económico, grupo de nacionalidad y tipo de contrato y sexo; y demandantes de trabajo por situación (activos y parados), sector económico, grupo de nacionalidad, sexo y tramo de edad, nivel de estudios, duración de la situación, etc.

### Descripción

Tiene como finalidad gestionar la obtención y la recopilación de los principales datos sociolaborales de las Illes Balears y profundizar en el estudio y la investigación de las características del empleo y el paro, así como de todos los aspectos relacionados con el mercado laboral (coste de trabajo, accidentes laborales, conflictos, condiciones y calidad de vida laborales, formación profesional e inserción laboral, seguridad y higiene en el trabajo, etc.). funciones:

a) Recopilar datos relativos al área laboral, de empleo, de paro y de todos los aspectos relacionados con el mercado laboral.

b) Crear y gestionar una base de datos de interés laboral con los datos obtenidos.

c) Procesar la información obtenida en materia laboral para confeccionar estadísticas y, al mismo tiempo, evaluar los datos recopilados.

d) Elaborar informes, estudios y diagnósticos sociolaborales de evoluclón y de prospección del mercado de trabajo.

e) Establecer un sistema de información estadística actualizada de manera periódica que sirva para los diferentes territorios y agentes sociales de la comunidad autónoma de las Illes Balears.

f) Realizar estadísticas que se le encomienden en relación con los indicadores laborales.

g) Establecer acuerdos de colaboración entre la consejería competente en materia de trabajo y formación y otras adminsitraciones públicas, entidades públicas o privadas y agentes sociales y mantener la coordinación con los proveedores y demandantes de información.

h) Establecer criterios homogéneos y sistemáticos de registro y explotación de las diferentes bases de datos de las diversas direcciones generales de la consejería y del Servicio de Empleo de las Illes Balears, con la finalidad de unificar el sistema de información estadística y mejorar la eficiencia de recursos humanos y materiales, sin perjuicio de las prescripciones de la normativa vigente sobre la protección de datos de carácter personal.

i) Elaborar mapas en los que se detalle el análisis que fundamentan los planes de empleo territoriales.

j) Asesorar en el diseño y la evaluación de todos los estudios de mercado y/o investigaciones en cualquier ámbito de las competencias de la consejería o de las entidades autónomas que dependan de éstas.

### En activo

Sí

**Comment by JaimeObregon** [comment]
¡Editado! Gracias.
