### ISSUE TITLE
Observatorio de Hallazgos-Propuestas Evaluaciones

### ISSUE THREAD

**Issue by m6d2-social** [JaimeObregon/observatoriospublicos.es#453]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Hallazgos-Propuestas Evaluaciones

### Sitio web

https://www.airef.es/es/buscador-hallazgos/

### Organismos públicos de los que depende

AIREF (Autoridad Independiente de Responsabilidad Fiscal)
"Nuestra misión es garantizar el cumplimiento efectivo del principio de sostenibilidad financiera por las Administraciones Públicas"

### Ámbito territorial

estatal

### Tipo

publico

### Informes publicados

Informe sobre los Presupuestos Iniciales de las AAPP 2024

### Descripción

La Autoridad Independiente de Responsabilidad Fiscal (AIReF) tiene por objeto velar por la sostenibilidad de las finanzas públicas como vía para asegurar el crecimiento económico y el bienestar de la sociedad española a medio y largo plazo.

### Fecha de inicio

8 de marzo de 2023

### En activo

Sí

**Comment by m6d2-social** [comment]
A por otro.

**Comment by JaimeObregon** [comment]
:D
