### ISSUE TITLE
Observatorio de Precios y Cadena de Valor del Sector Agroalimentario de la Comunidad Autónoma de Extremadura

### ISSUE THREAD

**Issue by Javierus2024** [JaimeObregon/observatoriospublicos.es#455]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Precios y Cadena de Valor del Sector Agroalimentario de la Comunidad Autónoma de Extremadura

### Sitio web

https://agrobservex.juntaex.es/

### Correo electrónico

observatorio.precios.ext@tragsa.es

### Organismos públicos de los que depende

CONSEJERÍA DE AGRICULTURA, DESARROLLO RURAL, POBLACIÓN Y TERRITORIO

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

COSTES DE PRODUCCIÓN 2022 - Estudio de costes de producción de la uva
COSTES DE PRODUCCIÓN 2022 - Estudio de costes de producción del tabaco 
COSTES DE PRODUCCIÓN 2022 - Estudio de costes de producción del tomate
COSTES DE PRODUCCIÓN 2022 - Estudio de costes de producción de la ciruela y la cereza
COSTES DE PRODUCCIÓN 2021 - [...] sobre la campaña de 2021 de la producción de bovino para sacrificio.

### Fecha de inicio

[DECRETO 25/2023, de 29 de marzo, por el que se crea y regula el Observatorio de Precios y Cadena de Valor del Sector Agroalimentario de la Comunidad Autónoma de Extremadura.](http://doe.juntaex.es/eli/es-ex/d/2023/03/29/25)

### En activo

Sí

**Comment by JaimeObregon** [comment]
¡Incorporado!
