### ISSUE TITLE
Observatorio de la Nutrición y de Estudio de la Obesidad AESAN

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#46]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Nutrición y de Estudio de la Obesidad AESAN

### Sitio web

https://www.aesan.gob.es/AECOSAN/web/nutricion/seccion/observatorio.htm

### Organismos públicos de los que depende

Ministerio de Derechos Sociales, Consumo y Agenda 2030

### Ámbito territorial

estatal

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
¡Añadido!
