### ISSUE TITLE
OBSERVATORIO PARA EL ANÁLISIS Y VISIBILIDAD DE LA EXCLUSIÓN SOCIAL

### ISSUE THREAD

**Issue by flomo13** [JaimeObregon/observatoriospublicos.es#465]
### Nombre del observatorio (OBLIGATORIO)

OBSERVATORIO PARA EL ANÁLISIS Y VISIBILIDAD DE LA EXCLUSIÓN SOCIAL

### Sitio web

https://www.urjc.es/estudiar-en-la-urjc/vida-universitaria/4682-observatorio-para-el-analisis-y-visibilidad-de-la-exclusion-social

### Correo electrónico

observatorio.exclusion@urjc.es

### Organismos públicos de los que depende

Universidad Rey Juan Carlos

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

Líneas de investigación abiertas:

Personas LGTBI en situación de vulnerabilidad.
“Estudio sociológico de las personas LGTBI sin hogar en la Comunidad de Madrid”   https://faciam.org/wp-content/uploads/2019/04/Informe-LGTBI-sin-hogar-18-junio.pdf.

https://canal.uned.es/video/5d1de262a3eeb026438b4570?track_id=5d1de2aba3eeb096438b4567

https://orgullodepadres.com/

Sociología Jurídica y Trabajo Social Forense. http://trabajosocialforense.com/
" Construcción de escala de intensidad de violencia de género"
" Validez predictiva de la escala de intensidad de violencia de género" (EN CURSO)
Pobreza y desigualdad
“Sucesos Vitales Estresantes (SVE) en personas sin hogar. Elaboración de una escala de detección del riesgo de sinhogarismo como herramienta de prevención” (EN CURSO)

### Descripción

El Observatorio para el Análisis y Visibilidad de la Exclusión Social , nace con el propósito de investigar situaciones, procesos y estructuras de exclusión social, darles visibilidad con campañas de comunicación y crear proyectos de intervención para colaborar en su erradicación. Se materializa así, como una manifestación más de la responsabilidad social universitaria, el firme compromiso de la Universidad Rey Juan Carlos en apostar por la igualdad de todas las personas, así como en la generación de oportunidades vitales para ellas. Este Observatorio está formado por un grupo interdisciplinar de PDIs, liderados desde la Sociología (investigación social) y el Trabajo Social (intervención social) de esta Universidad. Por su parte, el Grupo IDEX, líder en comunicación social, será el socio externo que implementaría la estrategia de difusión y sensibilización de la realidad investigada, financiándose a través de RSC de empresas. Se une la Universidad y la sociedad civil en la mejora de la calidad de vida de las personas más vulnerables.

OBJETIVOS:

Investigar y analizar situaciones, procesos y estructuras de exclusión social.
Lanzar campañas mediáticas para sensibilizar a la sociedad en general, de las situaciones, procesos y estructuras de exclusión social previamente estudiadas.
Generar proyectos de intervención social para los fenómenos analizados.

### En activo

Sí

**Comment by JaimeObregon** [comment]
¡Añadido! :)
