### ISSUE TITLE
Observatorio de uso de medicamentos

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#47]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de uso de medicamentos

### Sitio web

https://www.aemps.gob.es/medicamentos-de-uso-humano/observatorio-de-uso-de-medicamentos/

### Organismos públicos de los que depende

Ministerio de Sanidad

### Ámbito territorial

estatal

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido :)
