### ISSUE TITLE
Observatorio de la Muerte Digna

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#48]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Muerte Digna

### Sitio web

http://www.nafarroa.gob.es/home_es/Temas/Portal+de+la+Salud/Ciudadania/Me+cuido/Al+final+de+la+vida/Observatorio+de+la+Muerte+Digna/

### Organismos públicos de los que depende

Gobierno de Navarra. Departamento de Salud

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido :D
