### ISSUE TITLE
Observatorio de Precios de los Alimentos

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#49]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Precios de los Alimentos

### Sitio web

https://www.mapa.gob.es/es/alimentacion/servicios/observatorio-de-precios-de-los-alimentos/estudios-e-informes/default.aspx

### Organismos públicos de los que depende

Ministerio de Agricultura, Pesca y Alimentación

### Ámbito territorial

estatal

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido :D
