### ISSUE TITLE
[NUEVO OBSERVATORIO] Observatorio de la Realidad Social de Navarra

### ISSUE THREAD

**Issue by jesus-asenjo** [JaimeObregon/observatoriospublicos.es#490]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Realidad Social de Navarra

### Sitio web

https://www.observatoriorealidadsocial.es/es/

### Organismos públicos de los que depende

- Gobierno de Navarra

### Ámbito territorial

estatal

### Tipo

publico

### Informes publicados

- Centro de documentación (recopilatorio)
- Otros documentos del Departamento de Derechos Sociales
- Bancos de datos socioeconómicos

### Descripción

Observatorio de la Realidad Social de Navarra se tiene como objetivo la investigación aplicada, la planificación y la evaluación de las políticas públicas de servicios sociales, empleo y vivienda, así como el análisis de los procesos de transformación social y de los problemas sociales en la Comunidad Foral de Navarra.

### Fecha de inicio

2018

### En activo

Sí

**Comment by JaimeObregon** [comment]
Este ya lo tenemos fichado.
