### ISSUE TITLE
[NUEVO OBSERVATORIO] OTALEX (2)

### ISSUE THREAD

**Issue by jesus-asenjo** [JaimeObregon/observatoriospublicos.es#494]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Territorial Alentejo Extremadura y Centro de Portugal (OTALEX)

### Sitio web

http://www.ideotalex.eu/

### Organismos públicos de los que depende

- Gobierno de Extremadura
- Diputación Provincial de Cáceres (Área de Desarrollo Local y Formación)

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

Boletines:
- [Boletín Informativo 6/2015](http://www.ideotalex.eu/OtalexC/Publicaciones/OTALEXC/news_otc_6.pdf)

Estudios:
- [Estudio de Accesibilidad Viaria del Área OTALEX C](http://www.ideotalex.eu/OtalexC/Publicaciones/OTALEXC/Estudio_Accesibilidad_Viaria_OTALEXC.pdf)
- [Estudio de Indicadores de Sostenibilidad del Área de OTALEX C](http://www.ideotalex.eu/OtalexC/Publicaciones/OTALEXC/Estudio_Ind_Sostenibilidad.pdf)
- [Estudio Socioeconómico OTALEX C](http://www.ideotalex.eu/OtalexC/Publicaciones/OTALEXC/Estudio_Socioeconomico_OTALEX_C.pdf)

### Organismos que lo componen

- Gobierno de Extremadura (Ordenación del Territorio)
- Diputación de Cáceres (Área de Desarrollo Local y Formación)
- Diputación de Badajoz
- Instituto Geográfico Nacional
- Comunidade Intermunicipal do Alentejo Central
- Comunidade Intermunicipal do Alto Alentejo
- Direção-Geral do Território (PT)
- Universidad de Extremadura
- Comissão de Coordenação e Desenvolvimento Regional do Alentejo
- Empresa de Desenvolvimento de Infra-estruturas do Alqueva, S.A
- Univerisdade de Évora
- Instituto Politécnico de Castelo Branco

### Descripción

OTALEX está financiado por el programa europeo INTERREGIII A y tiene marcado como objetivo estudiar y mostrar la realidad de un territorio, compuesto por las regiones del **Alentejo** en Portugal y **Extremadura** en España, separado convencionalmente por una frontera administrativa pero unido por sus características físicas, ambientales, sociales y económicas. Se trata de espacios rurales de baja densidad demográfica donde los recursos naturales, culturales y la calidad ambiental conforman sus atractivos fundamentales.

La IDE OTALEX es el resultado del esfuerzo, el compromiso y la colaboración entre instituciones a los dos lados de la frontera, con implicación de los tres niveles administrativos: Estatal, Regional y Local. Muestra los trabajos de homogeneización y estandarización de datos del territorio Alentejo-Extremeño, a través de clientes de visualización de mapas, consulta de topónimos y consulta de catálogo, dentro de las líneas de INSPIRE.

### Fecha de inicio

2006

### Cese de actividad

Junio 2015

### En activo

None

**Comment by JaimeObregon** [comment]
¡Gracias, @jesus-asenjo! Incorporado.
