### ISSUE TITLE
[NUEVO OBSERVATORIO] Observatorio Socioeconómico Provincial de la Diputación de Cáceres (2)

### ISSUE THREAD

**Issue by jesus-asenjo** [JaimeObregon/observatoriospublicos.es#496]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Socioeconómico Provincial de la Diputación de Cáceres

### Sitio web

http://observatorio.dip-caceres.es/

### Correo electrónico

observatorio@dip-caceres.es

### Organismos públicos de los que depende

- Diputación Provincial de Cáceres

### Ámbito territorial

provincial

### Tipo

publico

### Informes publicados

Enlaces:
- [Análisis del sector agroalimentario de la Provincia de Cáceres. Abril 2018](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20recientes/23-sector_agroalimentario.pdf)
- [Estudio de tendencias y oportunidades del emprendimiento - Completo. Abril 2017](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20recientes/12-Estudio_tendencias_oportunidades-completo.pdf)
- [Informe socioeconómico de la provincia de Cáceres. Abril 2015](http://observatorio.dip-caceres.es/Observatorio2/documentosPDF/Estudios%20recientes/11-INFORME_SOCIOECON%C3%93MICO_2015.pdf)

### Organismos que lo componen

- Diputación Provincial de Cáceres

### Descripción

El Observatorio Socioeconómico aporta la información necesaria para el diagnóstico a los procesos de planificación, facilitando indicadores de evolución socioeconómica al personal técnico que trabaja en desarrollo local.

### En activo

None

**Comment by JaimeObregon** [comment]
¡Gracias, @jesus-asenjo! Lo incorporo.
