### ISSUE TITLE
Observatorio Aragonés del Sector Automoción

### ISSUE THREAD

**Issue by danibaeyens** [JaimeObregon/observatoriospublicos.es#498]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Aragonés del Sector Automoción

### Sitio web

https://femz.es/femz-y-caar-presentan-el-observatorio-aragones-del-sector-automocion/

### Ámbito territorial

autonómico

### Tipo

mixto

### Organismos que lo componen

* Cluster de Automoción de Aragón (CAAR)
* Federación de Empresas del Metal de Zaragoza (FEMZ)

### Descripción

# Objetivos principales
 
* Visibilizar el sector de automoción aragonés y su ecosistema. 
* Dinamizarlo a través de la integración, el talento y la tecnología.
* Anteponerse los nuevos retos globales.
* Diseñar una estrategia a modo de hoja de ruta compartida.

### Fecha de inicio

7/6/2024

### En activo

Sí

**Comment by danibaeyens** [comment]
De muy reciente creación, no hay web ni email de contacto.
No hay listado en las notas de prensa de qué órganos (aparte de CAAR y FEMZ) conformarán definitivamente el observatorio.

**Comment by JaimeObregon** [comment]
¡Gracias, @danibaeyens! No veo dónde está la financiación pública, pues tanto CAAR como FEMZ parecen entidades privadas, así que me temo que voy a descartarlo y cerrar el _issue_. Pero siéntete libre de reabrirlo si ves que entra en juego el dinero público de alguna manera más o menos directa. Un abrazo.
