### ISSUE TITLE
Añadir observatorio? No se si aplica, creo que es de la onze

### ISSUE THREAD

**Issue by tintintino** [JaimeObregon/observatoriospublicos.es#508]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Estatal de la Soledad no Deseada

### Sitio web

https://www.soledades.es/

### Ámbito territorial

estatal

### Tipo

mixto

### En activo

Sí

**Comment by JaimeObregon** [comment]
No veo dónde está la financiación pública. Todo lo que leo es que es una iniciativa de la Fundación ONCE, que parece una entidad privada. Lo cierro, pero reábrelo si ves que el Observatorio tiene financiación pública.
