### ISSUE TITLE
Observatorio militar para la igualdad entre mujeres y hombres en las Fuerzas Armadas

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#51]
### Nombre del observatorio (OBLIGATORIO)

Observatorio militar para la igualdad entre mujeres y hombres en las Fuerzas Armadas

### Sitio web

https://www.defensa.gob.es/ministerio/organigrama/subdef/omi/

### Correo electrónico

omigualdad@oc.mde.es

### Organismos públicos de los que depende

Ministerio de Defensa

### Ámbito territorial

estatal

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
