### ISSUE TITLE
[NUEVO OBSERVATORIO]

### ISSUE THREAD

**Issue by berezuma** [JaimeObregon/observatoriospublicos.es#52]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Cadena Alimentaria y de la Madera de Euskadi

### Sitio web

https://behatoki.eus/

### Organismos públicos de los que depende

Gobierno Vasco
Hazi

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido :D
