### ISSUE TITLE
[NUEVO OBSERVATORIO] Observatorio de Cooperación para el Desarrollo, Ciudadanía Global y EpDCG (Zaragoza)

### ISSUE THREAD

**Issue by alan-garcia** [JaimeObregon/observatoriospublicos.es#522]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Cooperación para el Desarrollo, Ciudadanía Global y EpDCG

### Sitio web

https://ocatcodes.unizar.es/

### Correo electrónico

catcodes@unizar.es

### Organismos públicos de los que depende

- [Diputación Provincial de Zaragoza (DPZ)](http://www.dpz.es/)
- [Cátedra de Cooperación para el Desarrollo de la Universidad de Zaragoza (CATCODES)](http://catedradecooperacion.unizar.es/)

### Ámbito territorial

provincial

### Tipo

mixto

### Informes publicados

https://ocatcodes.unizar.es/evidencia-de-actividades-y-documentacion-convenio-dpz-catcodes-fas-2022/

### Organismos que lo componen

Entidades clave en el proceso:
- Diputación Provincial de Zaragoza (financiador)
- Universidad de Zaragoza:
   - Cátedra de Cooperación para el Desarrollo
   - Facultad de Educación
   - Facultad de las Ciencias Sociales y del Trabajo
- Federación Aragonesa de Solidaridad:
    - Comunidades:
        - Agentes e instituciones de la comunidad local de la provincia de Zaragoza
        - Comunidades educativas (profesorado, alumnado y familias)
        - Asociaciones civiles locales
        - Ciudadanía en general interesada en participar
        - Socios colaboradores (contrapartes) en el extranjero.

Comisión Mixta:
- Por la Diputación Provincial de Zaragoza
- Por la Universidad de Zaragoza
- Por la Federación Aragonesa de Solidaridad

Fuente: https://ocatcodes.unizar.es/organizacion/

### Descripción

Creado en 2016, está constituido por un grupo de trabajo cuya finalidad es el estudio, la investigación, la formación, la divulgación, la promoción y la elaboración de estrategias para la Cooperación para el Desarrollo y la Educación para la Ciudadanía Global en la provincia de Zaragoza.

Son fines del Observatorio:

- Estudiar, investigar y difundir la situación de la Cooperación para el Desarrollo y la Educación para la Ciudadanía Global en la provincia de Zaragoza.
- Crear un marco de reflexión y diálogo en torno a la Educación para la Ciudadanía Global en la provincia de Zaragoza.
- Proponer estrategias conjuntas para la Educación para la Ciudadanía Global en los ámbitos formal, no formal e informal.
- Está abierto a todas las personas y entidades públicas y privadas que puedan facilitar y participar en la consecución de sus fines.

### Fecha de inicio

2016

### En activo

Sí

**Comment by alan-garcia** [comment]
@JaimeObregon Puedes eliminar éste, ya he creado uno reciente.

**Comment by JaimeObregon** [comment]
Lo cierro entonces; gracias.
