### ISSUE TITLE
[NUEVO OBSERVATORIO] Observatorio Aragonés de Familia

### ISSUE THREAD

**Issue by alan-garcia** [JaimeObregon/observatoriospublicos.es#529]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Aragonés de Familia

### Sitio web

https://www.aragon.es/-/observatorio-aragones-de-familia

### Organismos públicos de los que depende

Gobierno de Aragón

### Ámbito territorial

autonómico

### Tipo

publico

### Organismos que lo componen

Gobierno de Aragón

### Descripción

Órgano colegiado de carácter consultivo y de impulso al desarrollo de las políticas del Gobierno de Aragón de apoyo a las familias.

Objetivos
- Conocer, desde una perspectiva multisectorial, la situación, calidad de vida y demandas de las familias en Aragón.
- Asesorar y realizar el seguimiento de la incidencia que sobre las familias aragonesas tienen las políticas públicas.
- Promover mejoras sociales, económicas y legislativas que redunden en beneficio y apoyo de las familias aragonesas.
- Estimular la investigación y el conocimiento de la realidad socio-económica de las familias en Aragón.

### Fecha de inicio

2004

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado; gracias.
