### ISSUE TITLE
Observatorio de Salud Pública de Navarra

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#53]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Salud Pública de Navarra

### Sitio web

https://portalsalud.navarra.es/es/observatorio

### Correo electrónico

oscn@navarra.es

### Organismos públicos de los que depende

Gobierno de Navarra. Departamento de Salud

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
