### ISSUE TITLE
[NUEVO OBSERVATORIO] Observatorio de Costes del transporte por carretera de Aragón

### ISSUE THREAD

**Issue by alan-garcia** [JaimeObregon/observatoriospublicos.es#531]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Costes del transporte por carretera

### Sitio web

https://www.aragon.es/-/observatorio-de-costes

### Organismos públicos de los que depende

Ministerio de Fomento

### Ámbito territorial

autonómico

### Tipo

publico

### Organismos que lo componen

Ministerio de Fomento

### Descripción

El simulador de costes es una herramienta que complementa y añade valor al Observatorio de Costes del Transporte Discrecional de Viajeros por Carretera en Aragón.

Se trata de una aplicación interactiva que ha sido diseñada para calcular el coste de un servicio de manera sencilla e intuitiva. En su concepción se han tenido especialmente en cuenta las necesidades de las pequeñas empresas para identificar sus costes, proporcionándoles información acerca de la composición de los mismos.

Para ello, los usuarios deben suministrar al simulador los siguientes datos:

- Provincia a la que pertenece la empresa.
- Tipo de vehículo a utilizar.
- Número de kilómetros del servicio a realizar.
- Unidad de tiempo en que se valora: horas o días.
- Número de horas o días del servicio a realizar.

La aplicación calculará el coste total del servicio y efectuará una distribución de costes por partidas o centros de coste, tanto en euros como en porcentaje sobre el coste total. Además se obtendrá un gráfico circular en tres dimensiones que facilitará una interpretación intuitiva de los datos obtenidos.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Me entran dudas. El enlace es una página web del Gobierno de Aragón que cita un tal «Observatorio de Costes del Transporte Discrecional de Viajeros por Carretera en Aragón», del que no encuentro más información. Y que a su vez enlaza a dos páginas del Ministerio, que no funcionan. Voy a descartarlo porque no hay datos suficientes de que sea un observatorio funcional.
