### ISSUE TITLE
Nuevo observatorio

### ISSUE THREAD

**Issue by pablostarter** [JaimeObregon/observatoriospublicos.es#534]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de tendencias de mercamadrid

### Sitio web

https://www.mercamadrid.es/observatorio-tendencias-hosteleria/

### Organismos públicos de los que depende

Mercamadrid que dependen del ayuntamiento de madrid

### Ámbito territorial

local

### Tipo

publico

### Cese de actividad

Este tuit es de hace diez horas https://x.com/Mercasa_mercas/status/1830508788413051179

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias!
