### ISSUE TITLE
[NUEVO OBSERVATORIO] OBSERVATORIO ARAGONÉS DE LA SOLEDAD

### ISSUE THREAD

**Issue by astrosinfinitos** [JaimeObregon/observatoriospublicos.es#536]
### Nombre del observatorio (OBLIGATORIO)

Observatorio aragonés de la soledad

### Sitio web

https://eljusticiadearagon.es/oas/

### Correo electrónico

stroncio198@gmail.com

### Organismos públicos de los que depende

Depende del organismo publico de justicia de Aragón y del departamento de ciudadania y derechos sociales del gobierno de Aragón.

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

Hay diversos informes de este observatorio desde el año 1988 hasta el año 2023. Se pueden consultar en https://eljusticiadearagon.es/informes-anuales/

### Organismos que lo componen

El observatorio aragonés de la soledad está compuesto por los siguientes organismos:

Gobierno de Aragón
Federación aragonesa de municipios, comarcas y provincias
Ayuntamiento de Zaragoza.
Consejo aragonés de personas mayores.
Colegio profesional de trabajo social en Aragón.

### Descripción

La función del observatorio es la investigación, análisis y desarrollo de soluciones para abordar el problema de la soledad en la región de Aragón.

### Fecha de inicio

El observatorio comenzó a funcionar en septiembre del 2020

### Cese de actividad

Actualmente sigue activo

### En activo

Sí

**Comment by astrosinfinitos** [comment]
Buenas tardes, Jaime.

Creo que he encontrado un observatorio que no está listado dentro de la web de observatorios públicos que has creado. El observatorio en cuestión es el observatorio aragonés de la soledad, el cual tiene la siguiente web:

https://eljusticiadearagon.es/oas/#

Lo he buscado dentro de tu web, pero no lo he encontrado, así que te he enviado esta issue dentro de GitHub para que le eches un vistazo en cuanto tengas ocasión.

Muchas gracias por tu labor,

Un saludo.

**Comment by JaimeObregon** [comment]
Gracias, @astrosinfinitos. Incorporado. Aunque voy a quitar la dirección `stroncio198@gmail.com` porque no la veo en el sitio web y no parece la institucional de contacto.
