### ISSUE TITLE
[NUEVO OBSERVATORIO]

### ISSUE THREAD

**Issue by guaridadelmacho** [JaimeObregon/observatoriospublicos.es#538]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Vida Militar

### Sitio web

https://www.observatoriodelavidamilitar.es/

### Correo electrónico

info@observatoriodelavidamilitar.es

### Organismos públicos de los que depende

Cortes Generales

### Ámbito territorial

estatal

### Tipo

publico

### Informes publicados

https://publicaciones.defensa.gob.es/media/downloadable/files/links/m/e/memoria_informe_observatorio_vida_militar_2022.pdf

### Organismos que lo componen

Se compone de nueve personalidades de reconocido prestigio en el ámbito de la Defensa, recursos humanos o en derechos fundamentales y libertades públicas, elegidos cinco por el Congreso y cuatro por el Senado para un mandato de cinco años.

### Descripción

a) Efectuar análisis y propuestas de actuación sobre el ejercicio de los derechos fundamentales y libertades públicas por los miembros de las Fuerzas Armadas.
b) Elaborar, de oficio o a petición de parte, informes y estudios sobre el régimen de personal y las condiciones de vida en las Fuerzas Armadas.
c) Proponer medidas que ayuden a la conciliación de la vida profesional, personal y familiar de los militares.
d) Promover la adaptación del régimen del personal militar a los cambios que se operen en la sociedad y en la función pública.
e) Analizar los problemas que en el entorno familiar de los afectados se producen como consecuencia de su disponibilidad, movilidad geográfica y de su específico ejercicio profesional que conlleva la participación en operaciones en el exterior.
f) Evaluar la aportación adicional de recursos humanos a las Fuerzas Armadas a través de las diferentes modalidades de reservistas.
g) Velar por la aplicación a los militares retirados de la normativa que ampara sus derechos pasivos y asistenciales y, en su caso, efectuar propuestas de mejora sobre ésta.

### Fecha de inicio

El Observatorio se constituyó el 14 de enero de 2014.

### En activo

Sí

**Comment by JaimeObregon** [comment]
Incorporado. ¡Gracias! :)
