### ISSUE TITLE
Observatorio Aragonés de la Sociedad de la Información (OASI)

### ISSUE THREAD

**Issue by caryub** [JaimeObregon/observatoriospublicos.es#54]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Aragonés de la Sociedad de la Información (OASI)

### Sitio web

https://www.aragon.es/-/estudios-1

### Correo electrónico

oasi@aragon.es

### Organismos públicos de los que depende

Gobierno de Aragón 

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
