### ISSUE TITLE
[NUEVO OBSERVATORIO] Oficina Española de Delitos Informáticos

### ISSUE THREAD

**Issue by nacholopex** [JaimeObregon/observatoriospublicos.es#540]
### Nombre del observatorio (OBLIGATORIO)

Oficina Española de Delitos Informáticos

### Sitio web

https://oedi.es/

### Correo electrónico

oedi@oedi.es

### Organismos públicos de los que depende

Ministerio del Interior

### Ámbito territorial

estatal

### Tipo

publico

### Informes publicados

https://oedi.es/wp-content/uploads/2021/05/20211125-elche.pdf

### En activo

None

**Comment by JaimeObregon** [comment]
Lo cierro porque no veo por ningún que dependa del Ministerio del Interior, ni que sea un observatorio público o público-privado. El aviso legal dice que tiene domicilio social en un apartado de correos de Alicante. Y que está registrado en el Ministerio del Interior, pero esto último es un registro de asociaciones privadas del Ministerio, hasta donde yo sé. No implica que haya dinero público en la financiación de este observatorio.
