### ISSUE TITLE
[NUEVO OBSERVATORIO]

### ISSUE THREAD

**Issue by robertgc** [JaimeObregon/observatoriospublicos.es#542]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Criminalidad Organizada Transnacional

### Sitio web

https://ocot.usal.es

### Correo electrónico

crimtrans@usal.es

### Ámbito territorial

estatal

### Tipo

publico

### Descripción

El Observatorio de la Criminalidad Organizada Transnacional (OCOT) es un espacio interdisciplinario, crítico, reflexivo y de formación-acción que congrega una amplia red internacional de profesores e investigadores dedicados al estudio de la criminalidad organizada de modo pormenorizado. Es, además, un ambiente de alto nivel académico-científico y creciente reconocimiento nacional e internacional en la materia, especialmente dado su carácter pionero en el modo con el que aborda la temática estudiada, la calificada producción científica que impulsa, los distintos proyectos de investigación con financiación nacional que le dan cuerpo y la responsabilidad social que caracterizan sus acciones y reflexiones.

### En activo

Sí

**Comment by JaimeObregon** [comment]
¡Incorporado! Gracias. Un abrazo.

**Comment by robertgc** [comment]
> ¡Incorporado! Gracias. Un abrazo.

Gracias a ti por todo lo que haces
