### ISSUE TITLE
Observatorio de Infección en Cirugía

### ISSUE THREAD

**Issue by rmicharet** [JaimeObregon/observatoriospublicos.es#544]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Infección en Cirugía

### Sitio web

https://oincir.org/

### Ámbito territorial

estatal

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Hola. Lo cierro porque no veo que sea un observatorio público o público-privado. Este parece una iniciativa privada de la Asociación Española de Cirujanos.
