### ISSUE TITLE
Observatorio Fiscal de la Comunitat Valenciana

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#55]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Fiscal de la Comunitat Valenciana

### Sitio web

https://atv.gva.es/es/observatori-fiscal

### Organismos públicos de los que depende

Agència Tributària Valenciana

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
