### ISSUE TITLE
Observatorio del Hábitat y Segregación Urbana de la Comunitat Valenciana

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#57]
### Nombre del observatorio (OBLIGATORIO)

Observatorio del Hábitat y Segregación Urbana de la Comunitat Valenciana

### Sitio web

https://habitatge.gva.es/es/web/vivienda-y-calidad-en-la-edificacion/observatori-de-l-habitat-i-segregacio-urbana-de-la-cv

### Organismos públicos de los que depende

Generalitat Valenciana. Consellería de Servicios Sociales, Igualdad y Vivienda

### Ámbito territorial

estatal

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
