### ISSUE TITLE
Observatorio de la escuela rural de Aragón

### ISSUE THREAD

**Issue by caryub** [JaimeObregon/observatoriospublicos.es#58]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la escuela rural de Aragón

### Sitio web

https://educa.aragon.es/-/innovacion/observatorio-rural

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
