### ISSUE TITLE
Observatorio Valenciano del Trabajo Decente

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#59]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Valenciano del Trabajo Decente

### Sitio web

https://ceice.gva.es/va/web/dg-trabajo/observatori-valencia-del-treball-decent

### Organismos públicos de los que depende

Generalitat Valenciana. Consellería de Educación, Universidades y Ocupación

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
