### ISSUE TITLE
Observatorio de precios de la Comunitat Valenciana

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#60]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de precios de la Comunitat Valenciana

### Sitio web

https://argos.gva.es/es/web/prospectiva/observatori

### Organismos públicos de los que depende

Generalitat Valenciana

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
