### ISSUE TITLE
Observatorio Valenciano de la Cultura

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#61]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Valenciano de la Cultura

### Sitio web

https://ovc.gva.es/es/observatori

### Organismos públicos de los que depende

Generalitat Valenciana. Consellería de Cultura y Deporte

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
