### ISSUE TITLE
Observatorio de Brecha Digital

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#62]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Brecha Digital

### Sitio web

https://brechadigital.gva.es/es

### Organismos públicos de los que depende

Generalitat Valenciana. Consellería de Innovación, Industria, Comercio y Turismo

### Ámbito territorial

estatal

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
