### ISSUE TITLE
Observatorio para la Convivencia Escolar

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#63]
### Nombre del observatorio (OBLIGATORIO)

Observatorio para la Convivencia Escolar

### Sitio web

https://ceice.gva.es/es/web/inclusioeducativa/observatori-per-a-la-convivencia

### Organismos públicos de los que depende

Generalitat Valenciana. Conselleria de Educación, Universidades y Empleo

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
