### ISSUE TITLE
Observatorio valenciano para la igualdad de trato, la no discriminación y la prevención de los delitos de odio.

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#64]
### Nombre del observatorio (OBLIGATORIO)

Observatorio valenciano para la igualdad de trato, la no discriminación y la prevención de los delitos de odio.

### Sitio web

https://inclusio.gva.es/es/web/igualdad-diversidad/observatori-valencia-per-a-la-igualtat-de-trace-la-no-discriminacio-i-la-prevencio-dels-delictes-d-odi

### Organismos públicos de los que depende

Generalitat Valenciana. Conselleria de Servicios Sociales, Igualdad y Vivienda

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
