### ISSUE TITLE
Observatorio de la IA

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#65]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la IA

### Sitio web

https://observatorioia.gva.es/es/

### Organismos públicos de los que depende

Generalitat Valenciana. Conselleria de Innovación, Industria, Comercio y Turismo

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
