### ISSUE TITLE
Observatorio normativa electoral valenciana

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#66]
### Nombre del observatorio (OBLIGATORIO)

Observatorio normativa electoral valenciana

### Sitio web

https://cjusticia.gva.es/es/web/processos-electorals/observatori-electoral

### Organismos públicos de los que depende

Generalitat Valenciana. Conselleria de Justicia e Interior

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
