### ISSUE TITLE
Observatorio de la Industria y de los sectores económicos valencianos

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#67]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Industria y de los sectores económicos valencianos

### Sitio web

https://portalindustria.gva.es/es/observatorio-de-la-industria

### Organismos públicos de los que depende

Generalitat Valenciana. Conselleria de Innovación, Industria, Comercio y Turismo

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
