### ISSUE TITLE
Observatorio Ciudadano del Agua de la Comunidad Valenciana

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#68]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Ciudadano del Agua de la Comunidad Valenciana

### Sitio web

https://mediambient.gva.es/es/web/agua/novedades/-/asset_publisher/cYq5fnvdHYwT/content/observatorio-ciudadano-del-agua-de-la-comunitat-valenciana

### Organismos públicos de los que depende

Generalitat Valenciana. Conselleria de Medio Ambiente, Agua, Infraestructuras y Territorio

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
