### ISSUE TITLE
Observatorio de resultados del Servicio Madrileño de Salud

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#69]
### Nombre del observatorio (OBLIGATORIO)

https://www.comunidad.madrid/servicios/salud/observatorio-resultados-servicio-madrileno-salud

### Sitio web

https://www.comunidad.madrid/servicios/salud/observatorio-resultados-servicio-madrileno-salud

### Organismos públicos de los que depende

Comunidad de Madrid. Consejería de Sanidad

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
