### ISSUE TITLE
Observatorio de la Comunidad de Madrid de Víctimas del Delito

### ISSUE THREAD

**Issue by d78l** [JaimeObregon/observatoriospublicos.es#70]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de la Comunidad de Madrid de Víctimas del Delito

### Sitio web

https://www.comunidad.madrid/transparencia/unidad-organizativa-responsable/observatorio-comunidad-madrid-victimas-del-delito

### Organismos públicos de los que depende

Comunidad de Madrid. Consejería de Presidencia, Justicia y Administración Local

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
