### ISSUE TITLE
[NUEVO OBSERVATORIO]

### ISSUE THREAD

**Issue by rrroig** [JaimeObregon/observatoriospublicos.es#71]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Socioeconómico de la Marina Alta

### Sitio web

https://observatorimarinaalta.org/

### Correo electrónico

observatori@creama.org

### Organismos públicos de los que depende

Creama (Consorcio para la Recuperación Económica
y de la Actividad de la Marina Alta, Ayuntamiento de Dénia y otros municipios de la comarca, Generalitat Valenciana, Ministerio de Trabajo y Economía Social

### Ámbito territorial

local

### Tipo

mixto

### Fecha de inicio

2018

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
