### ISSUE TITLE
Observatori de la Mort

### ISSUE THREAD

**Issue by marc-sola** [JaimeObregon/observatoriospublicos.es#72]
### Nombre del observatorio (OBLIGATORIO)

Observatori de la Mort

### Sitio web

https://observatorisalut.gencat.cat/ca/observatori_mort/index.html

### Organismos públicos de los que depende

- Agència de Qualitat i Avaluació Sanitàries de Catalunya (AQuAS)

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

Listado de documentos publicados: [Documentos e informes](https://observatorisalut.gencat.cat/ca/observatori_mort/bibliografia_recomanada_obseravtori_mort/)

### Fecha de inicio

3 de Septiembre de 2019

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
