### ISSUE TITLE
[EDITAR OBSERVATORIO] Añadir Web al "Observatorio de Precios y Mercados de la Junta de Andalucía"

### ISSUE THREAD

**Issue by fcasarramona** [JaimeObregon/observatoriospublicos.es#73]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Precios y Mercados de la Junta de Andalucía

### Sitio web

https://www.juntadeandalucia.es/agriculturaypesca/observatorio

### Organismos públicos de los que depende

Consejeria de Agricultura y Pesca de la Junta de Andalucia

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

Informes de precios agrícolas y ganaderos

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
