### ISSUE TITLE
Observatorio Canario de Empleo

### ISSUE THREAD

**Issue by afeblesc** [JaimeObregon/observatoriospublicos.es#74]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Canario de Empleo

### Sitio web

https://obecan.es/

### Correo electrónico

info@obecan.es

### Organismos públicos de los que depende

Gobierno de Canarias - Consejería de empleo y asuntos sociales

### Ámbito territorial

autonómico

### Tipo

publico

### Comentarios

Decreto que anuncia su creación

https://www.gobiernodecanarias.org/boc/1998/160/003.html

### Fecha de inicio

Diciembre 1998

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
