### ISSUE TITLE
Observatorio de residuos de Bizkaia

### ISSUE THREAD

**Issue by oianer** [JaimeObregon/observatoriospublicos.es#75]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de residuos de Bizkaia

### Sitio web

https://bizkaikohirihondakinenbehatokia.com/es/observatorio-de-residuos/

### Organismos públicos de los que depende

Garbiker, empresa pública 100% perteneciente a la Diputación Foral de Bizkaia y adscrita al Departamento de Medio Natural y Agricultura.

### Ámbito territorial

provincial

### Tipo

publico

### Informes publicados

Informe Anual del Observatorio de Residuos de Bizkaia 2022
En teoría, hay histórico hasta 2010: https://bizkaikohirihondakinenbehatokia.com/es/en-numeros/#historico

### Fecha de inicio

2011

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
