### ISSUE TITLE
Observatorio Canario de la Juventud

### ISSUE THREAD

**Issue by afeblesc** [JaimeObregon/observatoriospublicos.es#76]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Canario de la Juventud

### Sitio web

https://www.gobiernodecanarias.org/juventud/programas/observatorio-canario-de-la-juventud/

### Organismos públicos de los que depende

Gobierno de Canarias - Dirección general de juventud

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

[El último informe es de 2013](http://www.injuve.es/observatorio/formacion-empleo-y-vivienda/estudio-consecuencias-economicas-covid-19-en-la-juventud)

https://www.gobiernodecanarias.org/cmsgobcan/export/sites/juventud/multimedia/documentos/Juventud_y_crisis_en_Canarias_v_impresion.pdf

https://www.gobiernodecanarias.org/cmsgobcan/export/sites/juventud/multimedia/documentos/programas/publicaciones/encuesta_jovenes_canarias_2012/ejc2012_diagnostico_juventud_canarias_2012_completo_13feb.pdf

### Comentarios

Se entremezcla con la dirección general de juventud. No tiene un correo propio sino que remite a la dirección general

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
