### ISSUE TITLE
[NUEVO OBSERVATORIO

### ISSUE THREAD

**Issue by jorjorbin77** [JaimeObregon/observatoriospublicos.es#77]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Aragonés del Arte en la Esfera Pública

### Sitio web

https://oaaep.unizar.es/

### Organismos públicos de los que depende

Universidad de Zaragoza

### Ámbito territorial

estatal

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
