### ISSUE TITLE
[NUEVO OBSERVATORIO]

### ISSUE THREAD

**Issue by jorjorbin77** [JaimeObregon/observatoriospublicos.es#78]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Aragonés por la convivencia y contra el acoso escolar

### Sitio web

https://educa.aragon.es/-/convivencia-web-basico-enlaces

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
