### ISSUE TITLE
Observatorio Regional de la Violencia de Género de la Comunidad de Madrid

### ISSUE THREAD

**Issue by jcm14** [JaimeObregon/observatoriospublicos.es#79]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Regional de la Violencia de Género

### Sitio web

https://www.comunidad.madrid/transparencia/unidad-organizativa-responsable/observatorio-regional-violencia-genero

### Organismos públicos de los que depende

Consejería de Presidencia, justicia y Administración Local

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
