### ISSUE TITLE
Varios observatorios del Gobierno Vasco

### ISSUE THREAD

**Issue by smendig** [JaimeObregon/observatoriospublicos.es#8]
- **Observatorio de Comercio del Gobierno Vasco**: https://www.euskadi.eus/gobierno-vasco/observatorio-comercio

- **Observatorio Vasco del Emprendimiento**: https://eeb-ove.eus/inicio/ | Twitter: @eeb_ove

- **Observatorio Vasco de Vivienda**: https://www.euskadi.eus/observatoriovivienda/

- **Observatorio Vasco del Juego**: https://www.euskadi.eus/gobierno-vasco/observatorio-vasco-juego/

- **Observatorio de Periodismo Machista**: https://periodismomachista.com/ | Twitter: @pemachista

- **Observatorio Vasco sobre Acoso y Discriminación**: https://www.observatoriovascosobreacoso.com/ | Twitter: @ObservVascoAcos

- **Observatorio Vasco de la Juventud - Gobierno Vasco**: https://www.gazteaukera.euskadi.eus/hasiera/ | Twitter: @gaztebehatokia
- **Observatorio de Coyuntura Industrial**: https://www.irekia.euskadi.eus/es/tags/observatoriodecoyunturaindustrial?uid=5196
- **Observatorio Vasco de Inmigración**: https://www.ikuspegi.eus/ | Twitter: @ikuspegi_eus
- **Observatorio Vasco LGTBI+**: https://lgtbi-behatokia.eus/ | Twitter: @BehatokiaLGTBI

**Comment by smendig** [comment]
https://github.com/JaimeObregon/observatoriospublicos.es/pull/10

**Comment by JaimeObregon** [comment]
PR mezclada. ¡Buen trabajo, amigo! 👍
