### ISSUE TITLE
[NUEVO OBSERVATORIO]

### ISSUE THREAD

**Issue by jorjorbin77** [JaimeObregon/observatoriospublicos.es#80]
### Nombre del observatorio (OBLIGATORIO)

Observatorio Aragonés de Dinamización Demográfica y Poblacional

### Sitio web

https://observatoriopoblacion.aragon.es/

### Ámbito territorial

autonómico

### Tipo

publico

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
