### ISSUE TITLE
OBSERVATORIO PRECIOS CADENA AGROALIMENTARIA CASTILLA LA MANCHA

### ISSUE THREAD

**Issue by Eredoper** [JaimeObregon/observatoriospublicos.es#82]
### Nombre del observatorio (OBLIGATORIO)

OBSERVATORIO PRECIOS CADENA AGROALIMENTARIA CASTILLA LA MANCHA

### Sitio web

https://www.castillalamancha.es/gobierno/agriaguaydesrur/estructura/dgalimentacion/titular/observatorio-precios-cadena-agroalimentaria

### Correo electrónico

observatoriocadena@jccm.es

### Organismos públicos de los que depende

Consejería de agricultura y ganadería de castilla la mancha

### Ámbito territorial

autonómico

### Tipo

publico

### Comentarios

No he sido capaz de encontrar ningún informe, te dejo por aqui la información que he podido encontrar. 

https://www.castillalamancha.es/actualidad/notasdeprensa/echa-andar-el-observatorio-de-precios-de-la-cadena-agroalimentaria-de-la-regi%C3%B3n-con-el-que-se

https://x.com/AgriculturaClm/status/1489578218722148357?s=20

https://www.castillalamancha.es/gobierno/agriaguaydesrur/estructura/dgalimentacion/titular/observatorio-precios-cadena-agroalimentaria

### Fecha de inicio

Decreto 94/2021, de 21 de septiembre, por el que se crea el Observatorio de Precios de la Cadena Agroalimentaria de Castilla-La Mancha. (D.O.C.M nº 186 de 27 de septiembre de 2021) 

**https://docm.jccm.es/portaldocm/descargarArchivo.do?ruta=2021/09/27/pdf/2021_10496.pdf&tipo=rutaDocm**

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
