### ISSUE TITLE
add: Observatorio de Seguridad y Eficiencia de las Operaciones Aéreas

### ISSUE THREAD

**Issue by lm-sanchez** [JaimeObregon/observatoriospublicos.es#83]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Seguridad y Eficiencia de las Operaciones Aéreas

### Sitio web

https://www.google.com/search?q=Observatorio+de+Seguridad+y+Eficiencia+de+las+Operaciones+A%C3%A9reas

### Organismos públicos de los que depende

- **ENAIRE** - https://www.enaire.es

### Ámbito territorial

estatal

### Tipo

publico

### Organismos que lo componen

- **ENAIRE**
- **COPAC** - Colegio Oficial de Pilotos de la Aviación Comercial

### Fecha de inicio

2 de julio de 2019

### En activo

None

**Comment by JaimeObregon** [comment]
Añadido.
