### ISSUE TITLE
Observatorio de Accesibilidad de Euskadi

### ISSUE THREAD

**Issue by igor-dg** [JaimeObregon/observatoriospublicos.es#95]
### Nombre del observatorio (OBLIGATORIO)

Observatorio de Accesibilidad de Euskadi

### Sitio web

https://isek.euskadi.eus/webisek00-isekquees/es/

### Correo electrónico

accesibilidad@euskadi.eus

### Organismos públicos de los que depende

- Gobierno Vasco
- Departamento de Planificación Territorial, Vivienda y Transportes
- Dirección de Vivienda, Suelo y Arquitectónica

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

[I PLAN DE ACCIÓN DE LA ESTRATEGIA DE ACCESIBILIDAD UNIVERSAL DE EUSKADI Informe anual de Evaluación 2022](https://isek.euskadi.eus/media/informes/webisek00-Informe-Evaluacion-2022-Plan-de-Accion-Accesibilidad.pdf)

### Descripción

El Observatorio de la Accesibilidad de Euskadi es una herramienta para centralizar la información sobre accesibilidad en el País Vasco y que esté a disposición de todas las personas interesadas.

### Fecha de inicio

[21 de julio de 2021](https://www.irekia.euskadi.eus/es/news/70861-euskadi-contara-con-observatorio-accesibilidad-para-obtener-imagen-real-este-derecho-comunidad-autonoma)

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
