### ISSUE TITLE
[NUEVO OBSERVATORIO]

### ISSUE THREAD

**Issue by Spurgus** [JaimeObregon/observatoriospublicos.es#98]
### Nombre del observatorio (OBLIGATORIO)

De la realidad social de Navarra / análisis y prospección de la realidad de Navarra

### Sitio web

https://www.observatoriorealidadsocial.es/es/estudios/

### Organismos públicos de los que depende

Servicios sociales , empleo y vivienda

### Ámbito territorial

autonómico

### Tipo

publico

### Informes publicados

https://www.observatoriorealidadsocial.es/es/estudios/evolucion-del-empleo-en-navarra-diciembre-2023-informe-mensual/es-590756/

Evolución del empleo en Navarra. Diciembre 2023. Informe mensual. Gobierno de Navarra , Pamplona, 2023, 29 p.

### Descripción

Innovación social
Evaluación de políticas públicas.

### Fecha de inicio

Aproximadamente 2016 (primeros estudios publicados como observatorio)

### En activo

Sí

**Comment by JaimeObregon** [comment]
Añadido.
